### ISSUE TITLE
Documentation Sprint Issue

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1040]
Reference this issue when making PRs for the Islandora 8 Documentation.  Let's see how long of a list of mentions we can make!

Please see [this spreadsheet](https://docs.google.com/spreadsheets/d/1wI_K5Y0XJSIBXoJ84VxObcy8TT07TuypIE_P3C0rnzU/edit#gid=0) to sign up for anything or to add any ideas for documentation gaps that still exist.

**Comment by alexkent0** [comment]
First draft (Word doc) on creating a collection/what is a collection (will add more on what is a collection)
[Islandora 8 creating a collection.docx](https://github.com/Islandora-CLAW/CLAW/files/2938373/Islandora.8.creating.a.collection.docx)

**Comment by alexkent0** [comment]
First draft (Word doc) on loading media 
[Islandora 8 loading media.docx](https://github.com/Islandora-CLAW/CLAW/files/2938378/Islandora.8.loading.media.docx)

**Comment by dannylamb** [comment]
@alexkent0 Any chance you can export those to markdown?  I'd like to get PRs going with those.  Good stuff.

**Comment by alexkent0** [comment]
@dannylamb, can you point me in the right direction to that? I haven't done it before. Thanks!

**Comment by dannylamb** [comment]
Sprint complete!

**Comment by dannylamb** [comment]
Starting another one!

**Comment by manez** [comment]
Sprints complete, closing issue 😄
