### ISSUE TITLE
Shifting Ports

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#1075]
As a suggested improvement for the VM, can we shift all of the ports up in the VM to not conflict with Islandora 7's VM?

Testing the 2 VMs side by side could be done easy without any manual modifications requirement by shifting the exposed ports up by 1 or set them "auto_correct: true" so spinning up Islandora 8 on top of 7 would not cause any failures. 

```Vagrantfile
# shift up by one
...
config.vm.network :forwarded_port, guest: 8000, host: 8001
config.vm.network :forwarded_port, guest: 8080, host: 8081
...

# OR automatically assign
...
config.vm.network :forwarded_port, guest: 8000, host: 8000, auto_correct: true
config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
...
```

**Comment by DonRichards** [comment]
Not sure how changing the ports to an unknown/random port will behave when using the auto_correct feature. It's just an option I thought I should mention.

**Comment by DonRichards** [comment]
Or use a parameter to fire a specified function instead of the default: `$ vagrant up compare_vms`

```vagrantFile
config.vm.define "compare_vms" do |db|
...
config.vm.network :forwarded_port, guest: 8000, host: 8001
config.vm.network :forwarded_port, guest: 8080, host: 8081
...
end
```
[Example](http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/) of the behavior

**Comment by dannylamb** [comment]
FWIW I've always prepended a 1 to the ports on my Islandora 7 boxes.  E.g. 8000 -> 18000, etc...

In the end, I don't care what we make the ports out to be.  Should just be some simple changes to the vagrant file and a handful of pertinent ansible variables.

**Comment by rangel35** [comment]
any thoughts on prepending a version number 78000 for I7 88000 for I8

**Comment by DonRichards** [comment]
This ticket should be closed.
