### ISSUE TITLE
 Upload destination configuration for file media type

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1103]
The storage configuration option "Upload destination" is configurable for image, video and audio, but not for file. Is there a specific reason why it is not configurable for file media type?

**Comment by dannylamb** [comment]
It is definitely not by design or on purpose from anything we're doing.  So either we've misconfigured `field_media_file` or it's a Drupal thing.

**Comment by Natkeeran** [comment]
@dannylamb 

Are you able to confirm this issue?

**Comment by dannylamb** [comment]
Seems to be ok on a fresh playbook.  Here's the field settings for `field_media_file` on the `File` media type.

![Screenshot from 2019-04-26 13-30-41](https://user-images.githubusercontent.com/20773151/56822499-a1dae000-6827-11e9-990b-d184ba4d13f9.png)

**Comment by seth-shaw-unlv** [comment]
Works on the most recent build:
<img width="1143" alt="Screen Shot 2019-05-01 at 10 52 55 AM" src="https://user-images.githubusercontent.com/29869988/57032458-47fb6100-6bff-11e9-927e-839fd0e175af.png">

**Comment by Natkeeran** [comment]
@seth-shaw-unlv are you able to select Public files option?

**Comment by seth-shaw-unlv** [comment]
Not when I took the initial screenshot, because I had already created a File Media. But, after I deleted it, the option became available:
<img width="1150" alt="Screen Shot 2019-05-01 at 11 48 16 AM" src="https://user-images.githubusercontent.com/29869988/57035484-02db2d00-6c07-11e9-8acb-b72c865e2d6d.png">
