### ISSUE TITLE
Batch update items membership and other properties

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1104]
Currently, there does not seem to be a way to migrate or assign collection membership to more than one item at a time.  Providing a method to batch update membership and other properties will help a lot with collections and metadata management.

https://www.drupal.org/project/views_bulk_edit might help here.

**Comment by manez** [comment]
I think this one's a winner. It took me minutes to set up a View that lets me bulk edit collection membership via the GUI. All other fields are accessible for bulk editing too. And there are many other actions that can be turned on. 

![image](https://user-images.githubusercontent.com/2371345/57034491-07630e00-6c26-11e9-81c2-87b5c119df8d.png)

**Comment by mjordan** [comment]
@Natkeeran does what @manez demoed in the recent Views webinar solve this?

**Comment by kstapelfeldt** [comment]
Acknowledging that there is more required here, but we will need use cases to govern that work. This is a way of getting us started.
