### ISSUE TITLE
Can't log in to tomcat manager on playbook

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#1118]
The documentation on the playbook says:

>  Tomcat Manager
>
 >   username: islandora
  >  password: islandora
>
>You can access the Tomcat Manager administration UI at http://localhost:8080/manager

And in trying to, I can't. I get a 403 page with no chance to log in. The username and password are in `/var/lib/tomcat8/conf/tomcat-users.xml` (symlinked to  `etc/tomcat8/tomcat-users.xml`) but my hacky edits to it or context.xml aren't coming up with any login screen.

**Comment by whikloj** [comment]
I'm just bringing up a new playbook, so I haven't yet tested this. But my guess is that this is in no way valid anymore. The Syn tomcat Valve will require a JWT. So you could try the `Authorization: Bearer islandora` and see where that gets you but I'm guessing it still won't work.

**Comment by pathintegral** [comment]
I can't access to /manager too. Is there any update on this?

**Comment by dannylamb** [comment]
^^ Just made a PR that removes the tomcat manager piece from the README.  It is locked down due to JWT's, and you'd have to completely disable syn in order to access it.
