### ISSUE TITLE
Migrations from a 7.x still working?

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1145]
Running a 1.0.0 vagrant from the GUI, I'm unable to successfully migrate some objects and their collection from a 7.x using https://github.com/Islandora-Devops/migrate_7x_claw. I have migrated from the same 7.x in the past (but it was pretty far back in the past). 

I had better luck running the migration using drush, but even then, none of the media came over. Curiously, all of the AUDIT files did, but not their media.

@MarcusBarnes  and I would love to demo this at the iCampEU. If someone has the time, can they try to perform a migration to see if it works for them to eliminate user error (a real possibility)?

If you want to try against the 7.x I'm using, I can share its IP address offline.

**Comment by mjordan** [comment]
Forgot to add, the migration is producing no messages.

Here's a screengrab of the migrations:

![migration](https://user-images.githubusercontent.com/403918/59042024-8ef7fa00-882e-11e9-980d-fc9f460fe835.png)

**Comment by whikloj** [comment]
@mjordan I think this is the same problem I was having when getting ready for Fedora Camp. I had to do https://github.com/Islandora-Devops/migrate_7x_claw/pull/15

You'll note in your screen shot that **Islandora Files** and **Islandora Media** report **0 TOTAL**

**Comment by mjordan** [comment]
@whikloj thanks, I'll give that a try.

**Comment by mjordan** [comment]
@whikloj  you are a wizard. That got me a lot further. All of my objects are now discovered and have migrated intact... but now I've hit a new problem which I will open another issue for.

Any reason that PR you pointed me to shouldn't be merged?

**Comment by whikloj** [comment]
@dannylamb had a concern as too why it was working before without this. I'm not clear how it worked without this either. So no real reason, just trying to understand what is going on.

**Comment by mjordan** [comment]
Maybe it'd be best for someone else to try a migration to see if it's just me.

**Comment by mjordan** [comment]
I mention this issue in #1147 so I'll close this one for now.
