### ISSUE TITLE
Update install docs

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1150]
I ran into a few snaffus spinning up https://future.islandora.ca and there's a few spots in the README that need to be updated.  We should put more detailed instructions on provisioning a non-development server in the actual docs, too.  And not just in the README.

**Comment by ajstanley** [comment]
maybe a note about changing url endpoints in the blueprint.xmls?

**Comment by dannylamb** [comment]
@ajstanley I think ^^ should cover it
