### ISSUE TITLE
Update installer to use Carapace 8.x-3.x

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1151]
Found this one out by surprise in the middle of the release.  I overreached a bit and tried to get this in, but it was too rushed.  Let's pull this in to dev as soon as possible and include it in the next release.

**Comment by seth-shaw-unlv** [comment]
Is that the theme on futures? It looks good!

**Comment by dannylamb** [comment]
The sandbox has https://www.drupal.org/project/solid on it.
