### ISSUE TITLE
centos based vagrant fails

### ISSUE THREAD

**Issue by pc37utn** [Islandora/documentation#1152]
This is a fresh clone after vagrant destroy and only the env for centos changed.
My settings are below and the last couple pages of output from when it starts messing up are below.
OS: Fedora 30

VirtualBox 6.0.8

vagrant version 2.2.4

vagrant plugin list
vagrant-vbguest (0.18.0, global)
  - Version Constraint: > 0

ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/paulc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

--------------

TASK [geerlingguy.drupal : include_tasks] **************************************
Friday 07 June 2019  16:41:27 -0400 (0:00:00.019)       0:06:54.383 *********** 
[DEPRECATION WARNING]: evaluating drupal_build_composer_project as a bare 
variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle..
 This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
included: /home/paulc/GITarea/claw-playbook/roles/external/geerlingguy.drupal/tasks/build-composer-project.yml for default

TASK [geerlingguy.drupal : Delete old /tmp/composer-project] *******************
Friday 07 June 2019  16:41:27 -0400 (0:00:00.032)       0:06:54.415 *********** 
ok: [default]

TASK [geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while).] ***
Friday 07 June 2019  16:41:27 -0400 (0:00:00.281)       0:06:54.696 *********** 
changed: [default]

TASK [geerlingguy.drupal : Ensure drupal_composer_install_dir directory has proper permissions.] ***
Friday 07 June 2019  16:42:44 -0400 (0:01:16.893)       0:08:11.590 *********** 
changed: [default]

TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***
Friday 07 June 2019  16:42:44 -0400 (0:00:00.284)       0:08:11.874 *********** 
changed: [default]

TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
Friday 07 June 2019  16:42:46 -0400 (0:00:01.749)       0:08:13.624 *********** 
changed: [default] => (item=zaporylie/composer-drupal-optimizations:^1.0)
ok: [default] => (item=drupal/console:~1.0)
changed: [default] => (item=drupal/devel:^2.0)
failed: [default] (item=drupal/rdfui:^1.0-beta1) => {"ansible_loop_var": "item", "changed": false, "item": "drupal/rdfui:^1.0-beta1", "msg": "./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Package operations: 1 install, 0 updates, 0 removals - Installing drupal/rdfui (1.0.0-beta1): Downloading (100%) Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested. Writing lock file Generating optimized autoload files - .csslintrc (https://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%) \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%) - .editorconfig (https://cgit.drupalcode.org/drupal/plain/.editorconfig?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%) \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%) - .eslintignore (https://cgit.drupalcode.org/drupal/plain/.eslintignore?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%) \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%) - .eslintrc.json (https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.6.10): Downloading (connecting...) [Composer\\Downloader\\TransportException] The \"https://git.drupalcode.org/project/drupal/raw/8.6.10/.eslintrc.json\" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known drupal:scaffold Script @composer drupal:scaffold handling the post-update-cmd event returned with error code 1 Installation failed, reverting ./composer.json to its original content.", "stdout": "./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 1 install, 0 updates, 0 removals\n  - Installing drupal/rdfui (1.0.0-beta1): Downloading (100%)\nPackage phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.\nWriting lock file\nGenerating optimized autoload files\n  - .csslintrc (https://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - .editorconfig (https://cgit.drupalcode.org/drupal/plain/.editorconfig?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - .eslintignore (https://cgit.drupalcode.org/drupal/plain/.eslintignore?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - .eslintrc.json (https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.6.10): Downloading (connecting...)\n                                                                                                                                                                                   \n  [Composer\\Downloader\\TransportException]                                                                                                                                         \n  The \"https://git.drupalcode.org/project/drupal/raw/8.6.10/.eslintrc.json\" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known  \n  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known                                                                                   \n                                                                                                                                                                                   \n\ndrupal:scaffold\n\nScript @composer drupal:scaffold handling the post-update-cmd event returned with error code 1\n\nInstallation failed, reverting ./composer.json to its original content.\n", "stdout_lines": ["./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Package operations: 1 install, 0 updates, 0 removals", "  - Installing drupal/rdfui (1.0.0-beta1): Downloading (100%)", "Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.", "Writing lock file", "Generating optimized autoload files", "  - .csslintrc (https://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)", "  - .editorconfig (https://cgit.drupalcode.org/drupal/plain/.editorconfig?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)", "  - .eslintignore (https://cgit.drupalcode.org/drupal/plain/.eslintignore?h=8.6.10): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)", "  - .eslintrc.json (https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.6.10): Downloading (connecting...)", "                                                                                                                                                                                   ", "  [Composer\\Downloader\\TransportException]                                                                                                                                         ", "  The \"https://git.drupalcode.org/project/drupal/raw/8.6.10/.eslintrc.json\" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known  ", "  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known                                                                                   ", "                                                                                                                                                                                   ", "", "drupal:scaffold", "", "Script @composer drupal:scaffold handling the post-update-cmd event returned with error code 1", "", "Installation failed, reverting ./composer.json to its original content."]}
changed: [default] => (item=drupal/restui:^1.16)
changed: [default] => (item=drupal/search_api_solr:^2.0)
changed: [default] => (item=drupal/facets:^1.3)
changed: [default] => (item=drupal/content_browser:^1.0@alpha)
changed: [default] => (item=drupal/matomo:^1.7)
changed: [default] => (item=drupal/pdf:1.x-dev)
changed: [default] => (item=islandora/carapace:1.0.0)
changed: [default] => (item=islandora/islandora_defaults:1.0.0)

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************
Friday 07 June 2019  16:47:31 -0400 (0:04:44.992)       0:12:58.617 *********** 

RUNNING HANDLER [Islandora-Devops.matomo : restart apache] *********************
Friday 07 June 2019  16:47:31 -0400 (0:00:00.000)       0:12:58.617 *********** 

PLAY RECAP *********************************************************************
default                    : ok=143  changed=50   unreachable=0    failed=1    skipped=98   rescued=0    ignored=0   

Friday 07 June 2019  16:47:31 -0400 (0:00:00.000)       0:12:58.617 *********** 
=============================================================================== 
geerlingguy.drupal : Install dependencies with composer require (this may take a while). - 284.99s
geerlingguy.php : Ensure PHP packages are installed. ------------------ 195.05s
geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while). -- 76.89s
geerlingguy.solr : Download Solr. -------------------------------------- 49.27s
geerlingguy.apache : Ensure Apache is installed on RHEL. --------------- 27.91s
install extra packages centos ------------------------------------------ 22.40s
geerlingguy.java : Ensure Java is installed. --------------------------- 17.57s
geerlingguy.git : Ensure git is installed (RedHat). -------------------- 13.97s
geerlingguy.solr : Run Solr installation script. ----------------------- 10.48s
geerlingguy.mysql : Ensure MySQL packages are installed. ---------------- 7.08s
geerlingguy.mysql : restart mysql --------------------------------------- 6.37s
geerlingguy.solr : restart solr ----------------------------------------- 6.06s
geerlingguy.php-mysql : Install PHP MySQL dependencies (RedHat). -------- 5.24s
geerlingguy.solr : Expand Solr. ----------------------------------------- 4.34s
geerlingguy.mysql : Ensure MySQL is started and enabled on boot. -------- 3.96s
geerlingguy.solr : Ensure solr is started and enabled on boot if configured. --- 3.48s
geerlingguy.solr : Create configured cores. ----------------------------- 2.98s
geerlingguy.solr : Ensure solr is stopped (RHEL 7 workaround). ---------- 2.59s
geerlingguy.solr : Ensure dependencies are installed. ------------------- 2.39s
geerlingguy.repo-remi : Install remi repo. ------------------------------ 2.04s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by whikloj** [comment]
I upgraded my ansible from 2.7.6 to 2.8.1 and am trying Centos now

**Comment by dannylamb** [comment]
It blows up on `rdfui`?  That is strange.  I highly doubt they've had a recent update, but I'll check.  Sometimes when my internet is bad I'll get similar messages when it can't pull from packagist.

FWIW a centos build with Ansible 2.7.5, VBox 5.1.38_Ubuntu r122592, and Vagrant 2.1.2 spins up alright, but that doesn't mean much if you can consistently reproduce this error.  The problem is probably due to other factors.

**Comment by whikloj** [comment]
I just built a Centos box on `1.0.0` and did not receive this error. @pc37utn could you give this another try please?

**Comment by pc37utn** [comment]
ok, I did a vagrant destroy and vagrant up and it completed this time.
================

PLAY RECAP *********************************************************************
default                    : ok=412  changed=201  unreachable=0    failed=0    skipped=183  rescued=0    ignored=1   

Monday 10 June 2019  13:27:17 -0400 (0:00:00.469)       0:28:31.409 *********** 
=============================================================================== 
geerlingguy.drupal : Install dependencies with composer require (this may take a while). - 263.50s
geerlingguy.php : Ensure PHP packages are installed. ------------------ 194.74s
geerlingguy.php : Ensure PHP packages are installed. ------------------ 191.37s
Islandora-Devops.alpaca : Add Alpaca Features ------------------------- 180.91s
Islandora-Devops.crayfish : Install requisite packages ---------------- 104.25s
geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while). -- 90.42s
Islandora-Devops.grok : Make grok -------------------------------------- 62.38s
Islandora-Devops.grok : Install Grok dependencies (yum) ---------------- 34.82s
geerlingguy.apache : Ensure Apache is installed on RHEL. --------------- 31.95s
geerlingguy.drupal : Install configured modules with drush. ------------ 25.45s
Islandora-Devops.crayfish : Build crayfish code including dependencies -- 24.30s
install extra packages centos ------------------------------------------ 19.31s
Islandora-Devops.matomo : Download Matomo. ----------------------------- 18.73s
geerlingguy.solr : Download Solr. -------------------------------------- 18.53s
geerlingguy.git : Ensure git is installed (RedHat). -------------------- 17.23s
Islandora-Devops.blazegraph : Wait for Blazegraph to come up ----------- 16.41s
geerlingguy.java : Ensure Java is installed. --------------------------- 14.98s
Islandora-Devops.drupal-openseadragon : Install Openseadragon with composer -- 14.94s
Islandora-Devops.activemq : Download and unarchive --------------------- 13.03s
Islandora-Devops.fcrepo : Download fcrepo war (post 5.0.0) ------------- 12.79s
Press any key to continue...

**Comment by pc37utn** [comment]
Must be network/repo issues?
