### ISSUE TITLE
Normalize CONTRIBUTING.md and add it where it's missing

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1173]
While working on updating readmes for https://github.com/Islandora-CLAW/CLAW/issues/1082 I discovered a few different versions of CONTRIBUTING.md floating around, and a few repos that don't have one at all. 

They should all be the same, and every repo should have one. 

Examples:

* Needs a light update for Islandora 8, but otherwise good: https://github.com/Islandora-CLAW/CLAW/blob/master/CONTRIBUTING.md
* Out of date: https://github.com/Islandora-CLAW/chullo/blob/dev/CONTRIBUTING.md
* No CONTRIBUTING.md: https://github.com/Islandora-Devops/migrate_7x_claw (yeah, it's Dev-Ops, but we might as well be consistent)

**Comment by manez** [comment]
Proposed CONTRIBUTING.md to be applied across the board: https://gist.github.com/manez/74b7fdda05cd01186c1d9b471c61b9dc

This is basically the CONTRIBUTING.md from the core CLAW repo, de-CLAWed, with some extra bits about our Code of Conduct, irc channel, and a link to the list of CLAs.

If it looks good, I'll start pull requests to update or add this wording on al our 8 and dev-ops repos.

**Comment by whikloj** [comment]
The above git of the CONTRIBUTING.md looks good, I am wondering if we should be looking at a repository rename for CLAW -> Islandora_8 (or something) sooner rather than later. I am wondering if people expected Islandora 8 will be confused by CLAW or am I overthinking this.

**Comment by manez** [comment]
The repo name issue is on the agenda for the TAG's next meeting https://github.com/Islandora/islandora/wiki/TAG-Meeting---June-28 hoopefully with reccomendations soon to follow.

**Comment by manez** [comment]
Note to self: address #1175 and tweak #1177 to update Committers group, as long as I'm doing pull requests all over the place.

**Comment by dannylamb** [comment]
Awesome, thx @manez
