### ISSUE TITLE
Add PR Template to Islandora-Devops Ansible Roles

### ISSUE THREAD

**Issue by jonathangreen** [Islandora/documentation#1177]
@dbernstein noticed when submitting https://github.com/Islandora-Devops/ansible-role-tomcat8/pull/8 that the Ansible roles don't have our PR template. Might be good to ad them. Figured I'd make a ticket so we don't forget about it.

**Comment by jonathangreen** [comment]
PR template file is here: 
https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/.github/PULL_REQUEST_TEMPLATE.md

**Comment by seth-shaw-unlv** [comment]
This must have auto-closed when I merged the referenced PR. Reopening as we should make sure the other roles also have the template.

**Comment by dbernstein** [comment]
There are template PRs for all the other roles.
