### ISSUE TITLE
Running phpcs on the Vagrant is undocumented

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1182]
`phpcs` is absent from the Vagrant. Looks like it was provided [pre-Ansible](https://github.com/Islandora-CLAW/CLAW/issues/32).

Running the following shell script from within the drupal install directory, cribbed from the [travis setup](https://github.com/Islandora-CLAW/CLAW/blob/master/.scripts/travis_setup_drupal.sh#L6), works:

```sh
#!/bin/bash

echo "Install utilities needed for testing"
mkdir /opt/utils
cd /opt/utils
if [ -z "$COMPOSER_PATH" ]; then
  composer require drupal/coder
else
  php -dmemory_limit=-1 $COMPOSER_PATH require drupal/coder
fi
sudo ln -s /opt/utils/vendor/bin/phpcs /usr/bin/phpcs
phpcs --config-set installed_paths /opt/utils/vendor/drupal/coder/coder_sniffer
```

Not sure if using shell like this is cool within the Playbook.

**Comment by dannylamb** [comment]
It's available in the ansible environment at
/var/www/html/drupal/vendor/bin/phpcs. Same goes for phpcbf and phpunit.
Although making those globally available isn't a terrible idea.

**Comment by mjordan** [comment]
OK, cool. I think we should add a page the developer docs that explains how to use it. I can open a PR.

**Comment by mjordan** [comment]
In `/var/www/html/drupal`, running `./vendor/bin/phpcs --standard=Drupal web/modules/contrib/islandora/src/Plugin/Condition/MediaHasMimetype.php` results in the following:
 
`ERROR: the "Drupal" coding standard is not installed. The installed coding standards are MySource, PSR1, Squiz, PSR12, PEAR, Zend and PSR2`

Is there another step I should be taking?

**Comment by dannylamb** [comment]
You have to provide the full path to the Drupal sniff.

/var/www/html/drupal/vendor/drupal/coder/coder_sniffer/Drupal

Definitely a documentation gap. I have phpcs and phpunit invocations burned
into my brain, which isn't terribly helpful for everyone else.

**Comment by mjordan** [comment]
OK, in /var/www/html/drupal, running `./vendor/bin/phpcs --standard=/var/www/html/drupal/vendor/drupal/coder/coder_sniffer/Drupal  web/modules/contrib/islandora/src/Plugin/Condition/MediaHasMimetype.php` works as expected. Want me to open a PR to add that docs page?

**Comment by mjordan** [comment]
Closing this one, please use #1207.
