### ISSUE TITLE
Some UX tweaks for content managers

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1186]
I'd like to suggest a couple of tweaks that I think would improve the UX for people adding and editing content. These are just suggestions, counter arguments are welcome.

## Move the "System" field group in the repository item add/edit form to the top

This field group contains the only required field (besides the title) for that content type. I think it should go at the top of the form, not be burried down at the end.

## When adding Media, on form submission, Drupal should redirect to the node edit form, not to the list of media.

There is no easy way back to the node from that list.

## Default value of the "Media Use" list in the GUI should be "Original File". 

Currently it is "None". Most times this list will be used it to upload an original file.

I know that many of these things are trivial to change locally (e.g., the location of the "System" field group) but I'm thinking of first impressions.

**Comment by manez** [comment]
- **Move the "System" field group in the repository item add/edit form to the top** - No strong feelings. It's a bit awkward at the end, but I'm used to scrolling all the way down for save/publish options in Drupal, so this one hasn't bothered me.

- **When adding Media, on form submission, Drupal should redirect to the node edit form, not to the list of media.** - Yes please!

- **Default value of the "Media Use" list in the GUI should be "Original File".** Yes please! And add some help text. I've been trying to figure out how to do a PR for this, but haven't quite hunted down where this configuration lives in the code.
`Defined by Portland Common Data Model: Use Extension https://pcdm.org/2015/05/12/use. 'Original File' will trigger creation of derivatives.` as a suggestion.

**Comment by mjordan** [comment]
> It's a bit awkward at the end, but I'm used to scrolling all the way down for save/publish options in Drupal, so this one hasn't bothered me.

Good point. Might be more of a personal preference, and I can see where some people might not like it at the top.

**Comment by dannylamb** [comment]
@manez Default value can be set on a per bundle basis.  For example, for Image media: http://localhost:8000/admin/structure/media/manage/image/fields/media.image.field_media_use

You'd have to set that to Original File for all the other media types too, but it's not too onerous.

Awesome suggestions, btw @mjordan.

**Comment by mjordan** [comment]
Another one: an action that combines "Delete content", "Delete Node from Fedora", and "Delete Node from Triplestore". It's a PITA to have to do all three if you want to purge all aspects of an object.

**Comment by dannylamb** [comment]
If you just delete content, the others will trigger in response to the
delete event. Or at least they should. The one I would add is 'Delete
object and all media'.

**Comment by manez** [comment]
@dannylamb I'm clear on how to change it in the front end (Drupal Form GUI :heart_eyes:) but I'm not sure how to put it into a pull request so that it builds that way from now on

**Comment by manez** [comment]
After some advice from @seth-shaw-unlv on the last tech call, I think I've got the right place to make changes, and the right changes in place. Now, can anyone help me figure out how to test them? Can I point claw-playbook at my fork of islanodra_defaults to make sure the form edits show up as their supposed to? How?

**Comment by seth-shaw-unlv** [comment]
If you take a box that is already setup you can vagrant ssh in, change to the relevant module directory,  pull in your branch’s changes, then do a feature import.

Doing it from the playbook is best done on a branch of the official repos, rather than forks.

**Comment by manez** [comment]
"vagrant ssh in, change to the relevant module directory, pull in your branch’s changes" this is kind of where I wander into the woods and get lost, but I'll keep at it.

Edit: Success! Shenanigans involved to use a GUI to SSH into my VM, but success!

**Comment by mjordan** [comment]
PR merged in fef6b30eab3b0c365e82c902122f67f2da152ca7.
