### ISSUE TITLE
EVA 8.x-1.3 no longer supported

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1187]
https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/composer.json refers to `"drupal/eva" : "^1.3"` but that version is no longer supported and `8.x-2.0-rc3` is recommended.

**Comment by kayakr** [comment]
Current version of EVA is 8.x-2.0.

**Comment by dannylamb** [comment]
resolved via https://github.com/Islandora/islandora/commit/26bfd76a38f87cbda4110f1cfd048ef909e766e9
