### ISSUE TITLE
Updating PR templates with correct committers tags

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1188]
As highlighted by @whikloj on [another issue](https://github.com/Islandora-Devops/ansible-role-fits/pull/1#issuecomment-505491080), and discussed in [today's meeting](https://github.com/Islandora-CLAW/CLAW/wiki/June-26%2C-2019), some of the PR templates in the Islandora-Devops community repos (e.g. [claw-playbook](https://github.com/Islandora-Devops/claw-playbook/blob/dev/.github/PULL_REQUEST_TEMPLATE.md)) use @Islandora-CLAW/committers (which won't work in that community) instead of @Islandora-Devpos/committers.

Fortunately, @manez [graciously agreed to do updates as part of other PRs](https://github.com/Islandora-CLAW/CLAW/issues/1173#issuecomment-505980702). 

We should also review the list's members to ensure it is up-to-date.

**Comment by dannylamb** [comment]
Done!
