### ISSUE TITLE
NodeHadNamespace condition uses hard-coded field, should use configured field

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1199]
https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/Plugin/Condition/NodeHadNamespace.php#L148 uses `$entity->hasField('field_pid'))`, should use `$entity->hasField($pid_field))`. My apologies, I'll open a PR.

**Comment by seth-shaw-unlv** [comment]
No worries, I should have caught that during the review before merging it. I'll be more careful.

**Comment by mjordan** [comment]
Me too!

**Comment by mjordan** [comment]
Resolved with a956f5a4a9be9ed428073d509492f0f1685d7993.
