### ISSUE TITLE
Add license files to Devops repos

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1202]
Most of the repos in https://github.com/Islandora-Devops don't have an actual license file, although they do have a license listed in their readmes. I'm going to be doing a bunch of prs for [CONTRIBUTING.md](https://github.com/Islandora-CLAW/CLAW/issues/1173) and the [pull request template](https://github.com/Islandora-CLAW/CLAW/issues/1188), so I'll include fixing this as well.

**Comment by manez** [comment]
There's one odd one out: https://github.com/Islandora-Devops/ansible-role-matomo has a GPLv3 license already attached. As noted in [this pr](https://github.com/Islandora-Devops/ansible-role-matomo/pull/4) should this be MIT?

**Comment by dannylamb** [comment]
All non-drupal code is supposed to MIT.  I'm not sure what the implications of just changing the license are... but we can do that.

**Comment by dannylamb** [comment]
Done.  Again, thx @manez.
