### ISSUE TITLE
Document how to replace a media

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1208]
In Islandora 7.x we have the ability to replace a datastream:

![replace_datastream](https://user-images.githubusercontent.com/403918/60693806-837d0a80-9e90-11e9-8774-45fd2a49a512.png)

In Islandora 8, you must "Remove" the file and replace it with another:

![media](https://user-images.githubusercontent.com/403918/60693866-baebb700-9e90-11e9-8d0a-fcc5054b47e8.png)

This should be documented at https://islandora-claw.github.io/CLAW/user-documentation/datastreams/.

Related issue: #1035.

**Comment by dannylamb** [comment]
You should link out to https://islandora-claw.github.io/CLAW/technical-documentation/rest-create/#files-and-media as well to point out that there's ways to do this headlessly.

**Comment by mjordan** [comment]
PR merged.

**Comment by rosiel** [comment]
I don't know if this is in scope. But does this process still leave the original file and its metadata floating around in Fedora? @dannylamb

**Comment by mjordan** [comment]
Reopening this, since the [text added by the above PR](https://github.com/Islandora/documentation/pull/1221/files) does not appear in https://islandora.github.io/documentation/user-documentation/media/ (maybe it was removed subsequently?), so that documentation still does not explain how to replace a media or file.

@rosiel to answer your question ^^, if I replace the file as described in the PR at https://github.com/Islandora/documentation/pull/1221/files, the file and its metadata remain in Fedora.

Also, if I delete the media at http://localhost:8000/media/X/delete, the binary and its metadata persist in Fedora. I've just verified this by adding a media, visiting it Fedora, then deleting the media, and revisiting it and its metadata in Fedora. Still there.

The only way I've found of verifiably deleting a file and its metadata is to run the "Delete media and file(s) action" in the general media list (http://localhost:8000/admin/content/media). Revisiting the file and its metadata in Fedora returns 404s.

This is all very confusing. I'd love to see a way to:

1. replace a file, along with the option to completely purge the one you think you're deleting or to create a new version of the file and accompanying metadata (i.e., keep the old file too by not make it the current revision)
1. delete (i.e. completely nuke from "Islandora") a file and its accompanying media and metadata

I wonder how we can wire up the code in the "Delete media and file(s) action" so that the user doesn't have to go to http://localhost:8000/admin/content/media to actually delete a file and its media but instead can do it closer to the node the file is associated with.

**Comment by mjordan** [comment]
Thinking about some UI options for this. These options are not "closer to the node the file is associated with" but they are closer to the existing UI for managing the specific media.

> if I replace the file as described in the PR at https://github.com/Islandora/documentation/pull/1221/files, the file and its metadata remain in Fedora.

We could allow the user to choose whether the file and its metadata remain in Fedora (current behavior) or do not (expected behavior):

![remove_media](https://user-images.githubusercontent.com/403918/87857560-99633f00-c8dc-11ea-930a-9677e58b3162.png)


> if I delete the media at http://localhost:8000/media/X/delete, the binary and its metadata persist in Fedora.

We could allow the user to choose whether the media remains in Fedora (current behavior) or does not (expected behavior):

![delete_media](https://user-images.githubusercontent.com/403918/87857264-396b9900-c8da-11ea-9ed8-4467ed25ea13.png)

Also, these options should only be present if Fedora is being used.

**Comment by rosiel** [comment]
Thank you for validating that, @mjordan ! Would it be appropriate to document the current actual behaviour in the documentation? I would like to make a PR.

**Comment by mjordan** [comment]
Sounds good to me, until we can come to a landing on how to implement the desired behavior. @manez any thoughts on the docs?

**Comment by mjordan** [comment]
@rosiel 's improvements to the doc have been merged, but should I close this issue and open a new one for the UI mods described above?

**Comment by rosiel** [comment]
Sounds good, as this is a "document" ticket.

I like your suggestions, by the way.

**Comment by mjordan** [comment]
Thanks! Will close this one and open a new one.
