### ISSUE TITLE
Is Published Condition

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1214]
I would like to enable my repository to only index published nodes in Fedora. The easiest way to do this is adding a NodeIsPublished condition that I can add to the "Content" context conditions. I don't think this needs to be the default, but I think it is a good capability to have. 

I'm not doing one for Media (yet) because I'm not sure about the Flysystem implications of doing so.

PR incoming.

**Comment by mjordan** [comment]
Merged.
