### ISSUE TITLE
Drupal reassigns node IDs

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1215]
I have narrowed down circumstances in which Drupal reassigns node IDs. The conditions for this to happen are that that no nodes exist (in other words, the highest node ID value at the time is 0), and it only happens just after you boot the Vagrant. You can replicate this behavior by doing the following:

1. delete all nodes from your Vagrant and `vagrant halt` it.
1. `vagrant up` it.
1. create a new node (content type doesn't matter).
1. it will have the node ID of 1.

I am assuming that this behavior is a side effect of how MySQL's autoincrement fields work, so it should not be a problem in production (where you wouldn't be restarting at 0). But, at least I can say I was not imagining this.

![not crazy](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2F736x%2F20%2F7a%2Fba%2F207abac4d4226c3446fd135f2ea219a3--futurama-simpsons-simpsons-funny.jpg&f=1)

**Comment by dannylamb** [comment]
Wow...

Artifact of mysql peculiarities plus virtualization subtleties...

That's a scary one.

**Comment by mjordan** [comment]
Could also explain things @manez was describing, since orphaned media would be associated with a node ID that was reused.

**Comment by mjordan** [comment]
Closed during July 17 tech call.
