### ISSUE TITLE
Move microservices from Silex to Symfony 4

### ISSUE THREAD

**Issue by whikloj** [Islandora/documentation#1224]
This ticket is to alter the existing microservices from the now deprecated Silex framework to symfony-flex.

**Comment by mjordan** [comment]
FWIW, [Riprap](https://github.com/mjordan/riprap), while not a core microservice, is in Symfony 4, as is [Islandora Bagger](https://github.com/mjordan/islandora_bagger). I think UPEI's FITS microservice is Symfony 4 as well.

**Comment by dannylamb** [comment]
Yep, it's called [Crayfits](https://github.com/roblib/CrayFits)

**Comment by whikloj** [comment]
@mjordan then you should be able to depend on `"islandora/crayfish-commons:dev-symfony-flex"` and configure it to use the JWT token authentication like in https://github.com/Islandora-CLAW/Crayfish/pull/73

**Comment by jordandukart** [comment]
@whikloj what's the status of this issue?

**Comment by whikloj** [comment]
I have a Homarus branch that was working, but now needs to be revisited.

Also (and the ticket # escapes me) there is an issue around moving
Crayfish-Commons to Symfony 5 to @seth-shaw-unlv and @elizoller where
discussing that issue.

Now that I have a working playbook, I'll see if I can't just do all the
remaining microservices as 1 PR.

**Comment by whikloj** [comment]
🥲 resolved with https://github.com/Islandora/Crayfish/commit/82320e5e6c4360b2dfceb658a43c543bff885a04
