### ISSUE TITLE
OpenSeaDragon fails to load image on translated nodes

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1226]
## Summary
OpenSeaDraogn fails to load image on translated nodes

## Steps to reproduce
* Enable a second language
* Create an image with display tag openseadragon
* (The image is displayed in the openseadragon)
* Translate the node
* The image is not displayed in the openseadragon
* It gets a 404 error

**Comment by whikloj** [comment]
Checking this (and possibly #1121) out. 

It appears that when I view `http://localhost:8000/node/9` the `tileSources` passed to OpenSeadragon is `http://127.0.0.1:8080/cantaloupe/iiif/2/_flysystem%2Ffedora%2F2019-08%2F0066.tif`

But when I go to `http://localhost:8000/fr/node/9` then the `tileSources` passed to OpenSeadragon is `http://127.0.0.1:8080/cantaloupe/iiif/2/http%3A%2F%2Flocalhost%3A8000%2F_flysystem%2Ffedora%2F2019-08%2F0066.tif`

So I am guessing the host part is causing the issue.

**Comment by whikloj** [comment]
Right [here](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/openseadragon.module#L87), when accessing a translated node the base URI has the language code but the full path to the file does not.

ie. 

`base_path = http://localhost:8000/fr`

`resource.full_path = http://localhost:8000/_flysystem/fedora/2019-08/0066.tif`

It appears that we don't currently support tile sources not on the same machine as the Drupal box.

**Comment by whikloj** [comment]
Ok, this is self inflicted. We have configured cantaloupe to look at a specific URL as the HttpResolver prefix.

https://github.com/Islandora-Devops/claw-playbook/blob/dev/inventory/vagrant/group_vars/tomcat.yml#L66

We should set the prefix to "" and set `$base = "";` ([here](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/openseadragon.module#L87)) instead of the assumed base URI. Then it works.

I'll open some PRs.

**Comment by dannylamb** [comment]
This appears to be working based on @whikloj's two PRs.  I could translate a TIFF and openseadragon worked on both languages.

![image](https://user-images.githubusercontent.com/20773151/76974429-f55a8e80-690f-11ea-8456-94f3c9707edf.png)

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/openseadragon/commit/db23c1c66c0bf0234724e159adb76a58be8c0813 and https://github.com/Islandora-Devops/islandora-playbook/commit/f23aa2f294d78f8417bc8f0b233803eb2b1992e3
