### ISSUE TITLE
Update OpenSeadragon to 2.4.1

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1228]
Open Seadragon in default Islandora 8 is v=2.2.1
2.4.1 is available https://github.com/openseadragon/openseadragon/releases/tag/v2.4.1, and may fix some issues we've encountered in efficient IIIF Image API v2.1. tiling.

**Comment by kayakr** [comment]
We've updated to v2.4.1 locally and no issues detected.

**Comment by dannylamb** [comment]
@kayakr https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon/pull/8

Yours to merge :)

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon/commit/0bda879f38d9bbf00ede070677ef5e9be1f29db7
