### ISSUE TITLE
What is the difference between field_external_authority_link and field_authority_link

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1236]
In the taxonomy fields, there are field_external_authority_link and field_authority_link fields.  What is the difference between field_external_authority_link and field_authority_link?

**Comment by seth-shaw-unlv** [comment]
If I recall correctly: field_external_authority_link is the old version of field_authority_link. It should be removed since nothing uses it.

**Comment by Natkeeran** [comment]
@seth-shaw-unlv thank you for the info.

It is disabled Resource Type.  Lets keep this ticket to remove it.  Need to add the authority_link field to the Resource Type as well.

**Comment by seth-shaw-unlv** [comment]
References to field_external_authority_link should simply be replaced with field_authority_link and then we can add the field to the form and display settings to make it consistent with the other vocabularies provided by the module.

**Comment by bseeger** [comment]
This should be fixed via: Islandora/controlled_access_terms@56ba6f7 but I'll leave this open to let @seth-shaw-unlv confirm that.

**Comment by seth-shaw-unlv** [comment]
Heh. Yeah, we duplicated and then resolved the ticket.
