### ISSUE TITLE
EVA: OpenSeadragon Media EVAs - Original File enabled for binary view display mode

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1237]
"EVA: OpenSeadragon Media EVAs - Original File"  view is enabled for binary view display mode.  I suppose there are no side effects to this.  But, should it be?

**Comment by seth-shaw-unlv** [comment]
Islandora defaults currently has those EVAs hidden for the binary display mode: https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/config/install/core.entity_view_display.node.islandora_object.binary.yml#L330-L332
