### ISSUE TITLE
Media View Breaks with Islandora Breadcrumbs

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1238]
When I have Islandora Breadcrumbs enabled and go to view the media tab for a Repository Item node, I receive an error ```Error: Call to a member function hasField() on string in Drupal\islandora_breadcrumbs\IslandoraBreadcrumbBuilder->applies() (line 39 of ...web/modules/contrib/islandora/modules/islandora_breadcrumbs/src/IslandoraBreadcrumbBuilder.php)```

**Comment by seth-shaw-unlv** [comment]
I can look at it Monday.

**Comment by elizoller** [comment]
cool, thanks

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/5888d45b4153411941c07228cbba1de8bf270a32
