### ISSUE TITLE
Configure Fedora to use the SQL database instead of simple file persistence

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1244]
By default, we ship with 'file' persistence, which isn't really meant for production.  We should switch it over to use the SQL database being used (`claw_db` is the variable to check), either MySQL or Postgres, because it's better, faster, and more reliable.  You can configure it in our `repository.json` that we template out here: https://github.com/Islandora-Devops/ansible-role-fcrepo/blob/master/templates/repository.json

**Comment by whikloj** [comment]
How to do the configuring : https://wiki.duraspace.org/display/FEDORA5X/Configuring+JDBC+Object+Store
