### ISSUE TITLE
Solr Core Name

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1248]
I think it would be helpful to be able to configure (in the playbook) the default name of the Solr Core - to something not "CLAW". Is this a thing other people are interested in?

**Comment by dannylamb** [comment]
Definitely sounds like a good idea to me.  @elizoller++

**Comment by whikloj** [comment]
Just noting that due to the way the ansible-role-solr is setup, we could define more than one core. We might want to test with more than one core and see if our internal Solr handling works with multiple cores.

**Comment by seth-shaw-unlv** [comment]
Closed by https://github.com/Islandora-Devops/claw-playbook/commit/b1cffba0a8a49dadab0cc1684264716a1bbfdbb0. If we decide to add multiple cores later we can make a new ticket.
