### ISSUE TITLE
Islandora 8 Webinar Topics

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1249]
We've done a couple of webinars on Islandora 8:

* [June 2019](https://www.youtube.com/watch?v=ZaEQccS_9fY&t=17s)
* [August 2019](https://www.youtube.com/watch?v=XqYyvR8SW_Y&t=2508s)

We'd like to make this a monthly thing whenever we can manage it. This issue to to gather topic suggestions for future webinars.

Some suggestions we've received so far:

* Islandora 8 Cookbooks (demo and describe use cases solved by vanilla Drupal modules)
* Migrations and Bulk Loading

**Comment by mjordan** [comment]
👍 to both of those topics! Here's another that might be of interest:

* access control / embargoes (not just for IRs, but also for IP-restricted collections, etc.)

**Comment by kayakr** [comment]
I'd like to know more about registering & running custom microservices.

**Comment by dannylamb** [comment]
@kayakr That would be a good opportunity for collaboration with @ajstanley.  He just wired up the OCR service and made a FITS service.

**Comment by manez** [comment]
We're introducing a new kind of webinar, collaborating with early adopters to put a spotlight on their sites and the stuff they've built for 8. UPEI will kick this off with a session on [November 7](https://zoom.us/meeting/register/1d80057ac0ca83a0c5b9141539e44ee6).

Following some feedback from Islandoracon, we're also going to do another standard webinar, on the topic of migrating from 7 to 8. Danny gave a workshop on this that was very well received, and we had a number of requests for it to be made into a recording for those who weren't at the conference. It'll be on [November 21](https://zoom.us/meeting/register/ed6dbecad2730abe7c24e00bf0acd2b8)

**Comment by manez** [comment]
These are on hiatus.
