### ISSUE TITLE
carspace div with id leaderboard is left aligned

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1252]
Latest carspace theme (a12ff72f3bc9e0d98683df0aeb2fcdc2b39a3551) login div/region is left aligned.  It should be centered!.

The issue seem to be [here](https://github.com/Islandora-CLAW/carapace/blob/8.x-3.x/styles/css/components/menu.css#L74).  Removing `display: inherit;` seem to address the issue.

![carspace_theme_issue_1](https://user-images.githubusercontent.com/1827166/63531021-9e095280-c4d5-11e9-9541-5a3789774e2f.png)

**Comment by dannylamb** [comment]
Spinning up a new box now to confirm, but I don't think this is an issue any longer.

**Comment by dannylamb** [comment]
The current build is not exhibiting this behaviour now.  I'm tenatively closing this.  Feel free to re-open if this re-appears in different browsers/builds.
