### ISSUE TITLE
AuthorityLink Field produces incorrect JSON-LD

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1259]
The controlled_access_terms authority_link field type, when serialized into JSON-LD includes a language when it shouldn't:
```
"http://schema.org/sameAs": [
  {
    "@language": "en",
    "@id": "http://id.worldcat.org/fast/803047"
  }
]
```
We didn't catch this earlier because Fedora was forgiving of this mistake until version 5.1.

Not exactly sure how to fix this... It may be 
1. changing the FieldType so the serializer understands it better, 
2. creating an CommonDataConverter to use in the rdf mapping, or 
3. fixing it in the [existing jsonld alter](https://github.com/Islandora-CLAW/controlled_access_terms/blob/8.x-1.x/controlled_access_terms.module#L26).

**Comment by seth-shaw-unlv** [comment]
Turns out there was a fourth option: tell the jsonld module that authority_links are `xsd:anyURI`. PR available for testing.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/f2cae854ae140c50ac88a9e59d6325a3287fc80a
