### ISSUE TITLE
Add a 'weight' field to the Repository Item content type

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1261]
We'll be using the weight module to add page ordering for paged content.  We should go ahead and add that to the Repository Item content type provided by `islandora_defaults`.

1. Add the `weight` module to the `islandora_defaults` info file: 
1. Add a weight field to the Repository Item content type
1. Remove the weight field from display
1. Add the weight field to the form under the `System` section.
1. Add an RDF mapping for the weight field.
1. Re-export the `islandora_defaults` feature

**Comment by dannylamb** [comment]
Linking to https://github.com/Islandora-CLAW/CLAW/issues/932

**Comment by manez** [comment]
Playing with this a bit to test for the sprint. 

I'm wondering what we should set for a default range, and can we set a default to auto-increment by assigning the heaviest weight? In other words, make it so that each new page gets added to the end of the book by default, if using the GUI. I tried a range of 1000, and nothing choked, but I assume that anyone building books page-by-page from the front end would rather not select the exact page number every time.

**Comment by dannylamb** [comment]
@manez We use the `prepopulate` module to give the member of field a default based on the parent.  No reason why we couldn't use the same trick and query for the highest weight of the parent and bump that by one for a default value.

**Comment by seth-shaw-unlv** [comment]
I've used 1000 as a range with no issues.

**Comment by seth-shaw-unlv** [comment]
I don't know if this is just me, but the field_weight settings aren't sticking. I updated my test site to the current master and did the feature import, but it is still showing the active config settings as only the default `range: 20` with the min settings as only in the module config:
<img width="515" alt="Screen Shot 2019-09-10 at 12 22 51 PM" src="https://user-images.githubusercontent.com/29869988/64643666-b928fd00-d3c5-11e9-8822-5abbd2d30744.png">
I tried to update them using the field edit form (http://localhost:8000/admin/structure/types/manage/islandora_object/fields/node.islandora_object.field_weight) but those didn't stick either.

I have the latest weight version (8.x-3.1).

Hmmm... opening the field edit page throws a number of notices... something is going on with the module.

**Comment by seth-shaw-unlv** [comment]
Alright, I checked my other test site that was already using the weight module and it isn't throwing any errors on the edit form, but it also doesn't have all the same form fields (despite the modules both reporting the same version).

**Comment by seth-shaw-unlv** [comment]
Okay, I see what's going on here... the new field_weight is using the integer field type, **not** the weight field type. My dev box got confused because it already had a field_weight using the weight field type and so the settings didn't apply.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora_defaults/commit/09355d90eb3ba604faec8e0cd3ea30ec219b2e07
