### ISSUE TITLE
Generate a IIIF manifest from views results

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1263]
Create a plugin for generating an IIIF manifest from views results.  If a view queries for all children and orders it by our weight field, we can translate that into a IIIF manifest for compatibility with all types of viewers.

**Comment by mjordan** [comment]
Related to #1184 .

**Comment by dannylamb** [comment]
I believe this is called a `Style` plugin for views from looking at the `geolocation` module.

**Comment by dannylamb** [comment]
@joecorall Trying to assign this to you, but I think you need to be a member of our organization.  I'm sending you an invite.

**Comment by dannylamb** [comment]
Linking to https://github.com/Islandora-CLAW/CLAW/issues/932

**Comment by joecorall** [comment]
> @joecorall Trying to assign this to you, but I think you need to be a member of our organization. I'm sending you an invite.

Invitation accepted. Thanks!

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/d16e49748a9f849288d4d294229d2f61fc26c34a

**Comment by milossramek** [comment]
which web apps can manage and display scanned books using a jpg and xml file for each page, with the possibility to search in all books?
