### ISSUE TITLE
Adapt `openseadragon` to support IIIF manifests

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1264]
In order to render multiple pages using the openseadragon viewer, it needs to be adapted to accept a IIIF manifest.

Depends on https://github.com/Islandora-CLAW/CLAW/issues/1263

See [this documentation from Openseadragon](https://openseadragon.github.io/examples/tilesource-iiif/) for examples.  I think we'd just use the first 'inline' method, but that's pure speculation until we get into the thick of it.

**Comment by dannylamb** [comment]
Linking to https://github.com/Islandora-CLAW/CLAW/issues/932

**Comment by whikloj** [comment]
Currently I think we are using more of the _XMLHTTPRequest for IIIF info.json_ method, which would also open us up to using the multiple request method for paged content.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/openseadragon/commit/1a37e48206fc539c6b1494c320f000f45369ccc4
