### ISSUE TITLE
Add 'Paged Content' and 'Page' terms to the Models vocabulary

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1265]
Just example names, of course.  Could be 'Book' and 'Book Page'.  Just trying to be generic.  But we need these terms so we know to trigger OCR, etc...

**Comment by dannylamb** [comment]
Linking to https://github.com/Islandora-CLAW/CLAW/issues/932

**Comment by manez** [comment]
Do we want separate terms for different kinds of paged content? Book, Newspaper, Serial, etc? Or does that get divided up elsewhere?

**Comment by dannylamb** [comment]
If you need to handle newspapers and books differently you'll probably want those terms.  Seems like a good idea to me.

**Comment by dannylamb** [comment]
Any ideas for external URIs for these things?

Right now I'm using `http://example.org/page` until I can find something appropriate, lol.

**Comment by seth-shaw-unlv** [comment]
Are we good to close this, @manez and @dannylamb?

**Comment by manez** [comment]
👍

**Comment by seth-shaw-unlv** [comment]
Closed via https://github.com/Islandora-CLAW/islandora/commit/7bd9ca17b53fc4eee5695e3934d9faadd4149c61
