### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() in islandora_entity_extra_field_info()

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1266]
Warning: Invalid argument supplied for foreach() in islandora_entity_extra_field_info() (line 361 of modules/contrib/islandora/islandora.module).
islandora_entity_extra_field_info()

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/pull/732
