### ISSUE TITLE
Rename "Members" tab to "Children"

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1272]
Maybe that's a bit more obvious.

**Comment by dannylamb** [comment]
FYI, you can do this all through the views ui, edit the title of the view, and it should roll through to the tab name.  Please re-export the view yml and put it in `islandora_core_feature`.

**Comment by seth-shaw-unlv** [comment]
So, how drastic do we want to go in changing "Members" to "Children"? Are we:
1. just updating the UI,
1. also updating the views machine names,
1. or going all the way and changing field_member_of to something like field_parent?

**Comment by whikloj** [comment]
I'd opt for choice 1 and then just create some documentation so people can change "Children" to "Vampires" or whatever they might desire.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/38a13c179f9a115c44cd1da2f085873d312a770e
