### ISSUE TITLE
Enhancement - changes needed for remote files.

### ISSUE THREAD

**Issue by ajstanley** [Islandora/documentation#1273]
Here are Robib we're working on using the remote_files media type with Islandora objects.  The media type is unique in that it contains a reference to a binary file, but does not contain the file itself.

Islandora and its microservices (reasonably) expect a file to be attached to a media, and bad things happen when there isn't.  A few methods in the Islandora module need some changes, and a few of the microservices have to be reworked as well.  Gemini, Milliner and possibly others will have to be modified.

I'm putting this here in hopes of getting some feedback from others and to let the community know what we're doing.

**Comment by dannylamb** [comment]
Superseded by https://github.com/Islandora/documentation/issues/1374
