### ISSUE TITLE
Remove deprecated keyword "context" from Conditions

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1274]
This is related to #1241.

As @whikloj points out over at https://github.com/Islandora-CLAW/islandora/pull/164#pullrequestreview-286885125, annotations for Context Conditions that contain the `context` keyword, like this:

```php
* @Condition(
 *   id = "parent_node_has_term",
 *   label = @Translation("Parent node for media has term"),
 *   context = {
 *     "media" = @ContextDefinition("entity:media", required = TRUE , label = @Translation("media"))
 *   }
 * )
```
should be updated to use `context_definitions` [https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Condition!Annotation!Condition.php/property/Condition%3A%3Acontext/8.7.x](instead). So the changed keyword would look like this:

```php
* @Condition(
 *   id = "parent_node_has_term",
 *   label = @Translation("Parent node for media has term"),
 *   context_definitions= {
 *     "media" = @ContextDefinition("entity:media", required = TRUE , label = @Translation("media"))
 *   }
 * )
```

These Conditions include (files are all in islandora/src/Plugin/Condition/):

* ContentEntityType.php
* EntityBundle.php
* FileUsesFilesystem.php
* MediaHasTerm.php
* MediaUsesFilesystem.php
* NodeHadNamespace.php
* NodeHasParent.php
* NodeHasTerm.php
* NodeIsPublished.php
* ParentNodeHasTerm.php

This should be an easy PR for someone since the change is just one keyword per class file, and the test process could just be to make sure the Conditions are still showing up in the list of Conditions presented to the user.

**Comment by dannylamb** [comment]
PR up for this one ^^

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/e9bea0d697000d6f6f2a6a2d8d672ca0e49f134a
