### ISSUE TITLE
Record File's Original Name

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1276]
| Title (Goal)  | Record Born-digital File's Original Name |
--------------- |------------------------------------|
| Primary Actor | Repository Manager  |
| Scope         |    |
| Story         |  As a repository manager I want to record a file's original path as a PREMIS "originalName" property. |

**Comment by seth-shaw-unlv** [comment]
Some of our repository materials are born-digital items where we want to record the original full path of the file. E.g. `2016-2018 photographs/neo000093-013.TIF`. I propose we add a field to the various Media entities to record this.

**Comment by mjordan** [comment]
I agree with this proposal. However, we haven't discussed what approach to take to replace 7.x's [Islandora PREMIS](https://github.com/Islandora/islandora_premis), but as part of the Islandora Riprap module, I started work (didn't get far) on providing PREMIS fixity event data at https://github.com/mjordan/islandora_riprap/issues/5.

This is probably related to our meta issue on auditing (https://github.com/Islandora-CLAW/CLAW/issues/927).

**Comment by seth-shaw-unlv** [comment]
We also need to pick which version of PREMIS we are using. [Fedora 5 uses a PREMIS 1 namespace built-in](https://wiki.duraspace.org/display/FEDORA5x/Best+Practices+-+RDF+Namespaces) (`http://www.loc.gov/premis/rdf/v1#`); the module @mjordan cites [appears to serialize PREMIS 2 XML](https://gist.github.com/mjordan/8256978#file-premis_with_agents-xml-L2); but LOC appears to only recognize PREMIS 3 as an RDF ontology ([the page for 2.2](http://www.loc.gov/standards/premis/ontology/owl-version2.html) says they have an OWL ontology, but the linked page only refers to v 3).

**Comment by mjordan** [comment]
PREMIS 3 is the one to go with.

**Comment by seth-shaw-unlv** [comment]
So, for this usecase we can use `http://www.loc.gov/premis/rdf/v3/originalName` which we can shorten to `premis3:originalName`.

**Comment by rosiel** [comment]
Hey, sorry if I missed the discussion elsewhere, but why is the field storage in islandora instead of islandora defaults?

**Comment by seth-shaw-unlv** [comment]
I don't recall the original reason, but the pattern of placing the field storage configs for media fields in core feature and the field definitions in islandora_defaults was established by @dannylamb a while ago.

**Comment by seth-shaw-unlv** [comment]
You can see the existing field storage configs @ https://github.com/Islandora/islandora/tree/8.x-1.x/modules/islandora_core_feature/config/install. Now that I think about this, I seem to recall it has something to do with setting up views we can keep in core regardless of the field definition...

**Comment by dannylamb** [comment]
^^ That plus things like making a field multi-valued are locked down by the core feature and don't change unless we explicitly do so and then provide an update hook for.

**Comment by mjordan** [comment]
https://github.com/Islandora/islandora/pull/735 and https://github.com/Islandora/islandora_defaults/pull/13 merged.
