### ISSUE TITLE
"Reorder Children" tab showing up on non-Islandora objects

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1284]
The newly renamed "Reorder Children" tab should probably not be showing up on non-Islandora nodes:

![reorderchildren](https://user-images.githubusercontent.com/403918/65682074-0edce680-e00f-11e9-8d89-01bd6ab9ceb3.png)

@whikloj's fix in https://github.com/Islandora-CLAW/islandora/pull/160 should be applied to that tab too.

**Comment by dannylamb** [comment]
I actually shuffled that around and am about to push up a PR to put the
reorder children tab as an action link on the manage members view.

**Comment by mjordan** [comment]
:+1: closing.
