### ISSUE TITLE
`field_external_uri` is a magic string in a handful of places

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1290]
We've got a constant for it in `IslandoraUtils`: https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/IslandoraUtils.php#L31

So we shouldn't be hardcoding it in `JsonldTypeAlterReaction`, `NodeLinkHeaderSubscriber`, and `LinkHeaderSubscriber`.

Super easy newbie ticket if there are any takers.

**Comment by dflitner** [comment]
I am on this!

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/2a3b556a9ef7356a9980884e8d4ec8c5776e0bf0
