### ISSUE TITLE
claw-playbook: ERROR! 'debugger' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by t4k** [Islandora/documentation#1293]
Vagrant 2.2.3
Ansible 2.4.2.0

`vagrant up`

> ERROR! 'debugger' is not a valid attribute for a Play
> 
> The error appears to have been in '/…/claw/solr.yml': line 3, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> - hosts: solr
>   ^ here
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

I was able to get past the error by commenting out line 5 in `solr.yaml`:
```
  debugger: on_failed
```

**Comment by elizoller** [comment]
i had the same error on vagrant 2.2.4 and ansible 2.8.3

**Comment by DonRichards** [comment]
@t4k @elizoller Just looking at the [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html) for Ansible 2.2 and I see it does support the debugger parameter so it should work. I wonder if it's failing because of something else failing. If you remove the line does it finish building?

**Comment by t4k** [comment]
Yes, everything worked perfectly with that single line commented out.

**Comment by t4k** [comment]
> _New in version 2.5._
> 
> [The debugger keyword can be used on any block where you provide a name attribute, such as a play, role, block or task.](https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html)

Looks like it requires Ansible 2.5 _and_ a name attribute. There is no name attribute in this section of the file.

**Comment by t4k** [comment]
Maybe an Ansible `compatibility_mode` needs to be set in the Vagrantfile: https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

**Comment by DonRichards** [comment]
Interesting. I just created a PR for this.

**Comment by elizoller** [comment]
Sorry, this might be a dumb question but why would we want to force it to behave like a previous version of vagrant? Isn't that what compatibility mode does?

**Comment by DonRichards** [comment]
I believe so, that's how I read it.

**Comment by dannylamb** [comment]
Are we good to close this one?
