### ISSUE TITLE
Create Github issue templates to guide users between submitting "bug reports" v.s. "feature request"

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#1295]
I wanted to suggest that we set up/create Github issue templates.

They can be used to guide users between submitting "bug reports" v.s. "feature request"

Here are the instructions, but I need access to the I8 repo settings menu.
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

This is what the default templates look like, may not need a lot of customizing....

![image](https://user-images.githubusercontent.com/725449/66428643-79fdc400-e9e4-11e9-91aa-91c8b9281964.png)

Bug report:

![image](https://user-images.githubusercontent.com/725449/66428772-aa456280-e9e4-11e9-945f-dc12c004b15d.png)

Feature request:

![image](https://user-images.githubusercontent.com/725449/66428806-bcbf9c00-e9e4-11e9-909e-bc1fd9daf64b.png)

**Comment by manez** [comment]
YES. This is a great idea. Once I'm back in the real world next week, I'll make this a priority. Thank you @ysuarez 👍 👍 👍

**Comment by ysuarez** [comment]
@manez because of de-CLAWing project and the separation of the documentation repo, this type of issue UI customization may be even more useful. I am sure you thought of this already.

For example, there is a need to make it clear that one repo should get documentation issues and not code issues, though of course we will get a mix of issues in the future.

FYI: @dannylamb

**Comment by ysuarez** [comment]
I have created this Google Doc with some ideas on what content we could want to add to the templates 

https://docs.google.com/document/d/1dF0yL9_lRsaX14Mb2nsMzZXUIbSPMmFITGH8KP_Zcxk/edit

Please reach out to me if you want rights to be able to leave comments in the doc.

@eldonquijote @kstapelfeldt @rosiel

**Comment by ysuarez** [comment]
This issue can now be closed now that templates have been submitted based on my Google doc. in this commit https://github.com/Islandora/documentation/commit/fa2bea63ab3983b2480834295c83c9e80aa51cef
