### ISSUE TITLE
Midia tab behavior

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#1307]
Align the media tab behavior to Islandora 7's datastream tab. 
Limit the content found in the tab to just the children and not the grandchildren. 

<img width="1069" alt="Screen Shot 2019-10-11 at 3 49 28 PM" src="https://user-images.githubusercontent.com/2738244/66690811-5f775500-ec47-11e9-9bfd-c8b2cd61ae72.png">

**Comment by whikloj** [comment]
That is the Drupal "Files" tab. It displays all the files on the site and is core Drupal. That "Media" tav will also display all the media on the site. 

You'll want the "Media" tab of a node. Which is at `http://localhost:8000/node/X/media`.
<img width="645" alt="Screen Shot 2019-10-15 at 7 56 48 AM" src="https://user-images.githubusercontent.com/2857697/66833536-9daf9580-ef21-11e9-9f48-c2008c631073.png">

Which is limited to the current resource's media.
<img width="848" alt="Screen Shot 2019-10-15 at 7 47 46 AM" src="https://user-images.githubusercontent.com/2857697/66833575-b029cf00-ef21-11e9-9533-0791eb04a10e.png">

**Comment by seth-shaw-unlv** [comment]
@DonRichards, can we close this ticket?

**Comment by DonRichards** [comment]
Yep, I'll go ahead and do it
