### ISSUE TITLE
Documentation: Bad link to docs in repo homepage

### ISSUE THREAD

**Issue by mradamcox** [Islandora/documentation#1319]
The repo front page (README.md) has a bad link to the Islandora 8 documentation (it links to https://islandora-claw.github.io/CLAW/ but the correct url seems to be https://islandora.github.io/documentation/).

**Comment by manez** [comment]
@whikloj is auditing this repo as part of our efforts #1267  to clean up those broken links and CLAW-based urls. Tagging him so this gets on the radar 😄

**Comment by mradamcox** [comment]
Aha, I see, this is a trees and forest thing :)

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/documentation/commit/6941603f8aa203f363e548bf85f5a09172dd9d8c

Thanks again for reporting @mradamcox
