### ISSUE TITLE
`--userid` option for migrations doesn't work on rollback

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1322]
The `--userid` option that's needed so we can pass around JWT tokens isn't available for the other migration operations, most notably rollbacks.  If the user id isn't known, then files can't be deleted from Fedora, resulting in this weird message:

`[error] Failed to unlink file fedora://some/file/path`

**Comment by seth-shaw-unlv** [comment]
Makes sense; although rollback is the only other one that really needs it because it modifies entities while the others (status and reset) are only doing migration state.

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/31faef884130c871582e77e1fe21a87b3e7cadf7
