### ISSUE TITLE
Filemime constant mapping

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1326]
I am wondering if the filemime should be mapped to constants/mime instead of constants/mimetype in migrate_plus.migration.file.yml
`  filemime: constants/mimetype`
because I only see `mime: image/jpeg` in the constants section of that file, not `mimetype: image/jpeg`

**Comment by seth-shaw-unlv** [comment]
@elizoller, you are correct.

**Comment by elizoller** [comment]
can i put in a PR for this?

**Comment by elizoller** [comment]
fixed with https://github.com/Islandora/migrate_islandora_csv/pull/34
