### ISSUE TITLE
Islandora.tomcat8 Ansible role has deprecated 'sudo:' directives

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1329]
Updated the Tomcat8 role to remove 'sudo' directives that cause Ansible 2.9 to fail.

PR: https://github.com/Islandora-Devops/ansible-role-tomcat8/pull/12

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/ansible-role-tomcat8/commit/712540525e4f31a60915e6305c4c602136a717c5
