### ISSUE TITLE
Playbook is failing

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1335]
Just replicated this twice, building the playbook in master branch at234642d94ad8c3c5601e6c643d403793937c6835 :

`
mark@mark-XPS-13-9343:~/Documents/hacking/vagrants/islandora-playbook$ screen -r                                                                                 pts-0.mark-XPS-13-9343
landora 1.0.0 -> no matching package found.\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n - It's a private package and you forgot to add a custom repository to find it\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.\n\nInstallation failed, reverting ./composer.json to its original content.\n", "stdout_lines": ["./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - Installation request for islandora/islandora_defaults 1.0.0 -> satisfiable by islandora/islandora_defaults[1.0.0].", "    - islandora/islandora_defaults 1.0.0 requires islandora/islandora 1.0.0 -> no matching package found.", "", "Potential causes:", " - A typo in the package name", " - The package is not available in a stable-enough version according to your minimum-stability setting", "   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.", " - It's a private package and you forgot to add a custom repository to find it", "", "Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "", "Installation failed, reverting ./composer.json to its original content."]}
`

Looks like a spelling mistate ("landora 1.0.0")?

**Comment by dannylamb** [comment]
'landora is the new 'murican? :rofl:

**Comment by mjordan** [comment]
Let me try to see if this is still the case. Will report back here.

**Comment by jhujasonw** [comment]
Just hit something that looks almost exactly the same but has no spelling error...

`TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] **********************************************
changed: [default] => (item=zaporylie/composer-drupal-optimizations:^1.0)
ok: [default] => (item=drupal/console:~1.0)
changed: [default] => (item=drupal/devel:^2.0)
changed: [default] => (item=drupal/rdfui:^1.0-beta1)
changed: [default] => (item=drupal/restui:^1.16)
changed: [default] => (item=drupal/search_api_solr:^2.0)
changed: [default] => (item=drupal/facets:^1.3)
changed: [default] => (item=drupal/content_browser:^1.0@alpha)
changed: [default] => (item=drupal/matomo:^1.7)
changed: [default] => (item=drupal/pdf:1.x-dev)
changed: [default] => (item=islandora/carapace:1.0.0)
failed: [default] (item=islandora/islandora_defaults:1.0.0) => {"ansible_loop_var": "item", "changed": false, "item": "islandora/islandora_defaults:1.0.0", "msg": "./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages. Problem 1 - Installation request for islandora/islandora_defaults 1.0.0 -> satisfiable by islandora/islandora_defaults[1.0.0]. - islandora/islandora_defaults 1.0.0 requires islandora/islandora 1.0.0 -> no matching package found. Potential causes: - A typo in the package name - The package is not available in a stable-enough version according to your minimum-stability setting see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details. - It's a private package and you forgot to add a custom repository to find it Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems. Installation failed, reverting ./composer.json to its original content.", "stdout": "./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for islandora/islandora_defaults 1.0.0 -> satisfiable by islandora/islandora_defaults[1.0.0].\n    - islandora/islandora_defaults 1.0.0 requires islandora/islandora 1.0.0 -> no matching package found.\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n - It's a private package and you forgot to add a custom repository to find it\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.\n\nInstallation failed, reverting ./composer.json to its original content.\n", "stdout_lines": ["./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - Installation request for islandora/islandora_defaults 1.0.0 -> satisfiable by islandora/islandora_defaults[1.0.0].", "    - islandora/islandora_defaults 1.0.0 requires islandora/islandora 1.0.0 -> no matching package found.", "", "Potential causes:", " - A typo in the package name", " - The package is not available in a stable-enough version according to your minimum-stability setting", "   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.", " - It's a private package and you forgot to add a custom repository to find it", "", "Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "", "Installation failed, reverting ./composer.json to its original content."]}`

**Comment by jhujasonw** [comment]
FWIW, https://packagist.org/packages/islandora/islandora does not contain the 1.0.0 version of "islandora/islandora"  which appears to possibly be why this is failing.... atleast, right now.

@DiegoPino and @jonathangreen  are the maintainers listed on the package page for islandora/islandora and @seth-shaw-unlv  is the maintainer for islandora/islandora_defaults

**Comment by dannylamb** [comment]
it's all starting to come together.  we migrated the repo over from another org, and the main islandora module got moved over as a branch.  that tag didn't make it over.

**Comment by dannylamb** [comment]
aha, because our tags are on master and i didn't move the master branch over

**Comment by dannylamb** [comment]
i pushed the master branch and the 1.0.0 tag over from Islandora-CLAW/islandora to Islandora/islandora.  it should work now :tm:

**Comment by jhujasonw** [comment]
Thanks for the super quick reply @dannylamb.  I am re-running my playbook now.  I'll post back if it is successful or not.

**Comment by jhujasonw** [comment]
The install go past the composer issue.  Now I'm at another issue, but I'll dig into that and won't pollute this ticket with it.  Thanks again for the quick reply.

**Comment by dannylamb** [comment]
Awesome.  Thanks for testing @jhujasonw.  Feel free to open another issue if you can't get past your next hurdle.
