### ISSUE TITLE
Add OR logic to NodeHasTerm and kin 

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1337]
Right now it allows multiple and assumes AND, you want all of the terms or fail.  You should be able to select AND or OR and have it evaluate appropriately.  For example, maybe I want to show openseadragon viewer for all nodes who have the Image _OR_ Paged Content term using context.

**Comment by dannylamb** [comment]
^^ PR up for that

**Comment by mjordan** [comment]
I'm probably missing something, but....

> Right now it allows multiple 

In the UI, how do you add multiples?

![Capture](https://user-images.githubusercontent.com/403918/68986902-00be7180-07d9-11ea-8a75-e051bf9f7b9b.PNG)


Clicking on "Add condition" shows a list that doesn't include "Node has term". Also, the autocomplete doesn't allow multiple entries.

**Comment by dannylamb** [comment]
After the first one autocompletes, typing `,` _should_ trigger it to start auto completing another.  This PR came from me untangling a bunch of tweaks I made working on quicker upload forms, and I may not have extracted it out correctly.  I'll circle back to this soon.

**Comment by mjordan** [comment]
Awesome, thanks, I'll give this a test this evening.

**Comment by mjordan** [comment]
https://github.com/Islandora/islandora/pull/745 merged. Nice work @dannylamb !
