### ISSUE TITLE
Should TIFFs be converted to JP2s for display?

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1339]
I'm probably missing something (it's happened, you know), but I was expecting a TIFF media I created to be converted to a JP2 for rendering in OpenSeadragon. The only derivatives created for the TIFF are   service file JPEG and thumbnail JPEG. I also don't see any actions to generate a JP2.

I'm running a very recent (last few days) build of the playbook.

**Comment by mjordan** [comment]
Poking through the issue queue, I suspect this one is related to #1294.

**Comment by dannylamb** [comment]
Probably due to the fact that we're having issues with generating JP2s on Ubuntu.  CENTOS is fine.  https://github.com/Islandora/documentation/issues/1285

**Comment by mjordan** [comment]
Ah, thanks for confirming I *was* missing something. Closing.
