### ISSUE TITLE
Update islandora_oaipmh for rest_oai_pmh alpha-10

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1360]
In the [alpha-10 release of rest_oai_pmh](https://www.drupal.org/project/rest_oai_pmh/releases/8.x-1.0-alpha10) the metadata schema selection was changed to using Plugins instead of theme hooks (don't worry, you can still create custom metadata profiles using twig templating). However, it also means we need to update our default configuration.

PR incoming.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora_defaults/commit/05846783242f042236ecc17024d0bf46ee7788a1
