### ISSUE TITLE
Spots where dependency injection is impossible because type hinting expects implementations, not interfaces

### ISSUE THREAD

**Issue by qadan** [Islandora/documentation#1361]
This originally cropped up when enabling the `webprofiler` submodule of the [Devel](https://www.drupal.org/project/devel) module. `webprofiler` implements a whole bunch of interfaces to inject, including an `EntityManagerWrapper` which is put in place of the standard `EntityTypeManager`. It doesn't extend the `EntityTypeManager` however, it only implements `EntityTypeManagerInterface`.

There's a bunch of examples of where this would trip things up in Islandora; I'll just pull the first one:

[NodeLinkHeaderSubscriber](https://github.com/Islandora/islandora/blob/31faef884130c871582e77e1fe21a87b3e7cadf7/islandora.services.yml#L24) takes an `@entity_type.manager` as its first argument, and in the actual implementation inherited from [LinkHeaderSubscriber](https://github.com/Islandora/islandora/blob/31faef884130c871582e77e1fe21a87b3e7cadf7/src/EventSubscriber/LinkHeaderSubscriber.php#L93), it's type hinted to use `Drupal\Core\Entity\EntityTypeManager`.

So, `webprofiler` tries to inject its `EntityManagerWrapper` as the `@entity_type.manager`, but the type hint is looking for an actual `EntityTypeManager` or subclass thereof, which `EntityManagerWrapper` is not one of, so it goes boom.

The [Drupal docs on dependency injection](https://api.drupal.org/api/drupal/core%21core.api.php/group/container/8.8.x) are disappointingly unclear on what they want you to do here ... the `services.yaml` definition says to use "the default class that provides the service, or if the service uses a factory class, the interface for the service" ... but they often document the default class instead of the interface, like with `@entity_type.manager`.

Anyway, that's all just an aside I guess. In practice modules use the interface providing a service to type hint ([content_sync](https://git.drupalcode.org/project/content_sync/blob/0df94c454ad7905e5d55fd1159732de9dbf7dcee/src/ContentSyncManager.php#L39) and [search_api_solr](https://git.drupalcode.org/project/search_api_solr/blob/3672ccaf839c7f6f6c5a3f6603c17c62a6c28e9d/src/SolrFieldManager.php#L52) both have examples of this specific service being implemented using the interface instead of the class), and we should follow suit to properly facilitate dependency injection. Even in `Drupal\islandora\EventSubscriber\LinkHeaderSubscriber`, the `@entity_type.manager` and `@entity_field.manager` don't type hint the interface, but then other stuff like `@access_manager` and `@current_user` do, so consistency is also a factor here.

Logging this issue specifically to look at auditing the codebase for spots where type hinting is going to reduce or prevent our ability to dependency inject, as this reduces our ability to extend Islandora 8 via contrib modules. `EntityTypeManager` is one example, but suspect others may exist. Logging the issue also to perhaps make a hard rule for development to use interface type hinting.

**Comment by dannylamb** [comment]
I did a quick audit and it looks like we are injecting the `EntityTypeManager`, `EntityFieldManager`, and `FileSystem` services without using their interfaces.  Some vim -> grep -> %s action should take care of this...

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora/islandora/commit/0d9019bb6dc6f9bacfc6047cf0e8bc0db7511cdb
