### ISSUE TITLE
Filenames with commas break entity display

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1366]
## Steps to Reproduce

1. Navigate to a node of an Islandora object
1. Go to the Media tab and click Add Media
1. Find a file to upload, but before uploading, put a comma in the file name somewhere. E.g. "Test,file.txt"
1. Save the new media
1. Go back to the media list page and click on the media to display the entity.

## Expected Behaviour

You see the entity

## Actual Behaviour

Page shows "The website encountered an unexpected error. Please try again later."

Apache Error Log shows: 

```
[Thu Nov 21 05:56:27.085262 2019] [php7:notice] [pid 338] [client 10.0.2.2:50942] Uncaught PHP Exception InvalidArgumentException: "The URI '2019-Twillingate.wav/fcr:metadata' is invalid. You must use a valid URI scheme." at /var/www/html/drupal/web/core/lib/Drupal/Core/Url.php line 281, referer: http://localhost:8000/node/1/media
```

It looks like the problem is in the GeminiLookup::lookup() function here:

```
      $links = Psr7\parse_header($head->getHeader("Link"));
      foreach ($links as $link) {
        if ($link['rel'] == 'describedby') {
          return trim($link[0], '<>');
        }
      }
```

Where the PSR7 url function is breaking apart the URL where the comma is, and the return statement is only returning second part of the URL after the comma, where the first part contains the rest of the Gemini URL.

**Comment by seth-shaw-unlv** [comment]
Tagging related issue #1309.

**Comment by alxp** [comment]
The Psr7::parse_header() function is splitting the string over the comma characters. It seems like filenames should be uURL-encoded when they are sent to and from Gemini - if not having it fully encoded going in to Fedora.

**Comment by dflitner** [comment]
This is a core issue. There are a couple of workarounds but they will require a bunch of testing.
See: https://www.drupal.org/project/imagemagick/issues/1502924#comment-13222054

**Comment by dannylamb** [comment]
This module takes care of it by sanitizing filenames as they come in: https://www.drupal.org/project/transliterate_filenames

I've tested it and it works for this and #1309

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/islandora-playbook/commit/d4c416727c86c2439ae41d3fcb30bf9184ca1d7f
