### ISSUE TITLE
Comment module is a dependency of a bunch of Islandora modules

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1369]
Looks like the core Comment module is a dependency for the following modules:

![comments](https://user-images.githubusercontent.com/403918/69682492-6676ed00-1066-11ea-85a7-f062b4f214b6.PNG)

Which makes it difficult to uninstall it. Looking at the .info.yml files for the modules listed above, it's there for Islandora Defaults and ... Solr Search Defaults (not one of ours).

So I guess the only way to not have comments on a site is to not configure any permissions for it? Here's the policy of the Solr Search Defaults maintainers: https://www.drupal.org/project/search_api_solr/issues/2938102.

**Comment by dannylamb** [comment]
I think if we want to avoid that then we're saddled with maintaining our own solr config and not using anything from `search_api_solr_default` (which may not be a bad thing?).

**Comment by mjordan** [comment]
Since defaults provides standard fields on repository objects, it might be nice to provide a corresponding set of search configs. As it is, admins still need to configure all the "islandora" fields at `admin/config/search/search-api/index/default_solr_index/fields`.

**Comment by dannylamb** [comment]
Totally.  And facets.  We should provide reasonable defaults for those, too.

**Comment by mjordan** [comment]
Now that we're not relying on `search_api_solr_default` can we remove the dependency on the comment module?

**Comment by mjordan** [comment]
Bumping this... now that we have islandora_search, does the comment module still need to be a dependency of islandora_defaults, islandora_oaipmh, and islandora_search? comment is a dependency of search_api_solr_defaults, which in turn is a dependency of islandora_search. If we can get rid of that last dependency, we can get rid of the comment module (I think).

**Comment by seth-shaw-unlv** [comment]
So, a quick grep shows that the only reference to search_api_solr_defaults is in the islandora_search info file. Removing that reference should allow us to remove comment from the islandora_defaults info file. 

!["It is a strange fate that we should suffer so much fear and doubt over so small a thing." -Boromir](https://user-images.githubusercontent.com/29869988/92018777-706f0000-ed0a-11ea-826b-2ae3e5154985.gif)

**Comment by seth-shaw-unlv** [comment]
I have [a branch for this](https://github.com/seth-shaw-unlv/islandora_defaults/tree/issue-1369), but I need to build a fresh box from scratch to test it before I issue the PR.

**Comment by seth-shaw-unlv** [comment]
Actually, it will be a lot easier to test this as a branch on islandora_defaults itself...

**Comment by seth-shaw-unlv** [comment]
Okay, I've tested my branch and it does remove the dependency on Comment. HOWEVER, it will still appear on a standard Drupal install because it is used by the Article content type. To truly remove Comment you have to delete the comment field from the Article content type and then uninstall the module.

PR incoming.

**Comment by mjordan** [comment]
All resolved, thanks very much @seth-shaw-unlv!
