### ISSUE TITLE
Need to set proper cache tags when altering jsonld

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1379]
Right now tests are failing because of this.  If you go update context config that alters jsonld, you have to clear the cache in order to get it to take effect.  Our test, which used to pass, is doing just that.  Make a context, check the jsonld, then update it and check the jsonld again for results.

You can put `drupal_cache_rebuild()` between every step of the test, but ideally we'd have the cache invalidated on jsonld representations every time the context that alters them gets updated.

**Comment by dannylamb** [comment]
So, fun fact, Drupal puts `CacheableMetadata` into the `$context` array that gets passed around in hooks.  You can get at it as `$context['cacheability']` and then add cache tags to it, etc...

In the alter that executes the context reactions for jsonld, I get all contexts (as in the `context` module context) that had reactions that fired and add their cache tags to the CacheableMetadata in the `$context` array.

Is that enough contexts for ya?

Anyway, now if you go and change `schema:sameAs` to `owl:sameAs` for the self-reference alter, you don't have to clear the cache to see your changes take effect in your jsonld.  This should fix tests (running them now...)

**Comment by dannylamb** [comment]
Ah noooo... Looks like that doesn't cover the case of adding content, then adding the reaction, then viewing the content to see if the alter happened.  Because the content pre-existed the context and reaction, you still gotta clear your cache.

**Comment by dannylamb** [comment]
Well... little bit of column A and a little bit of column B I guess.  I had to update the tests to add manual cache clears, but also updated the hook to add cache tags where appropriate.  Now Drupal automatically invalidates JSONLD REST responses when contexts that have those alters get saved.

Unfortunately, if content pre-dates the context, it will not get the right cache tags because it doesn't get altered.  So you still have to clear the cache in that scenario.  Not really sure how to do that without force invalidating everything everytime a context gets saved (which we could do :bomb: but feels ham-fisted).  So I'm leaving it there before going down the rabbit hole any further.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora/islandora/commit/b553f2cd2b1869639819b1d2298f80a42fbd1432
