### ISSUE TITLE
Updating Drupal Core to 8.8.1

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1387]
I experimented with updating Drupal Core to 8.8.0 using composer.
I tested some basic things like pushing content to Fedora and it seems to be ok. Not sure what kind of testing needs to run to evaluate it more thoroughly.
PR here: https://github.com/Islandora/drupal-project/pull/34

**Comment by whikloj** [comment]
Due to multiple critical vulnerabilities in 8.8.0, Drupal is now recommending 8.8.1. So I'd vote to relax on this push for now, but if not then jump straight to 8.8.1
https://www.drupal.org/sa-core-2019-012

**Comment by elizoller** [comment]
Updated PR to 8.8.1

**Comment by dannylamb** [comment]
Testing 8.8.1 now.  It may potentially fix a bug with stuff that I'm working on for https://github.com/Islandora/islandora/pull/745.

**Comment by dannylamb** [comment]
Well, doesn't fix my issue with https://github.com/Islandora/islandora/pull/745... but doesn't appear to break anything either.  I just ran a quick sanity test and everything worked out.  Derivatives, indexing, etc... all seem ok.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/islandora-playbook/commit/cc97929d58c2669fed58e5ab463cae599d9e9036
