### ISSUE TITLE
We aren't testing all of `islandora`'s submodules

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1390]
We're only running tests for breadcrumbs.  We need to run them for all the derivative submodules as well.  I bumped into this making a test for `islandora_video` and turns out they're failing (at least for that submodule), so there'll have to be some cleanup on those tests too once we turn them on.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora/islandora/commit/20477e814af6dcb6da78f3cd986b0132f1735ad2
