### ISSUE TITLE
Configuration page WSOD when Tomcat is down

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1396]
If Tomcat is down when visiting the general configuration page '/admin/config' will WSOD and report to the log `GuzzleHttp\Exception\ConnectException: cURL error 7: Failed connect to 127.0.0.1:8080; Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 185 of /var/www/html/drupal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).`.

To be honest, I don't know why the general configuration page crashes when Tomcat is down, but it does. 

To reproduce:
1. Spin up a box
1. Visit `http://localhost:8000/admin/config' which should load fine.
1. `vagrant ssh`
1. `sudo systemctl stop tomcat8`
1. Visit `http://localhost:8000/admin/config' which will WSOD.
1. Visit the recent log messages page (`http://localhost:8000/admin/reports/dblog`) and see the error listed.

**Comment by Natkeeran** [comment]
Yes, I've noted this issue as well.

I think this has something to do with Islandora config's trying to look up fedora, but as Seth noted, not sure what on that screen.

**Comment by wgilling** [comment]
I thought that this was traced to the fly system

**Comment by seth-shaw-unlv** [comment]
@wgilling, that is what @dannylamb was postulating last meeting, but we haven't followed up on it yet.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora/islandora/commit/2a1024c19a4b495c64fb88d4260e8d7ebea1f9b5
