### ISSUE TITLE
Controlled Access Terms requires unsupported Auto Entity Label version

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1399]
Currently requires requires drupal/auto_entitylabel ^2.1@beta but this is no longer supported and 8.x-3.0-beta2 (2019-Oct-11) is recommended instead.

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/controlled_access_terms/commit/51ed83a581c5b2677856ed1babbdcce29b197bdb

**Comment by kayakr** [comment]
@seth-shaw-unlv fwiw, I've applied this as a patch on on our Staging and UAT instances and all is ok.
