### ISSUE TITLE
Set Islandora roles to 'master' in requirements.yml for dev branch

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1404]
The dev branch of islandora-playbook needs to be able to keep up with changing roles without us having to slice new releases of the roles every time we make a change.  Case in point, islandora-playbook fails as of now unless we set the blazegraph and alpaca roles to pull from master.

**Comment by seth-shaw-unlv** [comment]
Ergo, https://github.com/Islandora-Devops/islandora-playbook/pull/150

**Comment by dannylamb** [comment]
I was going to toss master onto all of 'em, but those are enough to keep us going.

**Comment by seth-shaw-unlv** [comment]
Wouldn't take me more than a minute to do the rest.

**Comment by seth-shaw-unlv** [comment]
Whelp, never mind! 🤷‍♂️

**Comment by dannylamb** [comment]
alas... there is no ninja emoji in github

**Comment by dannylamb** [comment]
if you toss up a PR for the rest I can merge.  I've already tested it with all islandora roles at master and everything is fine.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/islandora-playbook/commit/db20b40f8f5ca4ce508e3a2208c265e99052a305
