### ISSUE TITLE
`islandora_fits` is out of sync with the rest of the codebase

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1405]
`islandora_fits` currently resides in roblib's github organization, and is being developed for features that aren't mainline yet.  We need to pin it down so it doesn't keep drifting on us. Right now, on a fresh install, I'm getting this: 

```
[Tue Jan 21 14:27:43.053575 2020] [php7:notice] [pid 814] [client 10.0.2.2:48366] Uncaught PHP Exception Drupal\\Core\\Entity\\EntityStorageException: "Field field_fits_file is unknown." at /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 847, referer: http://localhost:8000/media/add/image?edit%5Bfield_media_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=2
```

This has indexing for multiple files for media, but none of that has been contributed to us yet.  If we can't reasonably pin it down, then we need to maintain a fork or have it LSAP'd to us.

**Comment by dannylamb** [comment]
Reverting to `b8a126ebaa896402c6ba341047363a05857d0a60` worked out alright.

**Comment by dannylamb** [comment]
@alxp @ajstanley @rosiel ^^ Any chance we can get a version sliced at that commit?

**Comment by ajstanley** [comment]
Absolutely - I'll get it first thing in the morning.

**Comment by ajstanley** [comment]
Branch 8.x-1.x is good to go - anyone who wants the new model can go to newFileModel
(Sorry about that, I'd kept the changes in a new branch but merged prematurely)
Also copied it back to master, so old playbooks will still run.

**Comment by dannylamb** [comment]
Neither 8.x-1.x or master are working :cry:  You're referencing some fields we don't have.  Can you tag `b8a126ebaa896402c6ba341047363a05857d0a60` while we sort out how to move forward with all the content modeling changes?

**Comment by dannylamb** [comment]
Turns out I can just reference it like so

`islandora-rdm/islandora_fits:dev-master#b8a126ebaa896402c6ba341047363a05857d0a60`

for the time being.  A tag would be nicer but that'll keep us going until we manage to pull everything into the islandora org.

**Comment by dannylamb** [comment]
`dev-master` works fine for now.  Closing!
