### ISSUE TITLE
VagrantFile makes 4GB machine by default, README.md states it is 3GB

### ISSUE THREAD

**Issue by wgilling** [Islandora/documentation#1407]
In my attempts to run the islandora_playbook using an older MacBook laptop that has 4 GB 1600 MHz DDR3, the process never completed due to insufficient memory or timed-out processes.

Either the README.md should reflect that a VM is created with the default size of 4GB (and thereby, the user should have a machine that is capable of running that) or the VagrantFile should set up the default value to truly reflect what the README says the default value is:

` $memory = ENV.fetch("ISLANDORA_VAGRANT_MEMORY", "4096")`

That VagrantFile changed June 18, 2018 from 3GB to 4GB (among other changes) : https://github.com/Islandora-Devops/islandora-playbook/commit/364faee32c75d88e61cf3e006c3c2e9c6b3fcde8#diff-23b6f443c01ea2efcb4f36eedfea9089

I would be happy to make a pull request to achieve either of the above suggestions.

PS:  don't feel bad for me -- it was a temporary laptop so I am not going to have to suffer very long with the limited RAM.

**Comment by dannylamb** [comment]
@wgilling Pretty sure I did that.  I was having boxes fail to come up b/c of OOM errors when composer runs.  But that was June 2018 and we have done [this](https://github.com/Islandora-Devops/islandora-playbook/commit/94091f0a898fea06044e0ca6826faabe1f30de9c) since, which optimizes composer.  Maybe it can make through provisioning on just 3GB?  If you can confirm we can dial it back down in the vagrantfile.

**Comment by wgilling** [comment]
During the Islandora 8 call, some suggestions were:
 - simply update the README to reflect the memory allocation in the VagrantFile
 - @DonRichards suggested that it is possible to configure the VagrantFile to allow for a percentage of host machine's memory https://drupal.psu.edu/blog/post/dynamic-memory-allocation-vagrant-virtual-machines-windows-hosts 
 - Gavin suggested that it would be helpful to indicate a range of memory values that a developer machine may have -- I concur that a developer would understand how a change to the VM memory allocation may impact things.

The consensus seems to be that the VagrantFile be set to 4GB and the README explains that the allocation can be increased to lead to better performance.

@dannylamb suggested that a dynamic memory option should be made as a separate issue.
