### ISSUE TITLE
Inventory cleanup

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1409]
I'm going through testing all of @dbernstein's PRs for our roles, and I'm noticing lots of small things doing all of this on droplets instead of locally through vagrant.  I'm making this ticket as a bucket for cleanup PRs to our roles/inventory.

My goal here is to shrink the number of variables you have to edit when provisioning a remote server.  There's big chunks I can eliminate by pushing things into variables.

**Comment by Natkeeran** [comment]
@dannylamb 

Perhaps, related issue: https://github.com/Islandora/documentation/issues/1434

**Comment by seth-shaw-unlv** [comment]
Resolved by https://github.com/Islandora-Devops/ansible-role-alpaca/commit/4896d8507b386ac7c394032ea46416a61d287309
