### ISSUE TITLE
Enhancement: FITS should make PUID a field

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1411]
The new FITS integration is awesome - excellent work @ajstanley ! I'd like to see it create a field for PUID, which is the PRONOM format ID generated by Droid. The XML snippet in the FITS output is:

```xml
<externalIdentifier toolname="Droid" toolversion="6.4" type="puid">fmt/12</externalIdentifier>
```
Anyone have any objections to my opening a PR to make this into a field like the rest of the values from the FITS output?

**Comment by mjordan** [comment]
Went ahead and added it anyway! PR is at https://github.com/roblib/islandora_fits/pull/1.

**Comment by kstapelfeldt** [comment]
Closed with thanks. Please feel free to re-open or issue a new ticket if there needs to be any documentation made, etc.
