### ISSUE TITLE
Need to fix OAI-PMH

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1422]
I neglected to check OAI-PMH before merging the PRs for https://github.com/Islandora/documentation/issues/1412... 🤦‍♂️.

So, two choices that I can see:

1. Revert the dcterms merge on islandora_deraults
1. I quickly implement a metadata plugin to fix this (it is quick to do).
1. Ask @joecorall to quickly fix the default metadata plugin (or merge a PR from me) on rest_oai_pmh itself and issue a new alpha version tag.

Preferences?

**Comment by joecorall** [comment]
I'd be happy to update the `rest_oai_pmh` module if that's the best resolution.

**Comment by seth-shaw-unlv** [comment]
I think we can get away with just editing https://git.drupalcode.org/project/rest_oai_pmh/blob/8.x-1.x/src/Plugin/OaiMetadataMap/DublinCoreRdf.php#L147-179. I'm about to test.

**Comment by seth-shaw-unlv** [comment]
That didn't work. We'll need to poke at this some more.

**Comment by seth-shaw-unlv** [comment]
This patch will do it, @joecorall: [oai_dc.patch.txt](https://github.com/Islandora/documentation/files/4150674/oai_dc.patch.txt)

**Comment by joecorall** [comment]
I'll take a look at this early EST time and get it merged in // released✨🌴✨

**Comment by joecorall** [comment]
Hey @seth-shaw-unlv ,

To provide support for anyone using the namespace

- dc
- dcterms
- dc11

In RDF, I thought maybe it'd be easier to transform the namespace instead of editing the mapping array. Does this patch work for you?
[oai_dc.tranform_namesapces.txt](https://github.com/Islandora/documentation/files/4153488/oai_dc.tranform_namesapces.txt)

**Comment by seth-shaw-unlv** [comment]
@joecorall, much better solution. Works for me. 👍

**Comment by joecorall** [comment]
I wanted to get this released today, but I also wanted to fix [a recent, unrelated issue](https://www.drupal.org/project/rest_oai_pmh/issues/3110145) with the module, but am having trouble implementing that functionality. If I can't get that separate, unrelated issue implemented by tomorrow morning I can just create a new release with just this new namespace mapping functionality.

**Comment by joecorall** [comment]
Released 8.x-1.0-alpha12 with just this fix in it. Will get another alpha out for the other issue I wanted to roll into this one SOON.
