### ISSUE TITLE
change user in ubuntu to `vagrant`? 

### ISSUE THREAD

**Issue by bseeger** [Islandora/documentation#1431]
This is not an issue, so much as a question/request.  I'm wondering if we can change the main user in ubuntu to `vagrant`.  

The user `ubuntu` is the one with the synced home dir, but since you can't log in as them it's not easy for a novice user to find the `/islandora` dir unless they are comfortable on the command line.   It might make more sense to make the `user` be `vagrant` so that the synced dir shows up in their home dir.  I'm not sure of the full implications of doing this, in terms of setting up the system, so this might not be a good idea.  Is this change as easy as it seems to be, or does it require a big amount of rethinking things? 

Maybe the main user doesn't need to be changed, but just this line could be changed to point to `vagrant`'s home dir: `config.vm.synced_folder ".", home_dir + "/islandora"`? I don't know the full playbook.

Here's the line in the Vagrantfile that sets the user:  https://github.com/Islandora-Devops/islandora-playbook/blob/b3680d2dafb773a468143a968eb7a6be3975dc9c/Vagrantfile#L18

**Comment by bseeger** [comment]
@dannylamb, @seth-shaw-unlv   - my underlying goal here is to make accessing the syn-disabling script easy for novice users at the workshop.  

Right now they'd have to:

- copy the script into their shared dir on their machine. 
- vagrant ssh into vm 
- `cd /home/ubuntu/islandora`  or `cp /home/ubuntu/islandora/the_script.sh .`
- then run script. 

I'd like to eliminate the one step of grabbing things in `/home/ubuntu` if possible. 

But I think this change might be good in general. That being said, I don't understand all the underlying playbook setup.

**Comment by dannylamb** [comment]
I'm fine with removing the `ubuntu` user and just using `vagrant`.  It's just cruft that needs to get removed.

Maybe not everyone would want it, but we could run a "shell" provisioner in the Vagrantfile that curls down your gist and runs it, so folks don't have to do it for the workshop.  I find it best to wrap up this stuff as much as possible for folks.  The more steps, the more likely you are to lose people.

**Comment by bseeger** [comment]
Yeah, that would be great. Just note that I think we will be turning the Syn Valve off for the fedora sessions and then back on again afterwards - so I imagine we will be running it a few times.   But it would be great if the script were "just there" via some magic.

**Comment by bseeger** [comment]
I've changed this in the playbook as well as in the fits ansible role (as that referenced vagrantUser - let me know if that's unnecessary).

**Comment by kstapelfeldt** [comment]
We believe this should be closed, but let us know if there is a piece (such as documentation) that should be added.
