### ISSUE TITLE
Pax Exam IT does not use https for Maven Central

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1443]
When building Alpaca with`.gradlew clean build` an HTTPSRequired error occurs.
```        
java.io.IOException: Error resolving artifact org.apache.karaf:apache-karaf:zip:4.0.6: Could not transfer artifact org.apache.karaf:apache-karaf:zip:4.0.6 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file: http://repo1.maven.org/maven2/org/apache/karaf/apache-karaf/4.0.6/apache-karaf-4.0.6.zip. Return code is: 501 , ReasonPhrase:HTTPS Required.
```

**Comment by whikloj** [comment]
After all my work I final just asked on the listserv....and apparently this is a known issue that was just resolved. I'll update our Pax-Exam dependency and hopefully we are back on track.

https://groups.google.com/d/topic/ops4j/pJ98QaBVPfE/discussion

**Comment by whikloj** [comment]
Actually, we'll need to wait for 4.14.0 to be released. So I am going `@Ignore` this test for the time being.

**Comment by elizoller** [comment]
I proposed in the PR keeping a ticket open as a reminder that Pax Exam will need to be updated - is it ok to keep this ticket open or would it be better to close this one and open a new one related specifically to pax exam?

**Comment by dannylamb** [comment]
It's ok to keep this one. Maybe rename it to "Pax Exam IT does not use
https for Maven Central" just so it's obvious.

**Comment by whikloj** [comment]
4.13.2 was released today. I'll give it a try on Monday (if I remember).

**Comment by elizoller** [comment]
thats convenient

**Comment by dannylamb** [comment]
I'm giving this a whirl right now.  I'll report back.

**Comment by dannylamb** [comment]
4.13.2 results in 

```
> Task :islandora-karaf:test

Gradle Test Run :islandora-karaf:test > Gradle Test Executor 5 > ca.islandora.alpaca.karaf.KarafIT > classMethod FAILED
    java.lang.RuntimeException: Cannot get the remote bundle context

        Caused by:
        java.rmi.NotBoundException: 40723172-e9b4-4dbe-8ea3-eefb797dd736

Gradle Test Run :islandora-karaf:test > Gradle Test Executor 5 > ca.islandora.alpaca.karaf.KarafIT > executionError FAILED
    java.lang.RuntimeException: Container never came up

2 tests completed, 2 failed

> Task :islandora-karaf:test FAILED

FAILURE: Build failed with an exception.

```

I have no idea what that means beyond the fact that karaf couldn't spin up.  How would I be able to diagnose this further?  The HTML report generated just gives me the rest of the stacktrace, and that's it.

**Comment by whikloj** [comment]
Here is discussion thread with the OPS4J mailing list. 

https://groups.google.com/d/topic/ops4j/pJ98QaBVPfE/discussion

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/Alpaca/commit/8c6bc55a7fc3656894d5a8be82f8552e005f1281
