### ISSUE TITLE
Paged Content doesn't display Openseadragon on remote installs

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1445]
There's a hard coded reference to `localhost:8000` in the Openseadragon block configuration: https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/config/install/context.context.openseadragon_block.yml#L30

Because of this, the openseadragon block can't request the manifest in order to render, so it's being skipped :(  `localhost:80` would probabaly work, but we need that `8000` for vagrant.  So we need to find a way to set that properly when provisioning a remote system.

**Comment by mjordan** [comment]
Related to #1358?

**Comment by seth-shaw-unlv** [comment]
@mjordan No, we were able to fix it with a simple config update unrelated to CORS.

**Comment by dannylamb** [comment]
Bumping into this again with ISLE and https://github.com/Islandora-Devops/isle-buildkit/issues/20

We really should make this accept relative paths as well.  If it doesn't get a full url, then attempt to construct one with the provided path.  That way you can pass this config around between sites without worrying about changing the host name all the time.

**Comment by dannylamb** [comment]
....and fixed.  Was getting sick of re-configuring it every time.  If that gets merged, I'll update islandora_defaults appropriately.
