### ISSUE TITLE
Get the detailed stack diagram into the official docs

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1446]
Just making an issue so this doesn't get overlooked. @bseeger made the most comprehensive stack diagram of Islandora 8 to date:

![image](https://user-images.githubusercontent.com/2371345/75297918-7342e280-5807-11ea-8a30-87799b52f0ec.png)

We really should get a nice high-resolution version of this into our docs!

**Comment by manez** [comment]
@bseeger I just grabbed a screenshot from your Islandora/Fedora camp slides, for a visual reference. Can you share the original?

**Comment by bseeger** [comment]
Here's where the original file is located:  https://docs.google.com/drawings/d/1crnifK_4zpP102rIUR2Kc0Ekz91ln2fq4_YjQ9_ziwE/edit

**Comment by seth-shaw-unlv** [comment]
Resolved with 536dec9
