### ISSUE TITLE
Homarus FFMpeg fails on filepaths requiring authentication.

### ISSUE THREAD

**Issue by ajstanley** [Islandora/documentation#1447]
Homarus gets the filepath of the asset requesting a derivative from the Apix-Ldp-Resource header, then takes that filepath as the source argument for FFMpeg.

If that file is not available to an anonymous user the command will fail with a 403, causing the command to fail.  FFMpeg file request will have to be qualified somehow.

**Comment by elizoller** [comment]
closed with https://github.com/Islandora/Crayfish/pull/97
