### ISSUE TITLE
Islandora 8 solr search does not work

### ISSUE THREAD

**Issue by pejuko** [Islandora/documentation#1452]
Steps to reproduce:
```
git clone https://github.com/Islandora-Devops/islandora-playbook
cd islandora-playbook
vagrant up
```
With browser go to localhost:8000 log in and create collection, create image in the collection and upload media. Then go to home page and try to search for title of the created collection or the image. There are no results but when you look into solar server both are indexed.

**Comment by kayakr** [comment]
I'm seeing the same issue. Fresh Islandora 8 VM, new content is indexed in Solr, but search `/solr-search/content?search_api_fulltext=test` returns no results. Even entering a blank search returns no results.

**Comment by seth-shaw-unlv** [comment]
An empty search, in my experience with search_api, always returns no results. 

That said, it should pull up your item if you searched for the item's title and it is in the index. I'll see about verifying tomorrow. I was going to today but my fresh CentOS build died.

**Comment by kayakr** [comment]
* Disabling facets, e.g. `drush pm:uninstall facets` caused the Search to start returning results.
* Results are returned, even when the search filter is empty, e.g. `/solr-search/content?search_api_fulltext=`
* The default search is set to sort by Relevance ASC, but this should be Relevance DESC (e.g. most relevant first)

**Comment by seth-shaw-unlv** [comment]
Found the issue. We aren't importing all the provided configs on install. 

To reproduce:
1. Provision a fresh box
1. Create one or more searchable items (collections, items, subjects, etc.)
1. Search: _finds no results_

To fix: 
1. Import the search feature by importing differences @ `http://localhost:8000/admin/config/development/features/diff/islandora_search`
1. Re-index your site @ `http://localhost:8000/admin/config/search/search-api/index/default_solr_index`
1. Search: _should now return relevant results_

We should update the playbook to make sure all the relevant features are being imported.

**Comment by dannylamb** [comment]
I betcha I sorted this out in the iCampAZ branch of the playbook.  Searching worked for us then.

**Comment by dannylamb** [comment]
Yeah, I sure did: https://github.com/Islandora-Devops/islandora-playbook/compare/iCampAZ
I reworked things in the last ~two~ three files to shuffle around what we enabled and import.

**Comment by dannylamb** [comment]
I'm knee deep in something for ISLE right now, but I'll issue a PR for this.
