### ISSUE TITLE
Update search_api_solr to 3.8 breaks islandora_search

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1463]
@elizoller's search_api_solr PR (https://github.com/Islandora-Devops/islandora-playbook/pull/157) will be merged soon, but the updated version has a small incompatibility in the config that drops the connection to the server. See [this comment on the PR](https://github.com/Islandora-Devops/islandora-playbook/pull/157#issuecomment-598279624).

I'll create a PR to address the compatibility that we can test and merge once https://github.com/Islandora-Devops/islandora-playbook/pull/157 is in.

**Comment by elizoller** [comment]
Closed with https://github.com/Islandora/islandora_defaults/pull/25 c1af384a28e0dafe1519d0b30a263c14a9da96b7
