### ISSUE TITLE
PHP Warning using 7.3

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1466]
Getting this nagging warning on ISLE for Islandora 8.  We're using PHP 7.3 and are getting this:

```Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/web/modules/contrib/islandora/src/EventSubscriber/LinkHeaderSubscriber.php on line 286```

**Comment by whikloj** [comment]
I think we discussed this before, but for reference. https://wiki.php.net/rfc/continue_on_switch_deprecation

**Comment by dannylamb** [comment]
It's eerily similar to another 7.3 warning I fixed recently.

**Comment by akuckartz** [comment]
Wait what will happen with 7.4 ;-)

**Comment by rosiel** [comment]
Pretty sure this can be closed.
