### ISSUE TITLE
Concern about drupal-project support

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1471]
https://www.drupal.org/docs/8/update/update-core-via-composer#known-issues has a message that drupal-project is no longer the recommended way to build Drupal 8. 
"As of January 2020 drupal-composer/drupal-project Composer template for Drupal projects is no longer the recommended template for Drupal 8.8 and above."
https://github.com/drupal-composer/drupal-project has not been updated since Dec 2019.
do we need to consider changing how the drupal 8 build happens in the islandora-playbook?

Maybe this is the right documentation to look at: https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates

**Comment by dannylamb** [comment]
Yeah, this has popped up in ISLE.  There's a [drupal/recommended-project](https://github.com/drupal/recommended-project) instead.

**Comment by dannylamb** [comment]
All we use drupal-project for is to pin down the drupal version on new installs.  If we can do that with the other project, then that's easy enough.

**Comment by elizoller** [comment]
I think we can delete this since we are now using drupal recommended instead of drupal project. Please re-open if you disagree.
