### ISSUE TITLE
Could not locate derivative term with urihttps://projects.iq.harvard.edu/fits

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1475]
I'm investigate an issue that initially presented as `Error: Call to a member function id() on null in Drupal\islandora\Plugin\Action\AbstractGenerateDerivative->generateData() (line 170 of /var/www/drupal/arccen-isl/releases/archivescentral-20200326-2/web/modules/contrib/islandora/src/Plugin/Action/AbstractGenerateDerivative.php)` when submitting a media file (Media Use=Original File).

On investigate, I discovered a probably incorrect check: `$source_term` is checked twice instead of checking `$derivative_term`. See diff at https://github.com/kayakr/islandora/commit/a2ae41a976b6d6ee203fa3422049fbe970179a20

Now that derivative term is being checked I get an error still:
`Error generating event: Could not locate derivative term with urihttps://projects.iq.harvard.edu/fits`

**Comment by kayakr** [comment]
For some reason FITS File term had no External URI defined, so I've manually added https://projects.iq.harvard.edu/fits

**Comment by dannylamb** [comment]
And that means we're missing a row in a migration csv... :man_facepalming:

**Comment by dannylamb** [comment]
Strange, it's supposed to come from https://github.com/roblib/islandora_fits/blob/master/islandora_fits.install#L25.  Did you make the term yourself initially?

**Comment by kayakr** [comment]
@dannylamb no, just the standard migration of islandora tags
```
  Islandora (islandora)   islandora_defaults_tags                     Idle     13      13         0             2020-03-18 15:53:37  
  Islandora (islandora)   islandora_tags                              Idle     16      16         0             2020-03-18 15:54:32  
```

**Comment by kayakr** [comment]
I'm going to close this. Can reopen if it arises again.
