### ISSUE TITLE
Extracted text is not indexed unless you manually reindex

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1476]
Stumbled into this when testing [the build for 1.1.0](https://github.com/Islandora-Devops/islandora-playbook/tree/master).

## To recreate

- Ingest some paged content
- Go to a page and look at its extracted text file
- Search for something in the text
- Should get no results
- Go to Configuration > Search and Metadata > Search API and click on the "Default Solr content index" link next to "Index".
- Re-index solr by clicking on "Queue all items for re-indexing"
- Click confirm
- Scroll down and click "Index now"
- Search again for something you know is in the text
- Now you should get results

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/029bbcfe5dd6abe510bcda8717ed36d4fc61269e
