### ISSUE TITLE
JSONLD Endpoint for Extracted Text is Failing

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1477]
Getting a lot of these as the various camel bits are trying to get things done:

`Message | Error: [] operator not supported for strings in Drupal\islandora\Plugin\ContextReaction\JsonldTypeAlterReaction->execute() (line 59 of /var/www/html/drupal/web/modules/contrib/islandora/src/Plugin/ContextReaction/JsonldTypeAlterReaction.php)
-- | --`

Did some digging and it turns out to always be for Extracted Text media, which don't seem to have an rdf mapping!   We should give it one.  We should also make sure `JsonldTypeAlterReaction` can handle the situation where rdf:type is a string and not an array.

**Comment by seth-shaw-unlv** [comment]
resolved with https://github.com/Islandora/islandora/commit/8b7caa9e8c0b4eac54cdb8c8365eec453e36f369
