### ISSUE TITLE
Stale `field_edited_text` when the associated file is replaced

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1479]
A follow-up to #1476, if you run the extract text action again because the original file was replaced the new Extracted Text _file_ will be replaced but it will not update the `field_edited_text` value with the new content. This is a significant issue because that is the field the full-text search is based on. 

PR ~~incomming~~ _linked below_.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora/commit/163a621bc499d32a3b72da58b16b6a38d77694b4

**Comment by ajstanley** [comment]
I'd approach this with caution - valuable edits could be lost if the derivative file is updated.

**Comment by seth-shaw-unlv** [comment]
@ajstanley is right, we've just traded one unexpected behavior with another. After merging 163a621 a user _can't_ manually edit `field_edited_text` (the presave will just repopulate the field with the extracted text file instead of saving the edits) which makes it a misnomer.

So, we have an impasse. On one hand we want to be able to manually edit OCR results and on the other hand we want to automate repopulating this field if we re-run OCR, potentially with a different/better OCR microservice or setting; however the presave hook has no way of knowing which to preference, the existing value or the contents of the extracted text file.

@dannylamb, we should probably revert the merge, as the original behavior is probably more common than the latter (for now).

**Comment by seth-shaw-unlv** [comment]
Also welcoming thoughts from other @Islandora/8-x-committers.

**Comment by dannylamb** [comment]
I'm happiest with whatever makes sense for users, and am willing to revert/change whatever's neccessary.

**Comment by seth-shaw-unlv** [comment]
@dannylamb, go ahead and revert it.

**Comment by dannylamb** [comment]
https://github.com/Islandora/islandora/pull/770

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora/commit/3c969bf14f1775ebb6c52cc71b7558703f154210?
