### ISSUE TITLE
Resource Type default config is missing from controlled_access_term module

### ISSUE THREAD

**Issue by bseeger** [Islandora/documentation#1499]
Resource Type taxonomy has an External Auth Link field in it, but it doesn't show up when editing a term in the UI. This is because a config file is missing from this module for the Resource Type taxonomy. 

The config should be located here: 
https://github.com/Islandora/controlled_access_terms/tree/8.x-1.x/modules/controlled_access_terms_defaults/config/install

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/controlled_access_terms/commit/56ba6f72fba0f39c16ae3d5dc6ca2916bbd63cd0
