### ISSUE TITLE
Weird behavior of thumbnails in .ova VM

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1502]
I built the .ova, so I feel a bit like I'm tattling on myself here, but I want to know if anyone else is seeing this and/or if there's a fix, in case I should make a new VM without this issue:

When I first start up a VM from the [8 1.1.0 .ova](https://drive.google.com/uc?export=download&id=1hzy4ipCwBZ4Lpng0w8RRmj8WAx1dE9at), even if I've run it before, media on the most recently created nodes does not show up properly. There's a collection "Cat Pictures" with a thumbnail that comes with the VM that has the problem, and new content I've added later shows the same thing.

See here, when I first start up the VM and go to localhost:8000:

![image](https://user-images.githubusercontent.com/2371345/81106573-3c1a3d00-8eec-11ea-9c2e-93e97468b64f.png)

After a minute or two:

![image](https://user-images.githubusercontent.com/2371345/81106890-b21ea400-8eec-11ea-98f4-d55d1a26f86a.png)

The item with the lobster riding a cat is a Collection. The other one is an Image. The Media is listed, but does not show up when accessed directly (metadata does), until a few minutes in. In both cases, the Thumbnail was added on its own and tagged as a thumbnail, instead of being generated from an original file, which I suspect is at the heart of this, but... what's happening?

**Comment by mjordan** [comment]
I am seeing similar behavior. For me, it's the thumbnail of the dog pulling on the shoe laces ("Small puppy") that is last to load. It's always this one. But, if I load a new image, its thumbnail show up as intended, without the delay.

A more general pattern I've noticed is that since derivatives are generated asynchronously after the user submits the ingest form, they often take a few seconds (for most images anyway, big video files might be different) to show up. This is in contrast to Islandora 7, where all derivatives were generated before the user's form submit action completed. Not sure if that's in play here, but probably not if the thumbnails take a few seconds to show up independent of when they were create/generated.

**Comment by manez** [comment]
What I find most odd is that this happens every time I start up the same VM. It's not a first-time loading thing, it's persistent in the same VM after shutting down and restarting. They always show up eventually, but they're not there for the first few minutes.

Probably not a concern for production, if it's just happening when the site is unpacking its toys, but I don't want the VM to give a bad impression. And I'd like to know if this is indicative of anything more serious.

**Comment by manez** [comment]
This may not be anything new. I noticed it because the VM has a special view on the front page showing pretty much all of the nodes, with images built from the thumbnails. Older VMs either didn't have content when first started, or it's a click or two in, giving things time to catch up and maybe concealing this?

Interesting that you're seeing it on a different image @mjordan. I have it only when the thumbnail is loaded manually, so far, but "Small Puppy" was ingested with Migrate from CSV.

**Comment by mjordan** [comment]
Huh, after adding a few more objects, it appears to me that the image that is late to load is consistently the one in the upper-right corner of that front page View's table. So maybe it has nothing to do with the image itself but the way that the table's markup is being rendered.

**Comment by mjordan** [comment]
Maybe try adding a different output formatter to the View to see if the same image(s) load late, or sort differently within the same output formatter?

**Comment by mjordan** [comment]
Nope - I changed the sort on the View to title and the same images are loading late. 🤷‍♂️

**Comment by manez** [comment]
Definitely not just the view. If I go directly to the media, there's a blank space the same dimension as the eventual image.

**Comment by manez** [comment]
@whikloj had a look and found that the thumbnail was being served from Flysystem. It got put into Fedora on upload because it's not a derivative; it's a direct upload tagged as a thumbnail. This is known behavior, but probably not ideal.

**Comment by manez** [comment]
Known issue.
