### ISSUE TITLE
OpenSeadragon gives mixed content warnings 

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1504]
We've encountered mixed content warnings in the browser console as Open Seadragon on an HTTPS site was requesting its navigation button images via HTTP even with X-Forwarded-Proto configured.

**Comment by adam-vessey** [comment]
I think this has been addressed with the move to pull OpenSeadragon from a CDN in https://github.com/Islandora/openseadragon/pull/26; please feel free to reopen if this is not indeed the case.
