### ISSUE TITLE
"inactive" docs are causing problems

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1508]
During the last documentation clean up, I took several pages from our docs that are not appropriate for our official documentation (either they are old and need heavy updating, or they are stubs/works in progress) and shoved them in an ["inactive" folder](https://github.com/Islandora/documentation/tree/master/docs/inactive) in the docs directory. They're not in mkdocs.yml, so they get ignored when [docs](https://islandora.github.io/documentation/)are built.

Not ignored by Travis, though? There's a bad link in one of them, and Travis is failing over it: [see comment](https://github.com/Islandora/documentation/pull/1503#issuecomment-628288797)

Solutions:

1. Delete them once and for all.
2. Move the inactive folder out of the docs directory (but where?)
3. Fix issues in the inactive docs as they arise (which kind of defeats the purpose of shoving them into a pseudo-archived state)
4. Some other obvious and simple solution that I'm not seeing

Thoughts?

**Comment by dannylamb** [comment]
I vote for step 1, burn them with :fire:  They are confusing and still deployed and people can still find them.  Case in point: https://islandora.github.io/documentation/inactive/mvp_doc/#content-modeling-in-fedora
