### ISSUE TITLE
Provide description text for the "PID" field

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1514]
Islandora's default metadata fields include PID, which was intended as the place to store the islandora 7.x PID for each object after migration. Currently, this field doesn't have any description/help text:

![pid](https://user-images.githubusercontent.com/403918/82456413-0ab37c80-9a69-11ea-8491-300e4a70aea2.png)

We should add "PID of this object in Islandora 7.x (applies to migrated objects only)." or something similar.

**Comment by mjordan** [comment]
I'll open a PR for this.

**Comment by mjordan** [comment]
How's this for help text?

> PID of this object migrated from Islandora 7.x.

**Comment by manez** [comment]
@mjordan I think your first suggestion "PID of this object in Islandora 7.x (applies to migrated objects only)" works well. That extra bit of parenthetical info could be reassuring.
