### ISSUE TITLE
Provide a way for repo admins to see RDF field mappings

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1521]
RDF field mappings on a given Islandora repo are a bit hidden. Over at [Islandora Repository Reports](https://github.com/mjordan/islandora_repository_reports) I recently added a... report listing all of the configured mappings:

![rdf_mappings_screenshot](https://user-images.githubusercontent.com/403918/82928079-8cf2e380-9f36-11ea-9d2c-9e3e02112dfe.png)

The user can select which bundle (in this case, which node content type or media type) to show the mappings for. 

If people would find this a useful addition to the core Islandora module, I'd be happy to open a PR for that. The code to generate this report is already in the `getData()` function in https://github.com/mjordan/islandora_repository_reports/blob/master/modules/islandora_repository_reports_rdfmappings/src/Plugin/DataSource/RdfMappings.php#L62-L109 so it shouldn't be to much work to repurpose it into a standalone report linked from `admin/reports`, for example. 

If you'd find this useful, please vote on this with 👍 or leave a comment.

**Comment by manez** [comment]
I'd like to see all of [Islandora Repository Reports](https://github.com/mjordan/islandora_repository_reports) come into core (or at least have the module become part of our standard build'), but this particular piece of it seem like a key tool that really does belong in core.

**Comment by mjordan** [comment]
@manez integrating the Repo Reports module into Islandora core would probably be more complicated than keeping it as a separate (but standard) module. I'd be happy to work on bringing it up to the coding and testing standards required by the LSAP process and when that's done, initiate an LSAP for it.

That said, integrating the RDF mapping report on its own, independent of the Reports module, into core would be a simple, non-disruptive PR against Islandora.

**Comment by bseeger** [comment]
Yes please. This sounds really useful!

**Comment by mjordan** [comment]
It might be useful to also include a list of taxonomy terms that have external URIs assigned. Moar Linked Data.

**Comment by mjordan** [comment]
Merged, closing.

**Comment by dannylamb** [comment]
Using this to track https://github.com/Islandora/islandora/pull/827 for the sprint.

**Comment by elizoller** [comment]
closed with https://github.com/Islandora/islandora/pull/835
