### ISSUE TITLE
Geerlingguy broke ansible galaxy references

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1522]
Apparently Geerlingguy changed a number of roles on ansible galaxy a few hours ago which breaks our playbook.

Run the playbook as is and you get:
```
    default: Running ansible-galaxy...
- downloading role 'php-mysql', owned by geerlingguy
 [WARNING]: - geerlingguy.php-mysql was NOT installed successfully: - sorry,
geerlingguy.php-mysql was not found on https://galaxy.ansible.com.
```

Indeed, now [https://galaxy.ansible.com/geerlingguy/php-mysql](https://galaxy.ansible.com/geerlingguy/php-mysql) returns a 404. But, if you replace the hyphen with an underscore, [https://galaxy.ansible.com/geerlingguy/php_mysql](https://galaxy.ansible.com/geerlingguy/php_mysql), it resolves. 

So, you have to update requirements.yml and whichever roles use the underscore versions (e.g. webserver.yml and crayfish.yml) to make it work. This is true for php-mysql, repo-remi, repo-epel, and php-versions. (Oddly, drupal-console has been spared as of yet.)

**Comment by jhujasonw** [comment]
I just tried https://galaxy.ansible.com/geerlingguy/php-mysql and it works.  Might have been a blip in galaxy.ansible.com   Just thought I would mention that it appears to work, at least for that role.

**Comment by seth-shaw-unlv** [comment]
Huh, I wonder if Geerlingguy realized the issue and fixed it. The last import of the role was ~20 hours ago.

I can spin up a new one after my next meeting and close the ticket if it checks out.

**Comment by seth-shaw-unlv** [comment]
Whelp, I'm glad I didn't run off an issue a PR right away! Everything builds fine again. Yay for procrastination!
