### ISSUE TITLE
What is the islandora_version_count table used for?

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1528]
islandora.install creates the db table `islandora_version_count`, which is annotated as 'Keeps track of the number of changes to an entity'. However, grepping through the contrib modules directory only reveals a single use of 'islandora_version_count', in the .install file, and creating a new revision of a node doesn't add anything to the table. Is this still in use, and if so, what populates it?

**Comment by whikloj** [comment]
Ohhhhh waaaaay back (yes kids, there was a time before COVID-19) that was going to be how we enforced write order to Fedora. To ensure that in the case of two instantaneous edits we didn't end up with the wrong state in Fedora compared to Drupal we would check that the counter of the new write was one more than the counter of the current document. It may not be needed anymore but we haven't done a lot of multi-edit testing and depending on how asynchronous your Fedora is this could still be an issue.

**Comment by mjordan** [comment]
Ah. Thanks for the background.

**Comment by mjordan** [comment]
Should I just close this?

**Comment by whikloj** [comment]
🤷

**Comment by dannylamb** [comment]
Burn it with :fire:?

We didn't implement it... and may very well never...

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/0097808bddf2de94c772f7ca94c32bf373ebc730
