### ISSUE TITLE
Bug: edtf date validation problems

### ISSUE THREAD

**Issue by patdunlavey** [Islandora/documentation#1533]
A few things in EDTFUtils::validate():

1. Line 140: The regex pattern for a date set should not have the char lists internally separated by commas. Valid multiple date set strings are not matched.
2. Line 140: I think the string `[]` should not be considered a properly encoded date string, so I think the date part match group quantity should be changed from `*` to `+`.
3. Line 141: When there is a match, $match[1] and $match[2] will never equal each other. If `$has_match` is false, that's sufficient. And, we should return at this point, there's no reason to continue testing each date in the set.
4. Line 159: `!$date === '..'` will never be true. Put the negation outside the expression by using parentheses.

PR coming...

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/controlled_access_terms/commit/c19f743c103831e5074a2dacd41ed9c84925e3d4. 

However, this reminds me that we really need to add some unit tests for validation, if nothing else.
