### ISSUE TITLE
Tighten access to Islandora IIIF config form

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1534]
In Islandora 8, I notice any user with 'access administration pages' can get to '/admin/config/islandora/iiif' and change the URL. We have users with administration page access for content administration, moderation etc. that we don't want to alter site configuration. I suggest the appropriate permission is 'administer site configuration' instead.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora/commit/a51db93ec10f8bf670904e106bc9de0f8854939f
