### ISSUE TITLE
Update Drupal to 8.9.0

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1536]
https://www.drupal.org/project/drupal/releases/8.9.0

Since 8.9.0 requires PHP 7.3 this will have implications for the development VM at https://github.com/Islandora-Devops/islandora-playbook

**Comment by whikloj** [comment]
Playbook is installing Drupal 9, so I think this can be closed. Is that okay @kayakr?

**Comment by DonRichards** [comment]
Isle-dc/buildkit is still on 8.x
