### ISSUE TITLE
Add 'Edit this page' and 'Request documentation changes' links on every page of documentation

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1546]
See [the docker docs](https://docs.docker.com/engine/reference/commandline/context/) for an example.  It's just links back to Github, but they're handy and might encourage contributions.

**Comment by rosiel** [comment]
It's done already by mkdocs! https://github.com/mkdocs/mkdocs/issues/269

**Comment by rosiel** [comment]
They're defaulting to 'master', which isn't available anymore. I think there might be a way to configure the material theme to use a different branch...

**Comment by hannesdelbeke** [comment]
~~is there any documentation by mkdocs that explains how to do this?~~  
found it: [docs](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon)  

the linked issue links to another issue, which links to another issue, which links back to the first issue
