### ISSUE TITLE
RDF mappings report doesn't display mappings with multiple predicate values

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1549]
The RDF mappings report from #1521 displays a single predicate per Drupal field but the RDF mapping yaml allows multiple potential mappings, e.g. Drupal `title` mapping to `dcterms:title` (appears in report) and `rico:name` (doesn't appear in report).

/cc @mjordan

**Comment by mjordan** [comment]
Resolved with https://github.com/Islandora/islandora/pull/782.
