### ISSUE TITLE
RDF Mapping report: Add bundle to RDF Type display

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1550]
e.g. not just field level but node bundle to `pcdm:Object`, `rico:Record` etc., or Corporate taxonomy term bundle to `schema:Organization`, `rico:CorporateBody`.

/cc @mjordan

**Comment by mjordan** [comment]
> Corporate taxonomy term bundle to schema:Organization, rico:CorporateBody.

@kayakr it looks like Islandora Defaults doesn't ship with any RDF mappings for vocabularies. Is that correct? If so, can you suggest some YAML I can use to create one for dev/testing purposes?

**Comment by mjordan** [comment]
Scratch ^^, Drupal calls vocabularies "taxonomy_term" for RDF mappings. Doesn't make sense to me, but that doesn't matter.

**Comment by seth-shaw-unlv** [comment]
@mjordan vocabulary is to taxonomy_term as content type is to node. Ergo, while the Islandora Defaults content type has  [`rdf.mapping.node.islandora_object.yml`](https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/config/install/rdf.mapping.node.islandora_object.yml) (emphasis on *node* in that filename) the Corporate Body vocabulary has  [`rdf.mapping.taxonomy_term.corporate_body.yml`](https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/modules/controlled_access_terms_defaults/config/install/rdf.mapping.taxonomy_term.corporate_body.yml). 

Blame the RDF module for their naming convention. 🤷‍♂️

**Comment by mjordan** [comment]
Resolved with https://github.com/Islandora/islandora/pull/782.
