### ISSUE TITLE
Bug: LinkHeaderSubscriber throws exceptions when attempting to generate links for entities without canonical URLs

### ISSUE THREAD

**Issue by adam-vessey** [Islandora/documentation#1551]
In [`LinkHeaderSubscriber::generateEntityReferenceLinks()`](https://github.com/Islandora/islandora/blob/bbcd28ccb53e5c7cff856961aba8779bb3d426aa/src/EventSubscriber/LinkHeaderSubscriber.php#L179-L239), we attempt to [generate](https://github.com/Islandora/islandora/blob/bbcd28ccb53e5c7cff856961aba8779bb3d426aa/src/EventSubscriber/LinkHeaderSubscriber.php#L208) [`canonical`](https://github.com/Islandora/islandora/blob/bbcd28ccb53e5c7cff856961aba8779bb3d426aa/src/IslandoraUtils.php#L571) URLs for all referenced entities, expecting that all referenced entities _have_ canonical URLs; however, this is not the case. Some entities (such as [`block` entities](https://git.drupalcode.org/project/drupal/-/blob/f63bd1c6d684004c59656c9a784835edac10d33f/core/modules/block/src/Entity/Block.php#L41-46)) _do not_ specify a canonical URL template by default.

... This leads to errors and whitescreens when attempting to deal with this content.

**Comment by dannylamb** [comment]
resolved via https://github.com/Islandora/islandora/commit/bfa2c39f1ff7877cd388a9c478d2a989e9cefa3a
