### ISSUE TITLE
PDF Viewer Error Unexpected server response

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#1571]
>Unexpected server response.
> PDF.js v2.0.943 (build: dc98bf76)
> Message: Unexpected server response (500) while retrieving PDF "http://localhost:8000/_flysystem/fedora/2020-07/tennessee-alumnus.-volume-92-issue-1-2012-winter-alumnus_1507303279.pdf".

Tried renaming the file and replacing the PDF in case the filename was causing an issue but had the same result. This is happening on my local VM (islandora_playbook) and my AWS server (isle-dc). 

This is my local VM
<img width="1023" alt="Screen Shot 2020-07-28 at 8 02 20 AM" src="https://user-images.githubusercontent.com/2738244/88662916-b0f2b280-d0a8-11ea-8dd9-f253d035471f.png">

This is ISLE-DC
<img width="950" alt="isle-pdf-error" src="https://user-images.githubusercontent.com/2738244/88663451-a258cb00-d0a9-11ea-8d5f-99fb78007361.png">

**Comment by mjordan** [comment]
Anything useful for that 500 response in either the drupal or fedora error logs? Sorry, I don't know off the top of my head where the fedora error logs are but others would. Can you share (privately if you want) the PDF so others can see if the problem is specific to the PDF?

**Comment by rosiel** [comment]
(taking notes here from the committers call, relating to troubleshooting)
- renaming the pdf to example.pdf did not work; 
- is the file in Fedora? (if not, could there be a 404 getting masked by flysystem? If that's happening, that seems like a problem on its own). In this case, he file can be accessed from Fedora directly. 

Hmm.

**Comment by elizoller** [comment]
i have a vagrant setup (on the ubuntu basebox) from a few weeks ago and uploaded and viewed pdf in pdfjs without problem. then i spun up a vagrant vm with the islandora basebox and created an item and uploaded a pdf and it also displayed correctly in pdfjs. i suspect there may be something going on in your environment? i'd recommend looking through some of the logs - like are there js console errors? is that file directly reachable at the filesystem url (outside of pdfjs)? is the file reachable directly in fedora at something like localhost:8080/fcrepo/rest/2020-07/...
i don't have an up and running isle set up, but i suspect that's a very different issue (based on the screenshots)

**Comment by kstapelfeldt** [comment]
If this is still an issue, please re-open with additional steps to reproduce.
