### ISSUE TITLE
Support multiple Open Seadragon Viewer windows on a single page

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1572]
If you attempt to provide multiple images with Open Seadragon view modes selected (e.g. a view displaying multiple nodes with the Open Seadragon display mode selected) only **one** viewer will work. The rest are all black rectangles.

We should allow multiple viewers to work on the same page. PR incomming.

**Comment by mjordan** [comment]
@seth-shaw-unlv this sounds like it's related to https://github.com/Islandora/documentation/issues/1242.

**Comment by seth-shaw-unlv** [comment]
@mjordan, looking at the original issue, I'm not convinced that they are. In the 1242 ticket is was about displaying multiple Service Files attached to a single node. In this case I have a view displaying two nodes with the open seadragon viewmode enabled. The trouble with this ticket is specific to the openseadragon viewer.

**Comment by mjordan** [comment]
Correct, it is a bit different, and specific to OSD. Thanks for the clarification.

**Comment by mjordan** [comment]
@seth-shaw-unlv OK to close this?

**Comment by seth-shaw-unlv** [comment]
Huh, I guess we forgot to close this when the PR merged.  Thanks for the heads-up, @mjordan.

Resolved by https://github.com/Islandora/openseadragon/commit/f99e4a288688de5cf52b5ba8e92e7997cfbe0869.
