### ISSUE TITLE
Add a 'Pass Through URI' Data Converter to JSON-LD

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1581]
At times when creating our JSON-LD for a repository object we have entity reference fields where we don't want the targeted taxonomy term, we want the value stored in a term's field. Examples include rights statements URIs (see @elizoller 's [comment](https://github.com/Islandora/documentation/issues/1234#issuecomment-656845980)), genre terms, or subjects where we would rather our RDF refer to the external URI rather than our internal one.

Instead of 
```
{
   "@graph":[
      {
         "@id":"http://localhost:8000/node/2",
         "@type":[
            "http://pcdm.org/models#Object",
            "http://purl.org/coar/resource_type/c_c513"
         ],
         "http://purl.org/dc/terms/title":[
            {
               "@value":"Item 2",
               "@language":"en"
            }
         ],
         "http://purl.org/dc/terms/rights":[
            {
               "@id":"http://localhost:8000/term/34",
            }
         ],
         "http://schema.org/sameAs":[
            {
               "@id":"http://localhost:8000/node/2"
            }
         ]
      },
      {
         "@id":"http://localhost:8000/term/34",
         "@type":[
            "http://purl.org/dc/terms/RightsStatement"
         ]
      }
   ]
}
```
which would then have a 'sameAs' (or close match, whatever the predicate is...) jump over to the actual rights statement URI, we could have the simpler:
```
{
   "@graph":[
      {
         "@id":"http://localhost:8000/node/2",
         "@type":[
            "http://pcdm.org/models#Object",
            "http://purl.org/coar/resource_type/c_c513"
         ],
         "http://purl.org/dc/terms/title":[
            {
               "@value":"Item 2",
               "@language":"en"
            }
         ],
         "http://purl.org/dc/terms/rights":[
            {
               "@id":"http://rightsstatements.org/vocab/InC-NC/1.0/"
            }
         ],
         "http://schema.org/sameAs":[
            {
               "@id":"http://localhost:8000/node/2"
            }
         ]
      }
   ]
}
```

I'm working on a PR that adds a Data Converter class that allows us to use the rdf mapping config to specify what field in the target should be used for the transformation as well as refactors the EntityReferenceItemNormalizer to allow for this case. I just need to clean it up a bit and hopefully add a test or two before I submit it.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/jsonld/commit/659ef3579e7ed9f651c1d5d782182419733fd23f
