### ISSUE TITLE
Playbook fails on drupal-console; geerlingguy has deprecated

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#1599]
The playbook fails.

Tracking down discussion on slack (thanks @mjordan  and @elizoller !!) to why Drupal Console breaks the playbook:

Since Aug 17,  https://drupalconsole.com/installer  is no longer working. Issue: https://github.com/hechoendrupal/drupal-console/issues/4262   Suggestion was to use Composer to require Drupal Console.

We get drupal console through Geerlingguy's role. https://github.com/geerlingguy/ansible-role-drupal-console It is deprecated as of August 20, 2020. (#2020mood)

On Aug 25, "unknownterritory" posted how to composer require drupal console via ansible. Can we do this in the playbook? https://github.com/hechoendrupal/drupal-console/issues/4262#issuecomment-680254822

**Comment by mjordan** [comment]
@rosiel, fix has been merged, OK to close?

**Comment by rosiel** [comment]
Yahoo!

**Comment by red7-soporte** [comment]
Greetings for all
Most of us new users use the playbook to install islandora 8 (https://github.com/Islandora-Devops/islandora-playbook). Changes made to the drupal.yml file works fine for the development version (islandora-playbook-dev), but Danny's playbook doesn't have the updates from here.

**Comment by rosiel** [comment]
Thanks @red7-soporte ! 

Yes, the fix was applied to the dev branch. which we all thought was also the default branch of the islandora-playbook repo. 

The fact that 'main' is now the default branch may have been an accident with a large-scale script that changed our default default branch name from master to main. 

I think the intention is that
```
git clone https://github.com/Islandora-Devops/islandora-playbook
cd islandora-playbook
vagrant up
```
is supposed to work.

The main branch is 'pinned to' our release, but ... it should be possible to also spin up the release, and this is a change purely to the playbook/installation instructions. I therefore think we should apply this fix to 'main' as well (as any other branches that should be live).

@dannylamb @mjordan @elizoller (who posted about which branch should be default, back on Sept 1, in slack).

**Comment by red7-soporte** [comment]
Hi! 
I tested the last updates in https://github.com/Islandora-Devops/islandora-playbook , all works fine!. Thanks 
to all.
