### ISSUE TITLE
"Mirador" tag is added independently of Islandora Mirador being enabled

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1608]
Islandora Defaults add the "Mirador" display hint tag (https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/migrate/tags.csv#L4), regardless of whether Islandora Mirador is enabled (it isn't by default). This means that the "Mirador" display hint is exposed to the user even when that module is not enabled, which I believe is confusing:

![displayhints](https://user-images.githubusercontent.com/403918/92334014-e347e600-f03e-11ea-88e7-ba77ffc15178.png)

Couple of possible fixes:

* document this
* move the migration that adds the "Mirador" display hint tag from Islandora Defaults to the Islandora Mirador module

Other suggestions?

**Comment by kayakr** [comment]
@mjordan This could be moved to Islandora Mirador. On canterburystories.nz we have several custom modules adding display hints like Carousel, or Slideshow, leaving Islandora Defaults untouched but migrating terms to `islandora_display` taxonomy.

**Comment by elizoller** [comment]
Ah ok. Like a migration in islandora_mirador that adds the Mirador term to the islandora display hints vocabulary?

**Comment by seth-shaw-unlv** [comment]
Not necessarily a migration. You can add it in an install/update hook.

**Comment by elizoller** [comment]
Right. I’ll try to get a PR up today.
