### ISSUE TITLE
Documentation: islandora-playbook README link for installation docs is currently broken

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#1616]
The islandora-playbook README link for installation docs is currently broken

The link label is "official installation documentation for Islandora 8" and the current URL is:

https://islandora.github.io/documentation/installation/

which does not load content. We may just want to create some basic content for that URL so that it loads something. 

For now I am proposing changing the link in the README to this URL that does load content:
https://islandora.github.io/documentation/installation/component_overview/

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-Devops/islandora-playbook/commit/3c78ba7a1e4c037d3f211fed8ed3bc3b6203b389
