### ISSUE TITLE
Ainsible build fails due to Drupal Console URL being a 500

### ISSUE THREAD

**Issue by klidifia** [Islandora/documentation#1634]
The full ainsible build doesn't complete as it stops when trying to fetch https://drupalconsole.com/installer

It seems that this URL has been down intermittently over the last several weeks becoming a persistent issue.

```
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
Thursday 01 October 2020  10:39:15 +1300 (0:00:00.029)       0:04:40.242 ****** 
fatal: [default]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "elapsed": 2, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "status_code": 500, "url": "https://drupalconsole.com/installer"}
```

I tried changing it to use composer in `/roles/external/geerlingguy.drupal-console/tasks/main.yml` but could not get it to work, but wonder if that could be the right approach to take.

It currently reads as:

```
- name: Install Drupal Console.
  get_url:
    url: https://drupalconsole.com/installer
    dest: "{{ drupal_console_path }}"
```

I tried changing to a few other variants including:

```
- name: Install Drupal Console.
    shell: >
      composer global require drupal/console && cp $(composer global config home)/vendor/bin/drupal  {{ drupal_console_path }}
```

**Comment by elizoller** [comment]
are you running on the dev branch of the playbook?
we recently merged a PR to remove the geerlingguy.drupal-console role and use composer to install drupal-console 
PR is here: https://github.com/Islandora-Devops/islandora-playbook/pull/186

**Comment by klidifia** [comment]
No I was using the main branch because I wanted the full build, following from [this part](https://github.com/Islandora/documentation/blob/main/docs/installation/playbook.md#installing-a-local-development-environment).

But thank you and yes: I cherry-picked [ef940b797ec699121c1580daacf000517419fd39 (remove dependency on geerlingguy drupal console ansible role because...)](https://github.com/Islandora-Devops/islandora-playbook/pull/186/commits/ef940b797ec699121c1580daacf000517419fd39)

And it works fine (main branch with that commit added).

**Comment by rosiel** [comment]
We no longer use Drupal Console since https://github.com/Islandora-Devops/islandora-playbook/pull/186. 

Edit to say: You may need to be on the `dev` branch of the playbook.
