### ISSUE TITLE
ansible - Installation starting from Windows

### ISSUE THREAD

**Issue by DanRoller** [Islandora/documentation#1652]
Issues with installing Islandora 8 as a newbie to Drupal.
I'm a retired software developer with some unix experience, trying to
evaluate Islandora 8 for our local library's digital collections.

Any help would be appreciated!

The current instructions presume that you are starting with a linux
based machine and creating another virtual machine.

However I am on Windows 10. So I tried to follow the instructions, 
as if I can setup a ubuntu machine running as a vm of VirtualBox 
which would recreate your instruction's starting point.

So I trashed the wsl, installed VirtualBox, and created an ubuntu 20,04 virtual
 machine.

My problems are 
(1)	Starting with a Windows machine
(2)	Running virtualbox under ubuntu under Windows. Is it a Guest version? Duh? 
(3)	What is up with "Availiable boxes" in Vagrantfile?
(4) Also, I found missing pip, curl, python.
(5) Also, Email address islandora@googlegroups.com at bottom of 
https://islandora.github.io/documentation/installation/playbook/ rejected.

I followed the items below (plus stuff for setting up a Ubuntu virtualbox machine).

Requirements
	Virtual box
	Vagrant
	Git
	OpenSSL
	Ansible - probably not
https://islandora.ca/download
Getting Started with Islandora 
Islandora 8 Current Version: 1.1.0
Build and install with Ansible
https://github.com/Islandora-Devops/islandora-playbook 
Use: Official documentation for Islandora 8
https://islandora.github.io/documentation/installation/playbook/ 

 
From Official documentation for Islandora 8  (using main branch) 
https://islandora.github.io/documentation/installation/playbook/ 
Quick start mode
$ git clone -b dev https://github.com/Islandora-Devops/islandora-playbook
$ cd islandora-playbook
$ vagrant up

But first install on ubuntu
VirtualBox on ubuntu - duh? Still working on this..
Git - done
Vagrant - downloaded Linux (others include Windows Debian…)
OpenSSL - done
Ansible - probably not needed

Installing Git, OpenSSL, and Ansible on Ubuntu/Debian
# Install git and openssl
$ sudo apt-get install git
OKAY
$ sudo apt-get install openssl
OKAY
# If pip isn’t already available, run the following commands to install it

Pip not there, curl not there, I installed both

$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

Python not there, I installed

$ python get-pip.py --user
# Install ansible
$ pip install --user -Iv ansible==2.8.7
OKAY
Clone the playbook
$ git clone -b main https://github.com/Islandora-Devops/islandora-playbook
$ cd islandora-playbook
OKAY

Set the base box
To tell Vagrant which base box to use, set ISLANDORA_DISTRO. This can be done by editing the Vagrantfile or by setting a shell variable.

# Available boxes are 'islandora/8', ubuntu/bionic64' and 'centos/7'
# Use 'ubuntu/bionic64' or 'centos/7' to build a dev environment from scratch.
# Use 'islandora/8' if you just want to download a ready to run VM.
$vagrantBox = ENV.fetch("ISLANDORA_DISTRO", "islandora/8")

But I find
# Available boxes are 'ubuntu/xenial64' and 'centos/7'
$vagrantBox = ENV.fetch("ISLANDORA_DISTRO", "ubuntu/bionic64")

Thank you for your time.

**Comment by DanRoller** [comment]
Continuing, installing VirtualBox and then mesting of virtual machines

**Install VirtualBox on Ubuntu**
vboxmanage list vms
on Windows
"Ubuntu20.04Desktop" {9088d6f8-35bb-40a8-9e31-01c72769947c}
on Ubuntu
"Islandora 8 Ansible" {953b5041-a449-4c26-a816-813b1e2ba0e0}

Restart Ubuntu, VirturalBox  error is now
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "953b5041-a449-4c26-a816-813b1e2ba0e0", "--type", "headless"]
Stderr: VBoxManage: error: The virtual machine 'Islandora 8 Ansible' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Allow nesting**
	VBoxManage modifyvm "Ubuntu20.04Desktop" --nested-hw-virt on
Had to shutdown of ubuntu,
VirturalBox  start Ubuntu on Host Windows
	fails
	Cannot enable nested VT-x/AMD-V without 
		nested-paging and unresricted guest execution!
	(VERR_CPUM_INVALID_HWVIRT_CONFIG).

Google at https://nullrend.com/11909/verr_cpum_invalid_hwvirt_config/
says, do in powershell
	Disable-WindowsOptionalFeature -online -FeatureName VirtualMachinePlatform
forcing Windows reboot.

Ubuntu now starts.

vagrant up failed as before.

Try deleting the VM created by vagrant
VBoxManage unregistervm --delete "Islandora 8 Ansible"
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'islandora/8' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'islandora/8'
    default: URL: https://vagrantcloud.com/islandora/8
==> default: Adding box 'islandora/8' (v1.1.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/islandora/boxes/8/versions/1.1.0/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'islandora/8' (v1.1.0) for 'virtualbox'!
==> default: Importing base box 'islandora/8'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'islandora/8' version '1.1.0' is up to date...
==> default: Setting the name of the VM: Islandora 8 Ansible
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 5432 (guest) => 5432 (host) (adapter 1)
    default: 8983 (guest) => 8983 (host) (adapter 1)
    default: 8161 (guest) => 8161 (host) (adapter 1)
    default: 8081 (guest) => 8081 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "dd8507b3-a70e-48eb-9909-74a4a9318a56", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'Islandora 8 Ansible' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

I believe this is the same error as before BUT so much more happened!

I'm stuck but will tryout https://github.com/hashicorp/vagrant/issues/8687 ideas, tomorrow !

**Comment by DanRoller** [comment]
Continuing, timeout on vagrant up.
Perhaps it won't be me to evaluate Islandora 8's viability,  I'll hunt for another alternative.

**Comment by manez** [comment]
@DanRoller I don't think there has been a lot done to evaluate the ansible build in Windows, but there is an alternate method for deployment, using Docker, that has been tested and documented in Windows: https://islandora.github.io/documentation/installation/docker-compose/

Edit to add: I'm going to put in a PR against the readme to make the Docker option easier to find. The documentation is pretty new, but the Docker approach itself has been in development for a while and has a lot of support from Islandora users.

**Comment by DanRoller** [comment]
I'm moving on.  This process is too complex for me.
I'm trying to understand Islandora and Drupal, as a 70 year
old volunteer I can't deal with extra side issues.

I did the ISLE Islandora install.  It demanded port 80 which robbed my IIS/Windows world of my own database web apps.  Wsl or whatever had a bad leak and would lock up the processor in a couple of days, before I could learn much.

My current hope is Binami's Drupal stack for Windows .  It installed in less than a half hour, adding its own MySql ignoring mine, its own php, its own Apache, etc.  I get to add to, rather than chisel away.

hurray!

Thanks for your time.

**Comment by elizoller** [comment]
I don't mean to complicate things but I'll just throw this out there.
I have used DrupalVM on my mac to create Islandora instances and it works well for the Drupal side of things, but if you want the entire Islandora stack (fedora, blazegraph, microservices, etc.), you'd likely either need to run portions of the playbook pointed at your local VM (assuming that's what Bitnami is) or manually install things on that VM (ie Tomcat, Fedora, Blazegraph, Karaf, Crayfish, etc....) or host those services on another VM and point to them externally. 
Without those additional features (fedora, blazegraph, microservices, etc.), your Islandora will be pretty sparse (no Fedora layer, no triplestore, no derivatives, etc)

**Comment by DanRoller** [comment]
elizoller, I'm sure you right!  When I regain my patience, I'll have to ..

**Comment by DanRoller** [comment]
Give the progress(?) that I have made on this. I should be closed.
See: issue "ansible vagrant Please fix these errors and try again." for the rest of the story.
