### ISSUE TITLE
Composer issue when running "vagrant up"

### ISSUE THREAD

**Issue by kylehuynh205** [Islandora/documentation#1663]
Hello,I am trying islandora playbook: https://github.com/Islandora-Devops/islandora-playbook. I got the following error when I run "vagrant up",  It seems like composer need to downgrade to <2.0 version. 

`{
  "changed": true,
  "cmd": [
    "/usr/local/bin/composer",
    "create-project",
    "islandora/drupal-project:8.8.1",
    "/tmp/composer-project",
    "--prefer-dist",
    "--stability",
    "dev",
    "--no-interaction"
  ],
  "delta": "0:00:24.676947",
  "end": "2020-10-26 21:17:46.815108",
  "msg": "non-zero return code",
  "rc": 2,
  "start": "2020-10-26 21:17:22.138161",
  "stderr": "Creating a \"islandora/drupal-project:8.8.1\" project at \"/tmp/composer-project\"\nInstalling islandora/drupal-project (8.8.1)\n  - Downloading islandora/drupal-project (8.8.1)\n  - Installing islandora/drupal-project (8.8.1): Extracting archive\nCreated project in /tmp/composer-project\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - drupal/console[1.0.2, ..., 1.9.5] require drupal/console-extend-plugin ~0 -> satisfiable by drupal/console-extend-plugin[0.1.0, ..., 0.9.4].\n    - drupal/console-extend-plugin[0.1.0, ..., 0.9.4] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.\n    - Root composer.json requires drupal/console ^1.0.2 -> satisfiable by drupal/console[1.0.2, ..., 1.9.5].\n\nYou are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.",
  "stderr_lines": [
    "Creating a \"islandora/drupal-project:8.8.1\" project at \"/tmp/composer-project\"",
    "Installing islandora/drupal-project (8.8.1)",
    "  - Downloading islandora/drupal-project (8.8.1)",
    "  - Installing islandora/drupal-project (8.8.1): Extracting archive",
    "Created project in /tmp/composer-project",
    "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion",
    "Loading composer repositories with package information",
    "Updating dependencies",
    "Your requirements could not be resolved to an installable set of packages.",
    "",
    "  Problem 1",
    "    - drupal/console[1.0.2, ..., 1.9.5] require drupal/console-extend-plugin ~0 -> satisfiable by drupal/console-extend-plugin[0.1.0, ..., 0.9.4].",
    "    - drupal/console-extend-plugin[0.1.0, ..., 0.9.4] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.",
    "    - Root composer.json requires drupal/console ^1.0.2 -> satisfiable by drupal/console[1.0.2, ..., 1.9.5].",
    "",
    "You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2."
  ],
  "stdout": "",
  "stdout_lines": []
}`

I am wondering where should I declare installed composer version ? I tried to put "composer_version: 1.0" at requirement.yml and drupal.yml (https://github.com/Islandora-Devops/islandora-playbook/blob/dev/inventory/vagrant/group_vars/webserver/drupal.yml#L3), it generated different error.

**Comment by dflitner** [comment]
I don't know how to adjust the box settings to change the version of Composer but I did it directly by using `composer self-update --1` to downgrade to 1.10.16. I have Composer installed globally on my computer. I hope that works for you as well.

We just discussed updating the libraries and modules that we use to work with Composer 2 in the tech call but haven't started it yet.

**Comment by alxp** [comment]
PRs:

Crayfish: https://github.com/Islandora/Crayfish/pull/107
islandora-playbook: https://github.com/Islandora-Devops/islandora-playbook/pull/193

**Comment by kylehuynh205** [comment]
Hello, I tried the fixes and an error occurred: 

```
TASK [gather facts] ************************************************************
Friday 30 October 2020  15:02:51 -0400 (0:00:00.336)       0:00:00.393 ******** 
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"127.0.0.1\". Make sure this host can be reached over ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey,password).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0   
```

But it works but I ran with "sudo vagrant up", and it started download 'islandora/8' box, I am not sure if that's normal. Anyways, the playbook start working for me. Thank you so much for you help.

**Comment by kylehuynh205** [comment]
It fully works for me now. Thank you for resolve the issue.
