### ISSUE TITLE
Expose services through a single domain

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1665]
Right now, ISLE uses subdomains for some services, while some others are served under sub-paths from the "main" domain to dance around CORS.  By default what you get is:

- Activemq -> activemq-isle-dc.traefik.me
- Blazegraph -> blazegraph-isle-dc.traefik.me/bigdata
- Cantaloupe -> islandora-isle-dc.traefik.me/cantaloupe
- Drupal -> islandora-isle-dc.traefik.me
- Fcrepo -> fcrepo-isle-dc.traefik.me/fcrepo/rest
- Matomo -> islandora-isle-dc.traefik.me/matomo
- Solr -> solr-isle-dc.traefik.me

Managing these multiple and inconsistent subdomains make configuring the site, especially changing domains, a pain. Ideally, we'd have one variable in the .env file. `$DOMAIN` or something of the sort.  And from that, we'd expose services as subpaths. 

- Activemq -> islandora-isle-dc.traefik.me/activemq
- Blazegraph -> islandora-isle-dc.traefik.me/bigdata
- Cantaloupe -> islandora-isle-dc.traefik.me/cantaloupe
- Drupal -> islandora-isle-dc.traefik.me
- Fcrepo -> islandora-isle-dc.traefik.me/fcrepo/rest
- Matomo -> islandora-isle-dc.traefik.me/matomo
- Solr -> islandora-isle-dc.traefik.me/solr

**Comment by joshdentremont** [comment]
@dannylamb It looks like things have changed since you opened this. Is this now working how you were expecting, or is there more to be done?

I'm looking into documenting how to run two copies of Isle-DC so if we're still looking to make some changes to this I'd like to take a crack at it.

**Comment by dannylamb** [comment]
@joshdentremont I'll close this issue.  This is how things are working now.  All the exposed services are through one domain.  We still need work on https://github.com/Islandora/documentation/issues/1667 to make everything configurable, but what you get uses the `$DOMAIN` variable in your .env.
