### ISSUE TITLE
Upgrade Composer to version 2.0 in isle-buildkit

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora/documentation#1669]
Requires changing from the system provided composer to fetching and installing from a URL.

**Comment by alxp** [comment]
I've bumped a few versions of things and am working on a few PRs to upgrade required packages.

**Comment by nigelgbanks** [comment]
Almost ready for pull request from branch: https://github.com/nigelgbanks/isle-buildkit/tree/composer-2

Waiting on https://github.com/roblib/CrayFits/pull/4 to be merged.

Most of this work was lifted from @alxp work on the [playbook](https://github.com/Islandora-Devops/islandora-playbook/pull/193), and made possible by changes made to [crayfish](https://github.com/Islandora/Crayfish/pull/107).

**Comment by nigelgbanks** [comment]
Downstream consumers of this projects will have to run `composer update` and fix any issues that arise if they have not pinned themselves to a previous Docker image. Seems like we should probably sort out and start tagging the images appropriately with changes as we'll probably be ruining someones day.

**Comment by nigelgbanks** [comment]
`isle-buildkit` is currently using Composer 2.0.12
