### ISSUE TITLE
Frustration: Fedora URI doesn't show up until cache clear

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#1675]
So, this is more of a "this works in a not-great way" than anything, and maybe it's my bad for not reading the docs, which do state "Clearing cache may be necessary to refresh the node display."

But if i create a new repository item, the Fedora URI doesn't show up until I clear the cache (or re-save the node). Not even a "Fedora URI: Pending" or some other way of showing that the system is expecting there to be a fedora uri. 

As a result, i was baffled about why a content item, which was in Fedora, didn't get its URI displayed.  This is unintuitive and I thought something was broken.

**Comment by dannylamb** [comment]
I totally see that. I think we can force the pseudo field to have a default value of 'Pending', but then we'd still be subject to caching.  At least you'd see pending, tho.

If we want it to actually update appropriately without having to clear caches, we'll either need some cache wizardry in the pseudo field's code or we just make it a proper field. It would probably be way easier to make it a field with a default value of "Pending", and then when it actually gets set to the url, it will handle the caching.

**Comment by rosiel** [comment]
This is not an issue now that we've done away with Gemini.
