### ISSUE TITLE
Updates to Style Guide

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#1677]
Following some discussion at the November 4th DIG meeting, I am proposing the following changes to the Style Guide:

- A "last edited on DD-MM-YYYY" line to the end of each documentation page  — or the begging? where do folks think it would be more useful? We could use `<sub><sup>sup and sub text</sup></sub>` to make it <sub><sup>super tiny and less obtrusive</sup></sub> if it goes at the top. 

- A standard "callout" and emjoi for calling attention to when Islandora practice differs from standard Drupal. As an example, we have a [Managing Users](https://islandora.github.io/documentation/user-documentation/users/) page that is almost entirely vanilla Drupal, but the fedoraAdmin role is a special, Islandora-only thing, that people who are already comfortable in Drupal need to know about, even if they don't need a tutorial on the entire user management interface. This new callout would make for a standard "info box" calling out the Islandora-only thing for documentation users to scan for. It will appear as the _themeless_ example from [here](https://rdmd.readme.io/docs/callouts). We can use any emoji, but I'm partial to ✨   :beach_umbrella:  (for the Island) or, of course :lobster:

We can also have a standard call out for "Learn More" style information, where we are giving the basics in our docs, but linking out to either a more detailed page in our own docs or somewhere else on the web that goes into more depth.

**Comment by seth-shaw-unlv** [comment]
For dates, either top or bottom works for me but _please_ don't use the [sub](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub)/[sup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup) formatting; leave it full size:

> The `<sub>` element should be used only for typographical reasons—that is, to change the position of the text to comply with typographical conventions or standards, rather than solely for presentation or appearance purposes.

For the icon, 🦞  or ✨.

**Comment by manez** [comment]
Oh, all right. No torturing the markup for tiny text 


I'll get a PR ready for the style guide. Just need a few more votes on whether we sparkle or lobster.

**Comment by manez** [comment]
https://islandora.github.io/documentation/contributing/docs_style_guide/ all done!
