### ISSUE TITLE
islandora_breadcrumbs should have an uninstall function to remove config

### ISSUE THREAD

**Issue by wgilling** [Islandora/documentation#1707]
When using drush to enable the islandora_breadcrumbs module if it has been previously installed / uninstalled, the reenabling step islandora_breadcrumbs throws an error.

The output of the error is:
```
$ drush pm-enable islandora_breadcrumbs

In PreExistingConfigException.php line 65:
                                                                                                                         
  Configuration objects (islandora.breadcrumbs) provided by islandora_breadcrumbs already exist in active configuration  
                                                                                                                         
```

**Comment by alxp** [comment]
In the yml file you can  set your custom module as a dependency in your YML file by setting "enforced" under dependencies.

For example:

```yaml
dependencies:
  module:
    - node
  enforced:
    module:
      - custom_module
```

**Comment by wgilling** [comment]
I have tried as many variants of this as I can think of and none of it works.

Here is the current islandora_breadcrumbs.info.yml file:
```
name: 'Islandora Breadcrumbs'
type: module
description: 'Builds breadcrumbs based on field_member_of relationships.'
core: 8.x
package: Islandora
dependencies:
  - islandora
```

I edited it to this and then tried to uninstall / reinstall yet still get slightly different errors and this does not remove the config settings.
```
name: 'Islandora Breadcrumbs'
type: module
description: 'Builds breadcrumbs based on field_member_of relationships.'
core: 8.x
package: Islandora
dependencies:
  module:
    - islandora
  enforced:
    module:
      - islandora_breadcrumbs
```

The errors that this results in are:
```
$ drush pm-uninstall islandora_breadcrumbs
 [warning] strpos() expects parameter 1 to be string, array given Dependency.php:181
 [warning] explode() expects parameter 2 to be string, array given Dependency.php:182
 [warning] strpos() expects parameter 1 to be string, array given Dependency.php:181
 [warning] explode() expects parameter 2 to be string, array given Dependency.php:182
 [success] Successfully uninstalled: islandora_breadcrumbs
```

**Comment by alxp** [comment]
The enforced dependencies bit needs to be in each config yml file in the /config/install folder.

**Comment by wgilling** [comment]
Thanks again @alxp !!!  I have it working now and have made a pull request for it against the 8.x-1.x branch.

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/d76a6644c919acaa48d59d862a4fc6e8a279be2d.
