### ISSUE TITLE
Update isle-dc README with sprint changes

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1712]
- URLs have changed
- Add quickstart section
- Update changing domain section
- Add stub sections for
    - Demo
    - Local
    - Remote
- Add info on transitioning between local, and remote

**Comment by rosiel** [comment]
If it impacts the documentation, please also edit: https://islandora.github.io/documentation/installation/docker-compose/

**Comment by g7morris** [comment]
@rosiel Just merged https://github.com/Islandora/documentation/pull/1720 per your great changes and was reviewing the newly updated page https://islandora.github.io/documentation/installation/docker-compose/ Maybe it is a cache thing for me but does look like that screenshot still has the old url? How should we fix that? Is that something you can grab and update?
