### ISSUE TITLE
Got tripped up by trying to add a Media entity reference field, accidentally added Typed Relation field

### ISSUE THREAD

**Issue by antbrown** [Islandora/documentation#1715]
Hi, 

I'm seeing some extra fields on the "Add Field" form which looks like they're coming from controlled_access_terms, but a quick scan of the code base doesn't show anything.

Here's how I got confused:

1. /admin/structure/types/manage/<my_content_type>/fields/add-field
1. In the Select list, I selected "Media" under the General group
1. On the next screen, the field settings, it was asking me to fill out "Available Relations", I entered "none" and clicked Save.
1. Now under the field list the new field appears as a "Typed Relation" field, not "Media"

It turns out I was supposed to select the "Media" field under the Entity Reference group, the confusing part was that these extra fields appear under the General group:

```html
<option value="field_ui:typed_relation:node">Content</option>
<option value="field_ui:typed_relation:media">Media</option>
<option value="field_ui:typed_relation:taxonomy_term">Taxonomy term</option>
<option value="field_ui:typed_relation:user">User</option>
```

As my colleague @kayakr points out, it looks like something is adding a Typed Relation field type for each core content type and it would be useful if these were differentiated by adding something like "Media (Typed Relation)".

I've tried to step through with a debugger to see where these field types are being discovered, I got a bit lost, but I think it has something to do with the discovery steps around:

[web/core/modules/field_ui/src/Form/FieldStorageAddForm.php:149](https://git.drupalcode.org/project/drupal/-/blob/8.9.9/core/modules/field_ui/src/Form/FieldStorageAddForm.php#L149)

Let me know if there's any further info I can provide? Please accept my apologies if this is not a controlled_access_terms issue.

Cheers,
Ant

**Comment by elizoller** [comment]
Hi @antbrown, I have many times accidentally created typed relation fields when I meant to create a regular entity reference field. I didn't easily see a way to change the label but if someone else knows of a way to do that, please feel free to put in a PR. Instead, I just separated the typed relation into its own category of field. See the PR above and it's attached screenshot.

**Comment by antbrown** [comment]
@elizoller this is perfect, thank you! I applied the patch, did a cache rebuild and now Typed Relations appear under their own category... no more confusion :)

**Comment by antbrown** [comment]
@elizoller do I close this issue now, or leave for maintainers?

**Comment by elizoller** [comment]
We'll leave the issue for now. A committer will need to "review" and "merge" the above PR and then this ticket can be closed. But it definitely helps that you tested it! Thanks for having a look and thanks for submitting the issue to begin with.

**Comment by rosiel** [comment]
resolved with https://github.com/Islandora/controlled_access_terms/pull/60
