### ISSUE TITLE
Documentation Landing Page's Menu Shows only "About" Documentation

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1718]
This is confusing and makes it look like the documentation is really small.  If you click on the hamburger menu and then the left arrow, which looks more like it would make your menu disappear, you can get to the TOC. So it's there, but you have to know.

Ideally, the landing page to the documentation has a hamburger menu that is the TOC.

**Comment by rosiel** [comment]
We came to the agreement that the front page should not be within a "section".

**Comment by rosiel** [comment]
Solved by #1719
