### ISSUE TITLE
Remove dependency on libraries in openseadragon

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1732]
Openseadragon depends on `libraries`, but that's not Drupal 9 ready yet.  Since we load our js library from a CDN using core drupal libraries stuff (which doesn't need the contrib module), we can most likely jettison it.  The hardest part will be testing this on D9.

**Comment by jordandukart** [comment]
Isn't this duplicated by https://github.com/Islandora/documentation/issues/1729?
