### ISSUE TITLE
Carapace is not D9 ready

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1733]
It depends on Adaptivetheme, which looks like it's not going to be D9 ready.  If we want to go with D9 quickly, since no core functionality relies on it, we should ship with Olivero and Claro (the new Drupal default themes), until we sort out what to do with a community theme.

To accomplish this, we'll need to remove carapace from any composer.json that requires it and also update the config in `config/optional` in `islandora_defaults` to use the standard D9 themes.

**Comment by alxp** [comment]
+1 for Claro which has many accessibility improvements over Seven as an admin theme.

**Comment by dflitner** [comment]
Not saying that we should continue with Adaptive Theme since I'm not confident in its continued viability but someone forked it since the original maintainer has gone AWOL. https://www.drupal.org/project/at_theme.

I agree that a sub-theme or config on Olivero is a good way to go until/if we pick a new base theme.

**Comment by seth-shaw-unlv** [comment]
I know there is a lot of love for Olivero and Claro, but Bartik and Seven _are_ still the default themes enabled on a stock Drupal 9 Standard Profile install. Should we shift our defaults to Bartik and Seven (in line with the current Drupal defaults) or should we be explicitly setting Olivero and Claro as the default themes in our build tools (playbook and isle)?

**Comment by seth-shaw-unlv** [comment]
E.g. for the playbook we would either drop [this section](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/roles/internal/webserver-app/tasks/drupal.yml#L28-L45) to get bartik, or update it to set Olivero.

For isle-dc, 🤷‍♂️. Presumably we need a new image on dockerhub? I'm not seeing anywhere to set this in the isle-dc github repo.

**Comment by manez** [comment]
For Olivero and Claro, they still just "future defaults" based on Drupal Strategic Initiatives for a new admin them (https://www.drupal.org/about/strategic-initiatives/admin-ui-js) and base theme (https://www.drupal.org/about/strategic-initiatives/olivero), and I don't think we want to get too far ahead of the curve on adopting something that Drupal hasn't made official yet, but the focus on accessibility in both themes is _really_ appealing.

**Comment by elizoller** [comment]
https://github.com/Islandora/carapace/pull/25 with copied work from https://github.com/Islandora/carapace/pull/24 thanks @nigelgbanks ! gives us carapace support by depending on a d9 ready fork of adaptive theme
although it may not be the default theme anymore, this support at least allows sites using carapace to keep up to date and run on d9
