### ISSUE TITLE
Document how to add a facet on vocabulary reference fields

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1739]
Here are step-wise instructions for adding a facet on a vocabulary reference field. After a search, a block containing the configured facets appears letting the user filter their search.

## Step 1

Steps 1 and 2 add the field to the Solr index.

1. Go to Admin  > Configuration/Search and metadata/Search API
1. Edit the "Default Solr content index"
1. Open the "Configure the Taxonomy term datasource" fieldset, choose the vocabulary bundles you want to add to be indexed
1. Click Save

## Step 2
1. Back at the edit "Default Solr content index", choose "Fields" from the tabs across the top
1. Click on the "Add fields" button
1. Scroll down to "Content"
   1. Click on the + next to the field you want to add.
   1. Click on the + next to "Taxonomy term". A bunch of subfields will appear.     
   1. Look for the field that contains "YOUR_FIELD:entity:name" and click on the "Add" button at the end of the bulleted point.
   1. Click “Done.”
1. Find your newly added fields In the list, change the "Type" of the new field to "string" if needed
1. If the "Machine name" of the new field is generic, like "name_1", change it to be the same as the part of the "Property path" up to the first : (this will be the same as the field's machine name).
1. Click on the "Save changes" button.

## Step 3
Now that you've added the field, you need to rebuild your Solr index. 
1. Go back to "Default Solr content index" (admin/config/search/search-api/index/default_solr_index)
1. Click on the "Index now" button.

## Step 4
Step 4 adds and configures the facet itself. 

1. Go to admin/config/search/facets
1. Click on the "Add facet" button
1. Select the "View Solr search content" source
1. In the Field list, select the field you added above
1. You can adjust the admin Name of the facet
1. Click "Save".
1. Choose your configuration options (for example, "List item label") 
1. Click Save.

## Step 5
This step adds the facets in a single block.

1. To place a Facets block for the facets you have created, go to admin/structure/block.  
1. Click ‘Place block’ in the desired block region, for example, Sidebar second.  
1. Start typing the facets block in the Filter and click ‘Place block’ 
1. Choose the facets to include
1. Choose other configuration options for the block, for example change the title that displays and restrict by content type, etc. 
1. Click Save.

Would https://github.com/Islandora/documentation/blob/main/docs/user-documentation/searching.md be the best place for this?

Thanks to @librarychik for testing and fleshing this out.

**Comment by eldonquijote** [comment]
@mjordan Melissa created a documentation page from the instructions in this issue ticket, but I have trouble reproducing the intended behavior in the public sandbox. Do you recall which Islandora/Drupal version you used when you wrote them, and which theme?

**Comment by rosiel** [comment]
I was able to recreate it with the playbook's "standard" installation. I'll put a note to that effect in the docs. 

It was almost the same in the install profile (loaded with ISLE), but it was a bit confusing because a LOT of facets had already been configured, and i had a hard time keeping track. Also, in the Install profile, the blocks are placed in the view itself not structure/blocks.

**Comment by rosiel** [comment]
https://islandora.github.io/documentation/user-documentation/facet_on_vocabulary_reference_fields/
