### ISSUE TITLE
islandora_fits not D9 ready

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1742]
While testing the new D9 islandora parts I stumbled across this error when attempting to view a FITS record: `Error: Call to undefined method Drupal\file\Entity\File::url() in Drupal\islandora_fits\Plugin\Field\FieldFormatter\FitsFormatter->viewValue() (line 79 of /var/www/html/drupal/web/modules/contrib/islandora_fits/src/Plugin/Field/FieldFormatter/FitsFormatter.php)`. [The url function was deprecated in D8 and was removed in D9](https://www.drupal.org/node/3019830).

We should update the offending line and check for any other deprecated code.

Tagging #1680 and @ajstanley.

**Comment by ajstanley** [comment]
An easy one-liner.  Change has been pushed and tested in 8 & 9

**Comment by seth-shaw-unlv** [comment]
Rebuilt the D9 site and all is well!
