### ISSUE TITLE
Islandora 8 Sandbox does not have taxonomy terms required for basic functionality

### ISSUE THREAD

**Issue by kspurgin** [Islandora/documentation#1749]
**Initial report**: 
I visited http://future.islandora.ca/admin/content

I first tried to add a new Repository Item using the "Add content" button. Then I tried editing the existing object at: http://future.islandora.ca/node/9

In both cases, when I get to the bottom of the metadata form, there is nothing in the dropdown for the System Model field, so I cannot set a value for that field. 

As that field is required, I cannot save the Item to create or update it.

**Then, several days later...**
I tried creating a node and adding a media file. The thumbnail for my media file didn't get updated. I noticed this was because the Islandora Media Use taxonomy is blank. 

I manually added "Original File" term to that taxonomy, edited the media to set my media's Media Use to Original File, but my thumbnail still was not updated. 

I deleted my initial Media and file, and re-added it as new Media, selecting Media Use = Original File in the creation step. A FITS file was created, but I got an error that Thumbnail Image and Service File terms did not exist, so I guess derivatives were not created. 

----

This is a really poor experience if I'm using the Sandbox to see the basics of how Islandora 8 works. Migration of the taxonomy terms required for basic functionality should be part of the build of the Sandbox.

**Comment by kspurgin** [comment]
This would appear to be because there are no terms in the Islandora Models taxonomy now: http://future.islandora.ca/admin/structure/taxonomy/manage/islandora_models/overview

**Comment by kspurgin** [comment]
I manually added Image to the Islandora Models taxonomy, and when I went back to the Worried Kitten at http://future.islandora.ca/node/9, it was automagically assigned the Image model and I was able to update it.

**Comment by kspurgin** [comment]
http://future.islandora.ca/node/30/ is also getting assigned the Image model which might be correct since it is a jpg, but also maybe it should be getting assigned the Page model since it is the page of a Book parent? 

Seems like the default taxonomy values are missing for some reason and need to be restored.

**Comment by kspurgin** [comment]
@dannylamb  -- is this by design, or an already known problem? 

Or does the sandbox get set up with the taxonomy terms but some helpful test person deletes them, which I guess we can't control?

I'm just thinking toward IMIG folks using the sandbox for the mapping verification sprint and running into weird problems trying to do stuff because of this.

**Comment by manez** [comment]
@kspurgin thats on old Danny github. He's at @dannylamb now 😄

**Comment by kspurgin** [comment]
I thought that looked weird! Thanks, @manez

**Comment by kspurgin** [comment]
@dannylamb redeployed the Sandbox and it now has all expected taxonomy terms, so we'll call this someone "helpfully" deleting the terms, and it's now (at least FOR NOW) fixed
