### ISSUE TITLE
drupal/vendor/islandora/chullo/src/IFedoraApi.php \EasyRdf\Graph Already In Use

### ISSUE THREAD

**Issue by jqi26** [Islandora/documentation#1759]
Getting the following warning in IFedoraApi.php:

_Warning: Cannot declare class \EasyRdf\Graph, because the name is already in use in require() (line 24 of /var/www/html/drupal/vendor/islandora/chullo/src/IFedoraApi.php)._

These lines of code seem to be the issue:

_if (class_exists('\EasyRdf_Graph')) {
    class_alias('\EasyRdf_Graph', ' \EasyRdf\Graph');
}_

**Comment by mjordan** [comment]
Can confirm that I am seeing this warning too when I do a `drush cr`.

**Comment by elizoller** [comment]
PR is up

**Comment by mjordan** [comment]
Merged, closing.
