### ISSUE TITLE
New repository item not posted to fedora

### ISSUE THREAD

**Issue by Tristaan** [Islandora/documentation#1760]
When I add a new repository item, the new item is not shown in fedora. On the other side I have a running isle-dc where the Fedora URI is created and displayed. But it wasn't there at the start so there is some kind of delay from creation to posting to fedora. But that delay is larger than a couple of hours, i think?

EDIT: The Content context which contains Repository item has the actions configured correctly (index node in Fedora). When applying the action manually it's not indexed.
 
So my question is how can I configure this delay? Where does it get stuck (note: the repo item is not in gemini either)? How can I debug this?

If you need more info please tell me which.

**Comment by dannylamb** [comment]
Hi @Tristaan,

The delay should be super small. Most of the time, people don't even realize there is a delay and think it's immediate.  What you're experiencing is the retry/fail logic in Alpaca taking its sweet time.  It will requeue and retry a bunch of times before eventually getting through or failing.

The delay between retries can be configured, but it's probably better to diagnose what is actually going on.  I'd start by checking the Milliner logs.  If you're using ISLE, try `docker logs -tf isle-dc_milliner_1` and let me know what you get.

**Comment by dannylamb** [comment]
@Tristaan Are you still stuck on this or have your issues been resolved?

**Comment by Tristaan** [comment]
Sometimes it works, sometimes it doesn't. Keep this issue open when some
thorough testing is done.

**Comment by kstapelfeldt** [comment]
Hi @Tristaan - we're undertaking a repo cleaning project, and have also made some code changes that may affect the behaviour you were seeing. If you can get this to reproduce, or find info out in the logs, can you re-open with additional details?
