### ISSUE TITLE
Document new Advanced Search module once merged

### ISSUE THREAD

**Issue by eldonquijote** [Islandora/documentation#1761]
https://github.com/Islandora/islandora/pull/824 proposes to add new Advanced Search Module to Islandora Core. 

Once approved and merged, the module's comprehensive readme information should be added to the documentation (https://github.com/nigelgbanks/islandora/tree/8.x-1.x-advanced-search/modules/islandora_advanced_search).

@Islandora/documentation

**Comment by mjordan** [comment]
Haven't taken a look but documentation on this module might make #1739 redundant.
