### ISSUE TITLE
Require confirmation to delete the media and files from a Repository Object node

### ISSUE THREAD

**Issue by kspurgin** [Islandora/documentation#1762]
If I click to the `Media` tab of a Repository Object node, the pre-selected/default Action is `Delete media and file(s)`.

If I have selected any files, and I click `Apply to selected items` for any reason (accidental or not) while on this page, my media and files are immediately deleted without asking me for any confirmation.

One fix would be to require affirmative confirmation before all media/files are deleted. 

Another might be to **not** have any action pre-selected in the drop-down, *especially* not the most destructive possible action option.

**Comment by mjordan** [comment]
Related issue - #1564.

**Comment by kayakr** [comment]
FWIW, if I visit Media tab of Repository Item on sandbox, there is no default action selected, see https://sandbox.islandora.ca/node/49/media

Also, if I select a media entity and action "Delete media and file(s)", and click "Apply to selected items" I get a confirmation form "Are you sure you want to delete this media and associated files?" with options "Delete" and "Cancel"
https://sandbox.islandora.ca/media/delete_with_files?destination=/node/49/media

I think this issue can closed?
