### ISSUE TITLE
Reduce number of watchdog entries

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1774]
The Drupal log has a lot of entries like this:

![image](https://user-images.githubusercontent.com/403918/110648981-0d08d380-816e-11eb-8627-aadd46c0b09e.png)

Any way to not log these? I assume the Gemini errors will go away once Gemini is removed, but the 404s for media don't seem to indicate a problem. Can we figure out what's triggering them and not log them?

**Comment by mjordan** [comment]
I'll try to figure out what's triggering the 404s on media. Might be from Workbench (in which case I'll fix), since I run it frequently.

**Comment by seth-shaw-unlv** [comment]
Those 404's aren't just workbench. I've seen them pop up a time or two. Also, I don't think the Gemini entries are errors, just verbose "this is what is happening" messages. Ergo, no warning or error symbol next to them.

**Comment by mjordan** [comment]
2021-03-17 Tech Call: The Gemini entries will be/are gone, and the 404s on media are due to the attempts by external microservices doing their normal asynchronous thing.

So, closing.
