### ISSUE TITLE
can't install islandora defaults

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#1785]
When on a build of Isle (supported build mechanism, yes?) i was surprised to find islandora defaults not installed. however, i need to be able to upload .tif's into paged content, so thought i'd install it.

```
rosies-MacBook-Pro-2:codebase [git:development] rlefaive$ composer require islandora/islandora_defaults -W
Using version ^1.1 for islandora/islandora_defaults
./composer.json has been updated
Running composer update islandora/islandora_defaults --with-all-dependencies
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - islandora/islandora_defaults 1.1.0 requires islandora/islandora 1.1.0 -> found islandora/islandora[1.1.0] but it conflicts with your root composer.json require (dev-8.x-1.x).
    - islandora/islandora_defaults 1.1.1 requires islandora/islandora 1.1.1 -> found islandora/islandora[1.1.1] but it conflicts with your root composer.json require (dev-8.x-1.x).
    - Root composer.json requires islandora/islandora_defaults ^1.1 -> satisfiable by islandora/islandora_defaults[1.1.0, 1.1.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

you may notice that I _did_ use -W in my attempt to install it. 

Something's wrong if I can't require it.

**Comment by DiegoPino** [comment]
Hi @rosiel, I do not know too much about I8 versioning or which branches are stable but looking around it seems that `1.1.0` has a strict dependency in its module composer.json to the matching Islandora version, but https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/composer.json is the current live (looking at commit dates) and matches this `Isle` deployment's project level composer.json, so ... maybe  (really maybe)

`composer require islandora/islandora_defaults:dev-8.x-1.x -W` should at least clear the dependencies issue, but again, not sure if other than general composer issue,  if dev-8.x-1. is stable or the one you actually want to use to.

Hope this helps. I'm really lurking

**Comment by rosiel** [comment]
:D That almost worked - it seems Islandora Defaults depends on `pdf` but that wasn't part of what Composer installed for it. 

Thank you 1 million x for `composer require islandora/islandora_defaults:dev-8.x-1.x -W `. 

(edit: and `composer require pdf` successfully got pdf around so that I could whitescreen after enabling Islandora Defaults)

(edit 2: the whitescreen was because i'd accidentally already defined a field in my custom content type called field_description and the storage type was different. I'm going to pay for this later I'm sure, but for now things seem okay)

**Comment by rosiel** [comment]
There's gonna be some documentation about what is/isn't possible with these variations, so this ticket's remaining open for that.

**Comment by rosiel** [comment]
The pdf module dependency was added in https://github.com/Islandora/islandora_defaults/pull/49.

Since the semantic versioning shift, islandora and islandora_defaults are no longer version-locked and `composer require` should find a compatible version.
