### ISSUE TITLE
OpenSeadragon viewer does not display for Anonymous on Drupal 9

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1788]
PR: https://github.com/Islandora/openseadragon/pull/35

## Steps to reproduce:

On Fresh Drupal 9 Islandora install (using playbook in our case)

1. Create a Repository Object and select Image for the Model and Resource Type, and 2. OpenSeadragon for the display hint.
3. Add a Media of type Image.
4. Log out and view the object node. 

### Expected Behaviour

The user should see the OpenSeadragon viewer.

### Actual behaviour

No viewer is displayed.

The drupal/core library is now explicitly required if the Drupal object is accessed by a module when user is Anonymous.

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/openseadragon/commit/0fd1218f929cb4fd1537f52647f35f4248ce0fc0.
