### ISSUE TITLE
Update playbook to Ubuntu 20.04 Focal64

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1792]
These are the pull requests that together comprise an update to run the Playbook on Ubuntu 20.04 Focal64:

Playbook: https://github.com/Islandora-Devops/islandora-playbook/pull/198

Roles:

Tomcat8: https://github.com/Islandora-Devops/ansible-role-tomcat8/pull/15
Fcrepo: https://github.com/Islandora-Devops/ansible-role-fcrepo/pull/13
Blazegraph: https://github.com/Islandora-Devops/ansible-role-blazegraph/pull/12
Grok: https://github.com/Islandora-Devops/ansible-role-grok/pull/11
Fits: https://github.com/Islandora-Devops/ansible-role-fits/pull/9
Fcrepo-syn: https://github.com/Islandora-Devops/ansible-role-fcrepo-syn/pull/11

**Comment by elizoller** [comment]
@alxp these all look merged - can it be closed?

**Comment by alxp** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
