### ISSUE TITLE
"Hacking on Islandora" page is outdated

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1794]
We've received a request for "plain language documentation", and this page was surfaced.  Turns out to be waaaaay back from the 7.x-2.x days.

**Comment by dannylamb** [comment]
It's riddled with elusive `CLAW`s, too.

**Comment by manez** [comment]
Is there anything in there worth preserving?

**Comment by dannylamb** [comment]
Not really.  This page covers similar ground better: https://islandora.github.io/documentation/#try-islandora
