### ISSUE TITLE
Replace Travis with Github Actions where applicable

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1798]
We've taken the plunge with the main islandora module, and things have run pretty smoothly.  We should follow suit where applicable and convert out existing Travis ymls into Github Actions.

See https://github.com/Islandora/islandora/blob/8.x-1.x/.github/workflows/build-8.x-1.x.yml for an example.  It's actually the most complicated of setups we'll require, so adapting this to other repos should be an exercise in trimming the matrix back down.

**Comment by elizoller** [comment]
carapace done with https://github.com/Islandora/carapace/pull/25

**Comment by elizoller** [comment]
i may have gotten to all of them?

**Comment by elizoller** [comment]
they are all merged! @dannylamb maybe can be closed?
