### ISSUE TITLE
In media migrate, error "Call to function getMimeType() on null.

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1825]
If a media's source file isn't loading properly, a PHP error occurs and the migrate process halts.

In src/Plugin/Condition/MediaSourceHasMimetype.php:

```
      if ($mid) {
        $source = $entity->getSource();
        if ($source) {
          $source_file = File::load($source->getSourceFieldValue($entity));
          if (!empty($source_file) && $this->configuration['mimetype'] == $source_file->getMimeType()) {
            return TRUE;
          }
        }

```

Add a check to $source_file to make sure it is not null before calling the function.

**Comment by seth-shaw-unlv** [comment]
We actually do something very similar in the [MediaHasMimetype condition](https://github.com/Islandora/islandora/blob/8.x-1.x/src/Plugin/Condition/MediaHasMimetype.php#L153-L156):
```
        $file = $this->mediaSource->getSourceFile($medium);
        if ($file && in_array($file->getMimeType(), $mimetypes)) {
          return TRUE;
        }
```

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora/commit/cf82e8f392c081221781fd568cfc11d1bde7fd87
