### ISSUE TITLE
Add option to ignore undated ("XXXX") and open-ended dated EDTF values in the search index

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1852]
The existing EDTF year index support currently builds an array of integer values to populate the index. By default this means that anything undated ("XXXX") results in the year "0", anything with an open beginning will go from 0 to the end year, and anything with an open end date will go from the beginning year until the current one. A site _can_ set a default open and end year for the index but undated will still be year 0 which makes a terribly unwieldy slider facet widget that tries to accommodate over 2021 values....

We would like to filter out undated values and simply ignore the open date values. E.g. "../1984" or "1984/.." simply becomes "1984" in the index.

**Comment by kspurgin** [comment]
Ignoring XXXX for indexing seems fine to me. 

Indexing `../1984` as 1984 also seems fine.

Seems like `1984/..` should index as 1984 to current year? Since generally something with a date like this is actively still being published

**Comment by seth-shaw-unlv** [comment]
Summary from the [Tech Call](https://github.com/Islandora/documentation/wiki/Jun-23%2C-2021): Yes make these configurable; also, make ignoring open beginning and open end separately configurable. Everyone seems fine with pushing the PHP requirements to 7.4 so we can use the Professional-Wiki EDTF library.

**Comment by seth-shaw-unlv** [comment]
Resolved by https://github.com/Islandora/controlled_access_terms/pull/70
