### ISSUE TITLE
GitHub IO pages are broken

### ISSUE THREAD

**Issue by misilot** [Islandora/documentation#1853]
Something is up with the GitHub IO site.

For example https://islandora.github.io/documentation/technical-documentation/rest-create/ does not work but https://islandora.github.io/documentation/technical-documentation/rest-create.html does.

Google is also indexed with the clean url's so they are broken.

Also, https://islandora.github.io/ returns a 404.

I can come up with more examples if you need them.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/documentation/commit/76c93f5505da5d87ac532567918513c62735152c
