### ISSUE TITLE
Islandora Defaults not running migration called "Tags migration for islandora_defaults feature"

### ISSUE THREAD

**Issue by joshdentremont** [Islandora/documentation#1862]
When installing Islandora Defaults it creates a migration called "Tags migration for islandora_defaults feature" but it doesn't seem to execute this migration automatically. It works fine when I execute it manually, but until you do that the OpenSeadragon and PDFjs contexts do not work (and give an error when you try to edit them) and you are unable to use the OpenSeadragon and PDFjs viewers because of this. 

You should be able to reproduce this by running "make local" with isle-dc and then installing Islandora Defaults. Here are my required modules in composer.json for reference:
"require": {
        "composer/installers": "^1.9",
        "drupal/core-composer-scaffold": "^9.2",
        "drupal/core-project-message": "^9.2",
        "drupal/core-recommended": "^9.2",
        "drupal/search_api_solr": "^4",
        "drush/drush": "^10.3",
        "islandora/carapace": "dev-8.x-3.x",
        "islandora/islandora": "dev-8.x-1.x",
        "islandora/islandora_defaults": "dev-8.x-1.x"
    },

**Comment by rosiel** [comment]
This should at very least be in the README: https://github.com/Islandora/islandora_defaults

**Comment by rosiel** [comment]
Closing this issue as we have replaced Islandora Defaults with the [Islandora Starter Site](https://github.com/Islandora/islandora-starter-site/#usage). 

With the Starter Site, the migrations (including the Tags migration) are run by all of our provisioners, and running the migrations is listed as well in the manual install instructions under [# 6: Usage](https://github.com/Islandora/islandora-starter-site/#usage)
