### ISSUE TITLE
ISLE's built-in IDE only works with `make demo`

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1865]
Setting `INCLUDE_CODE_SERVER_SERVICE=true` before running `make local` will bring up an IDE at port 8443, but it won't be able to find any code, just a very very empty looking Drupal site with no `composer.json` or modules directory.

It works fine with `make demo`, but since `make local` is meant for developing, it should definitely work with that too.

**Comment by joecorall** [comment]
`make local` has been removed from isle-dc. Closing this issue

```
$ make local
make local has been removed. To create a development site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
