### ISSUE TITLE
Audio files that have no tracks throw an error on media page

### ISSUE THREAD

**Issue by wgilling** [Islandora/documentation#1871]
For items' media that are set to use the audio media type -- and the uploaded mp3 file entity has no tracks information, the media page for it throws a (Chrome | Inspect | Console) javascript console error:
```
drupal.js?v=9.2.0:16 Uncaught TypeError: Cannot set property 'oncuechange' of undefined
    at init (audio.js?v=1.x:24)
    at Object.attach (audio.js?v=1.x:37)
    at drupal.js?v=9.2.0:27
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (drupal.js?v=9.2.0:24)
    at drupal.init.js?v=9.2.0:29
    at HTMLDocument.listener (drupal.init.js?v=9.2.0:17)
```

_**NOTE:** The Format for the audio file must also be set to "Audio with Captions" for either Source or Default http://localhost:8000/admin/structure/media/manage/audio/display or http://localhost:8000/admin/structure/media/manage/audio/display/source... otherwise the audio.js file is not attached via the twig template._

This can be addressed in the islandora/modules/islandora_audio/js/audio.js file by checking that the textTracks exists before trying to set HTML for each currentCue it might have.

**Comment by wgilling** [comment]
added additional info to specify the exact configuration that causes this error to happen.

**Comment by elizoller** [comment]
fix was merged
