### ISSUE TITLE
Documentation: "Build and install with Docker" link throws a 404 error

### ISSUE THREAD

**Issue by fruviad** [Islandora/documentation#1877]
Bad link: https://islandora.github.io/documentation/installation/docker-compose/

Page containing the bad link:  https://islandora.ca/download

Bad link is for "Build and install" in the following block of text, with the larger block of text added for context:

Islandora 8
Current Version: 1.1.0

_Build and install_ with Docker

**Comment by manez** [comment]
Fixed the link (and a couple of other problems on that page). Thanks for reporting this, @fruviad !
