### ISSUE TITLE
Playbook: Delete 'main' branch and make 'dev' the default

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1881]
We have never had a clear message of how stuff goes from 'dev' to 'main' and it has cause many people to run an old playbook.

Propose just pointing main to the current state of dev and then deleting dev.

**Comment by mjordan** [comment]
@alxp will remove main and make dev the default. Also send out a message indicating that we've done that.

**Comment by alxp** [comment]
Removed branch protection rule, reviewed dangling commits, did not find any that needed to be merged to dev. 'main' branch has been deleted.

rip.
