### ISSUE TITLE
islandora_core_feature_update_8001() fails due to duplicate index entry

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1888]
`islandora_core_feature_update_8001()` changes structure of `media__field_file_size` table, by copying field values to a temporary table then moving them back. During the copy back, an error occurred:
```
[notice] Update started: islandora_core_feature_update_8001
[error]  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1577-0-0-en' for key 'PRIMARY': INSERT INTO {media__field_file_size} SELECT o.*
 FROM
 {media__field_file_size_o} o
 ORDER BY o.entity_id ASC, o.revision_id ASC, o.delta ASC
 LIMIT 1500 OFFSET 1000; Array
 (
 )
[error]  Update failed: islandora_core_feature_update_8001 
[error]  Update aborted by: islandora_core_feature_update_8001 
[error]  Finished performing updates. 
```
The table has an index based on entity_id-deleted-delta-langcode.

I'm considering workarounds, e.g. drop index and reinstate it after update hook runs. Or change update hook to copy values row-by-row checking for duplicates.

/ @seth-shaw-unlv

**Comment by seth-shaw-unlv** [comment]
I'm not able to work on this and the other [related ticket](https://github.com/Islandora/documentation/issues/1886) right now. But if you come up with a PR I'm happy to test.

**Comment by kayakr** [comment]
@seth-shaw-unlv For the moment I just wanted to mention it to see if others have encountered it. It's happened on two environments for the same site so far. I'll see if I can devise a repair process.

**Comment by kayakr** [comment]
Ok, repaired `media__field_file_size` table using
`drush sqlq "INSERT INTO media__field_file_size (bundle,deleted,entity_id,revision_id,langcode,delta,field_file_size_value) SELECT bundle,deleted,entity_id,revision_id,langcode,delta,field_file_size_value FROM media__field_file_size_o WHERE (CONCAT(entity_id,\"-\",revision_id) NOT IN (SELECT CONCAT(entity_id,\"-\",revision_id) FROM media__field_file_size))"`
to copy rows from the temporary `media__field_file_size_o` table back to `media__field_file_size` where they were missing (based merely on entity_id-revision_id composite key).

`drush sqlq "SELECT COUNT(*) from media__field_file_size"`
19669

`drush sqlq "SELECT COUNT(*) from media__field_file_size_o"`
19667

/cc @seth-shaw-unlv
