### ISSUE TITLE
Code task: Deprecate islandora/drupal-project

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#1902]
We have a languishing fork of drupal-composer/drupal-project, here: https://github.com/Islandora/drupal-project/

We created it for the playbook, but haven't used it since [this commit](https://github.com/Islandora-Devops/islandora-playbook/commit/7cd01da9c30377fb1f278598ba04fedd77e18f7d) in November of 2020.

Can we deprecate/remove this repository? Move it to [islandora-deprecated](https://github.com/islandora-deprecated)?

(Came up during discussions of applying semver branches to all repos.)

**Comment by alxp** [comment]
Yes, the model I was following, to use an outer shell project that could use a drupal profile via composer require does not seem to carry any special advantage, and the model I was following, Acquia Lightning, is now being deprecated.

**Comment by kstapelfeldt** [comment]
@manez to move to  islandora-deprecated and close the ticket (or report back if she no longer has permissions)

**Comment by manez** [comment]
It is done! https://github.com/islandora-deprecated/drupal-project
