### ISSUE TITLE
Use GitHub Actions to compile Islandora documentation instead of Travis

### ISSUE THREAD

**Issue by eldonquijote** [Islandora/documentation#1914]
Islandora documentation is maintained using Markdown files, which are compiled by MkDocs (https://www.mkdocs.org/) to create static HTML documents. Compilation of the HTML documents is triggered by merging a PR against the Islandora/documentation repository. The compilation currently uses Travis CI to run the MkDocs Python. 

Most Islandora repositories have started using Github Actions instead of Travis CI. The DIG would like to follow suit for the documentation repository, to remove the external dependency. 

Desired outcome:
* Static documentation pages are generated using MkDocs run by a Github Action 
* Dependencies to Travis CI are removed

**Comment by adam-vessey** [comment]
With #2212 being merged, has this been addressed?
