### ISSUE TITLE
References to old field_alternative_title persist in islandora_defaults

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1980]
The MIG updates represented by the change between islandora_defaults 1.1.1 and 2.0 include renaming field_alternative_title to field_alt_title. However, some [lingering references to field_alternative_title persist](https://github.com/Islandora/islandora_defaults/search?q=field_alternative_title).

**Comment by elizoller** [comment]
fixed by @kspurgin with https://github.com/Islandora/islandora_defaults/pull/59
