### ISSUE TITLE
Remove "Fedora-based" from Islandora Github repository description?

### ISSUE THREAD

**Issue by kspurgin** [Islandora/documentation#1991]
![image](https://user-images.githubusercontent.com/450570/144292591-520556f2-9319-486f-b5b1-a85b30f72c8f.png)

Given that it is optional to use Fedora in the stack, should "Fedora-based" be removed from that description?

If I were opposed to running Fedora for some reason, and didn't know better, I might rule Islandora out based on that description.

**Comment by kspurgin** [comment]
Of possible relevance: Here is how [the documentation](https://islandora.github.io/documentation/) describes Islandora: 

"Islandora is an open-source framework that provides the necessary tools to use a Drupal website as a fully-functional Digital Assets Management System."

**Comment by rosiel** [comment]
Done.
