### ISSUE TITLE
Bad IIIF server address shows whitescreen.

### ISSUE THREAD

**Issue by ajstanley** [Islandora/documentation#1992]
If you enter a non-working IIIF Image server location from admin/config/islandora/iiif you'll whitescreen.

**Comment by ajstanley** [comment]
FWIW - It passed coder on my machine.

vagrant@islandora8:/var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_iiif/src/Form$ coder IslandoraIIIFConfigForm.php 
vagrant@islandora8:/var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_iiif/src/Form$

**Comment by seth-shaw-unlv** [comment]
We'll run with it.

**Comment by seth-shaw-unlv** [comment]
Fixed with https://github.com/Islandora/islandora/commit/4f45cb8c06df9da096260a6a449bec6f494cc65d.
