### ISSUE TITLE
Migrate Tools update broke our CI

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1994]
[Two weeks ago the Migrate Tools dev branch removed support for Drupal 8](https://git.drupalcode.org/project/migrate_tools/-/commit/9bc6966b6204eef9353e5a3b9d8b038d04a50684). Our [testing matrix still includes testing on Drupal 8](https://github.com/Islandora/islandora/blob/2.x/.github/workflows/build-2.x.yml#L26) which now fails. See @ajstanley 's [recent PR](https://github.com/Islandora/islandora/pull/857#issuecomment-984792000) [build failure](https://github.com/Islandora/islandora/runs/4389028529?check_suite_focus=true#step:10:21).

So, we can either drop Drupal 8 support in our testing matrix OR lock down [Migrate Tools in our composer](https://github.com/Islandora/islandora/blob/2.x/composer.json#L27) to `5.0` rather than `^5`.

Do we have a preference between these two, @Islandora/8-x-committers?

**Comment by whikloj** [comment]
If we are not dropping support for Drupal 8, then I vote for locking it for the time being.

**Comment by seth-shaw-unlv** [comment]
There are several committers on the Sprint Call right now that vote for dropping D8 from the testing matrix since it is EOL anyway.

**Comment by dflitner** [comment]
I agree that we should drop D8 since it's EOL. 

I don't know how much it might be used in the Islandora community so do we need to lock it for now and phase it out with an announcement? I think it could be a fairly short phase out period but if folks don't think that's needed then yes we should just get rid of it.

**Comment by rosiel** [comment]
I'm for we drop D8.

**Comment by seth-shaw-unlv** [comment]
So, if we drop D8, is that a major version change, even though _our_ API didn't change? Or something else?

**Comment by bseeger** [comment]
I'm for dropping 8 and for a major version change - is this just for the islandora module (for starters)?

**Comment by seth-shaw-unlv** [comment]
Bringing over observations made in a Slack thread:

> Although, is there a reason why we have to include migrate-tools? Would this better be placed in an install profile?
> Yes, we use the Migrate API to pull [islandora model terms] in, but that is part of an installation process, not _how the code works_. Migrate-tools is simply a useful tool for using the Migrate API.

So, we could just remove the dependency from islandora's composer and info.yml, relying instead on deployment methods to include it.

**Comment by seth-shaw-unlv** [comment]
> @bseeger: I'm for dropping 8 and for a major version change - is this just for the islandora module (for starters)?

Yes, only islandora would _need_ to be 3.0. However, modules that include islandora as a dependency would also have to update their composer to be `islandora/islandora:^2 || ^3` **or** drop D8 themselves and shift their major versions as well.

**Comment by seth-shaw-unlv** [comment]
Building on my earlier comment about the third option, removing migrate_tools as an islandora dependency, I made PR 859 (linked above). It appears that this fixes the CI for the islandora module.

However, this puts the onus on deployment methods (e.g. ansible and isle) to install and enable migrate_tools themselves _if_ they use a Drush version less than 10.4. 

I know the [playbook uses Geerling Guy's drush role](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/webserver.yml#L21) which is [configured to use Drush 9](https://github.com/geerlingguy/ansible-role-drush/blob/master/defaults/main.yml#L11), so it would either need to override the Geerling Guy config _or_ add migrate_tools to the [drupal_composer_dependencies config](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/inventory/vagrant/group_vars/webserver/drupal.yml#L6) and [drupal_enable_modules config](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/inventory/vagrant/group_vars/webserver/drupal.yml#L36).

It looks like, for isle, ~we would just need to update the composer.json for the islandora_install_profile_demo which is [currently set to use Drush 9](https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/main/composer.json#L96) as well. Someone correct me if I'm wrong on that.~ _Edit: I just spun up a fresh `make local` and it is giving me Drush 10.3.6. I'm guessing that is because we don't preemptively install Drush and composer respected the request for migrate tools conflicting with later Drush versions._

Oh, side-note: it appears that simply dropping D8 from the matrix won't help us without locking down composer in the CI to Drush < 10.4 because, even with D9, migrate_tools ^5 will still conflict with Drush 10.6, which the CI is grabbing before checking any other composer requirements and currently isn't us letting us downgrade Drush.

**Comment by alxp** [comment]
The Drush GeerlingGuy role may default to version 9 but it is overridden in the Playbook or the Drupal install itself is hosting Drush in its own structure, which the Drush launcher is happily running.

```bash
vagrant@islandora8:/var/www/html/drupal/web/sites/default$ drush --version
Drush Launcher Version: 0.6.0
Drush Commandline Tool 10.6.1
```

This is in the install-profile branch, so it should be merged to dev soon.

**Comment by seth-shaw-unlv** [comment]
@alxp, is that with the current dev branch or the new install-profile one?

**Comment by alxp** [comment]
The new one, there was some conflict that prevented an update to Drupal 9 if Drush 9 was pegged.

**Comment by seth-shaw-unlv** [comment]
Looks like the [dev branch is also asking for 10.3+](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/inventory/vagrant/group_vars/webserver/drupal.yml#L10).

**Comment by seth-shaw-unlv** [comment]
Fixed with https://github.com/Islandora/islandora/commit/90d67951727452896b2a281337b8fab6485ff237.
