### ISSUE TITLE
New EDTF formatting issues

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#2016]
While testing out @Natkeeran 's newspaper fixes I came across some issues with the [recent "do not show" options for controlled_access_terms](https://github.com/Islandora/controlled_access_terms/pull/75).

E.g. I created a record with today's date using the date created field from islandora_defaults:
<img width="416" alt="Screen Shot 2021-12-21 at 11 49 51 AM" src="https://user-images.githubusercontent.com/29869988/146989989-23564dff-e321-4a89-8bd4-15c62d4e935b.png">
If you then go to the date created display settings you will notice that the year format inexplicitly says "Do not show year" even though it _does_:
<img width="971" alt="Screen Shot 2021-12-21 at 11 50 54 AM" src="https://user-images.githubusercontent.com/29869988/146990341-1c0cf071-4878-449d-9857-876ecd3ca9fa.png">
Also, the two-digit year option copied the option text from month:
<img width="871" alt="Screen Shot 2021-12-21 at 11 52 05 AM" src="https://user-images.githubusercontent.com/29869988/146990428-173d5f02-e611-4dc9-af45-0c0563869ece.png">
Regardless, the year setting always shows the "do not show year" option as selected, even when it wasn't before.

I have a PR incoming for that issue.

Further, the [middle-endian order will display the year regardless of the year setting](https://github.com/islandora/controlled_access_terms/blob/2.x/src/Plugin/Field/FieldFormatter/EDTFFormatter.php#L307-L311). E.g. the settings in the screenshot below will result in the year displaying even when configured not to:
<img width="882" alt="Screen Shot 2021-12-21 at 11 53 57 AM" src="https://user-images.githubusercontent.com/29869988/146990800-9998bb1a-9207-49f8-98c4-6cbd0f68fe00.png">
<img width="426" alt="Screen Shot 2021-12-21 at 11 54 30 AM" src="https://user-images.githubusercontent.com/29869988/146990804-ae4ffdef-e747-4c24-9647-dab12349787a.png">

The simple workaround for the second issue is to simply use either the big or small-endian options if you don't want to show the year. No code fix for that bit yet.

**Comment by Natkeeran** [comment]
This PR works as expected.
