### ISSUE TITLE
Need to find a place in the docs navigation Islandora 2 release notes

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2063]
This issue was suggested by @seth-shaw-unlv.
 
We need to find a place in the navigation for spot for current and future Islandora 2 release notes, sicne right now  there is no direct link from the docs (as far as we know). You would need to traverse the github repo to find the release notes.

Here is the only one and current release notes on the repo:

https://github.com/Islandora/documentation/blob/main/docs/release_notes/8.x-2.0.md

My first suggestion for a spot for it in the navigation is at the top of the "Installation" section in mkdocs.yml before line 72...

https://github.com/Islandora/documentation/blob/3273e1a3f2007f975b1a1d12268830ca90fe6202/mkdocs.yml#L67-L73

I am thinking something like this...

```
  - Installation:
      # Procedural, different user roles: clarify who the audience is for a
      # particular recipe. The ISLE documentation page was written with a
      # 'non-technical' user in mind who wants to test. The Manual installation
      # guides mention that users will need additional knowledge about server administration.
      - 'Release Notes': 'release_notes/8.x-2.0.md'
          - 'Older Release Notes': 'release_notes/'
      - 'Docker (ISLE)':
          - 'Introduction to ISLE': 'installation/docker-introduction.md'
```

Though other may have better ideas and look forward to hearing them. 
@Islandora/documentation @Islandora/8-x-committers

**Comment by eldonquijote** [comment]
This is probably an oversight, since all documentation pages should be linked from the menu tree. 

In this case, they could be linked from different places in the menu, but I like the suggestion to add them to the "Installation" section for starters.

**Comment by ysuarez** [comment]
@eldonquijote thanks for the feedback. I am creating a PR for this since you thought it would be an OK place for it (at least for now).

Also, when building the docs locally the software listed the release file I am now linking as not being reflected in the navigation at all. Now that I have linked to the release notes locally, the Mkdocs software says these additional files are also not linked in the navigation. I am going to list them here to document them, so I or someone else can check if they also need to be linked from the navigation...

```
<snip>
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - placeholder.md
  - contributing/readme_template.md
  - installation/docker-download.md
  - tutorials/switch_homepage_to_twig.md
  - user-documentation/recipes/alexa_search.md 
<snip>
```

**Comment by rosiel** [comment]
since the release notes are in the menu now, is it okay to close this ticket?

**Comment by eldonquijote** [comment]
`  - user-documentation/recipes/alexa_search.md`  is linked from the page "Extending Islandora" (aka cookbook)
`  - placeholder.md` is practically empty
`  - installation/docker-download.md` is empty

`  - tutorials/switch_homepage_to_twig.md` could be linked from the Cookbook as well, although I'm not sure whether the described steps are optional, or should actually be best practice if Twig is the default templating mechanism in D8..?
`  - contributing/readme_template.md` - unclear where that should be linked from

**Comment by ysuarez** [comment]
¡Thanks @rosiel!

I am going to close this ticket and open a new one for the "unlinked" files I ran into, in case they need follow up.
