### ISSUE TITLE
Bug: unable to change paged content child weights if all values are set to 1.

### ISSUE THREAD

**Issue by antbrown** [Islandora/documentation#2065]
If you accidentally set all weights to 1 using the IntegerWeightSelector, it is then impossible to change the value to anything other than 1.

![node-field-weight-ui-options](https://user-images.githubusercontent.com/1214401/158965924-04252567-e270-4ce9-bc4e-895c437df475.png)

![node-field-weight-db-values](https://user-images.githubusercontent.com/1214401/158965960-7e85e99f-082a-4a0d-84b0-88646d57f95e.png)

I think this happens because https://github.com/Islandora/islandora/blob/2.x/src/Plugin/views/field/IntegerWeightSelector.php#L54 only populates all possible values for the select element if there is a blank value returned from `$this->getValue($row)`.

I think it should maybe populate all possible values when the number of options is less than the total number of rows returned by the view.

**Comment by jordandukart** [comment]
Merged in https://github.com/Islandora/islandora/pull/863.
