### ISSUE TITLE
Add an ancestor condition that looks beyond the direct parent.

### ISSUE THREAD

**Issue by jordandukart** [Islandora/documentation#2071]
https://github.com/Islandora/islandora/blob/2.x/src/Plugin/Condition/NodeHasParent.php exists which looks at a direct parent, it'd be nice to do this on the ancestor chain. PR to come.

**Comment by seth-shaw-unlv** [comment]
Could this be a separate condition, e.g. NodeHasAncestor, in case the site really does want to _just_ check the parent? Either that or a condition configuration to expand the search up the hierarchy?

**Comment by jordandukart** [comment]
After chatting in Slack with @seth-shaw-unlv, re-worked it to be a helper in utils as well as updating `islandora_breadcrumbs` to leverage it to DRY things up.

**Comment by jordandukart** [comment]
Closing as the PR is merged.
