### ISSUE TITLE
Enable issues on Islandora-Devops/islandora-playbook and add it to the project issue list

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#2072]
Hello,

Since we have been opening up issue queues for various Islandora projects, we should do the same for Islandora-Devops/islandora-playbook. Once this is done its issues should be included in the query that shows the active issues for Islandora. I don't have permission to do this for Islandora.

This came up in today's tech call: https://github.com/Islandora/islandora-community/wiki/March-30%2C-2022

**Comment by islandora-community** [comment]
I've just gone ahead and opened an [issue queue](https://github.com/Islandora-Devops/islandora-playbook/issues) for Islandora-Devops/islandora-playbook. 
I think the [current query](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3AIslandora+user%3AIslandora-Devops) for active issues will include any issues opened as it includes issues from user:Islandora-Devops , which islandora-playbook is under.

**Comment by misilot** [comment]
Thanks for doing this! Just curious if it would be worth moving issues for projects that have an issue queue active to those? 

At least for me, I think it would make it a little easier to find open issues / solutions?
