### ISSUE TITLE
Islandora weight doesn't let you reorder children

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2076]
The integer weight fields don't seem to work if content wasn't created from the Add Members tab. 

To replicate:
1. create a paged content item
2. create two or more page items **from the global add content** interface (i.e. not from the Members tab)
3. In the member of field, point the pages to the paged content.
4. Go to the paged content item's members tab and attempt to re-order children.

My results were that dragging the bottom child to the top took no effect (pressing Save caused it to revert to the bottom). With "View weights" on, I could see that both of them were weight 1 and the dropdown gave me no option to change the value.
<img width="979" alt="Screen Shot 2022-04-04 at 4 08 16 PM" src="https://user-images.githubusercontent.com/1943338/161617878-766949a0-8c08-49a8-bc8d-5a0068896b4a.png">

**Comment by amyrb** [comment]
In the context of compound objects rather than paged content, I have been able to reorder children by editing each of the child objects and setting the weight there. The problem you describe clearly needs fixing, but setting the weight directly by editing the child node might be a workaround? (Unless it isn't?)

**Comment by seth-shaw-unlv** [comment]
I believe [this PR ](https://github.com/Islandora/islandora/pull/863) provided a fix for this. Could you double-check to make sure you have the latest 2.x code for islandora and try again?

**Comment by rosiel** [comment]
It did. [edit: It fixed it. I did not have the latest 2.x code.] Would it be possible to tag a bugfix or greater release of the 2.x code? It appears to have been 6 months since our last tag.

**Comment by seth-shaw-unlv** [comment]
Sure. Give me a few minutes to finish testing https://github.com/Islandora/islandora/pull/865 and then I can do that.

**Comment by seth-shaw-unlv** [comment]
@rosiel https://github.com/Islandora/islandora/releases/tag/2.2.0

**Comment by rosiel** [comment]
also thank you @amyrb that was a smart workaround. I had the "Custom sort weight" hidden inside an accordion fold and didn't notice it.
