### ISSUE TITLE
Should we specify which versions of Drupal can be loaded in isle-dc's /codebase?

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2081]
On the [installation/docker-local.md](https://islandora.github.io/documentation/installation/docker-local/) page of the docs it says

"If you do already have a Drupal site, use git to clone it into place as the codebase folder." 

I was wondering if we should mention that the existing site has to be Drupal 8+ or maybe it should say Drupal 9+? I just want to specify a number to avoid having someone with a Drupal 7 site think that they can proceed with the rest of the docs.

For the record, the previous line in this file does say "If you don't already have a Drupal site, you'll be given a basic setup using **Drupal 9** and the", therefore the change I am thinking about may not be really needed. 

I can make this PR if people think it will be helpful, but I wanted to make sure what should be the minimum Drupal version I should mention. 

Thanks in advance.

**Comment by rosiel** [comment]
from tech call: yes, specify Drupal 9

**Comment by ysuarez** [comment]
Thanks, I will make a PR for this.

**Comment by ysuarez** [comment]
I decided to just commit straight into main, since I was just adding a single digit and a space with this commit c0c4b82338f9f75da35e7d71a855424181e9515d
