### ISSUE TITLE
Shutting down ActiveMQ causes a White Screen of Death on many actions

### ISSUE THREAD

**Issue by whikloj** [Islandora/documentation#2099]
**What steps does it take to reproduce the issue?**

On Islandora with islandora_defaults installed
Shut down ActiveMQ (i.e. `sudo service stop activemq` on most distros)
Add/Delete a new taxonomy term (I'm using language)
You see the fabeled Drupal WSOD (White Screen Of Death)

**Which version of Islandora are you using?**
Current

**Any related open or closed issues to this bug report?**
https://github.com/stomp-php/stomp-php/issues/167

**Comment by whikloj** [comment]
Also see [Slack discussion](https://islandora.slack.com/archives/CM5PPAV28/p1651074082888349)

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/islandora/commit/d8d101e5710c42804f06eff0f6c6a4ee3c69adbd
