### ISSUE TITLE
Add ICS link for community calendar

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#2102]
The [original link](https://calendar.google.com/calendar/u/0/embed?src=96s6v709n719hapqtt9m8vj588@group.calendar.google.com&ctz=America/Toronto) navigates to the embedded calendar view but does not give access to the needed ICS file to subscribe via a calendar viewer of your choice. 

A 2nd link should go to a ICS file linked within the “Event Calendar” section on https://www.islandora.ca/community 
<img width="848" alt="Screen Shot 2022-05-02 at 4 27 01 PM" src="https://user-images.githubusercontent.com/2738244/166321822-5a54eea5-3c19-493d-96ee-4b7f5998657e.png">

This link works when adding it to a calendar
`https://calendar.google.com/calendar/ical/96s6v709n719hapqtt9m8vj588@group.calendar.google.com/public/basic.ics`

**Comment by islandora-community** [comment]
<img width="575" alt="icsButton" src="https://user-images.githubusercontent.com/92804539/166952830-ebef4ace-d0d1-461a-81ee-e771e6d13bc0.png">

I've added a button on the community page to access the ICS file
