### ISSUE TITLE
[BUG] islandora_entity_view causes WSOD for media without a source file

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#2110]
## What steps does it take to reproduce the issue?

* Create a media without a source file (this occurred with a broken migration).
  * Create a media via the UI
  * Jump to the command-line and the interactive terminial `drush php:cli`
  * Load the media, e.g. `$m = \Drupal::entityTypeManager()->getStorage('media')->load(1);` (replacing "1" with your test media's ID)
  * Get the source file: `$f = \Drupal::service('islandora.media_source_service')->getSourceFile($m);`
  * Delete it: `$f->delete();`
  * Clear your cache
* Make sure the field_gemini_uri is set to display with the media's default mode
* Visit the media's page and receive a WSOD

The error occurs because `$source_file = $media_source_service->getSourceFile($entity);` returns `FALSE` and the following line, `$uri = $source_file->getFileUri();` is trying to call the getFileUri function on a boolean value.

## To whom does it occur (anonymous visitor, editor, administrator)?

All

## What did you expect to happen?

The media's page should be displayed

## Which version of Islandora are you using?

2.x

**Any related open or closed issues to this bug report?**

None that I found.

**Comment by seth-shaw-unlv** [comment]
Throwing in the following check after the getSourceFile call resolves the issue:
```
        if (!$source_file) {
          \Drupal::logger('islandora')->warning("Can't get source file for " . $entity->label() . "(" . $entity->id() . ")");
          return;
        }
```

**Comment by jordandukart** [comment]
Resolved in https://github.com/Islandora/islandora/pull/874.
