### ISSUE TITLE
[BUG] Docs are not automatically building with newest MarkDown content

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2114]
**What steps does it take to reproduce the issue?**

Visit this official [docs page](https://islandora.github.io/documentation/installation/docker-maintain-drupal/) and see that the changes from this [merged PR](https://github.com/Islandora/documentation/commit/32aa02bcad80814a37571d2ed63140aeb8670f35) are not reflected

Here is a link that displays errors in building docs.
https://github.com/Islandora/documentation/actions

* When does this issue occur?

n/a

* Which page does it occur on?

In a few official doc pages that should have newer content, for example https://islandora.github.io/documentation/installation/docker-maintain-drupal/

* What happens?
n/a

* To whom does it occur (anonymous visitor, editor, administrator)?

All visitors to the official docs.

* What did you expect to happen?

That the latest documentation commits would lead to new markdown content. 

**Which version of Islandora are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by rosiel** [comment]
Found the source: `mkdocs-material-insiders`, our theme, requires `pymdown-extensions>=9.4` , but pymdown-extensions dropped python 3.6 support back in 9.2. Our Travis environment runs on python3.6.7, which seems to be a default. We might be able to specify the python version in the Travis file to something more recent.

**Comment by rosiel** [comment]
Resolved with #2115
