### ISSUE TITLE
Documentation: Audit the contents of CONTRIBUTING.md

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2118]
The contents of CONTRIBUTING.md are a bit redundant and out-of-date with some existing pages in the rest of the mkdocs official docs.

This file is also being displayed within the official docs at this path... 
https://islandora.github.io/documentation/contributing/CONTRIBUTING/

 It is normal that CONTRIBUTING.md exists in the root directory of the a repo, specially if it was a repo for storing code. Though this is a documentation repo nowadays. We may want to come up with a new way of using the CONTRIBUTING.md or eliminating it. For example, we may want to just put links to the relevant sections in the official docs, instead of maintaining content in two places.

**Comment by islandora-community** [comment]
A [doc](https://docs.google.com/document/d/1h2KRHNtmyEf3hV5zeBF1O2AMx_WH1b0NWe3nRo5u3tk/edit?usp=sharing) to discuss CONTRIBUTING.md in future Tech Calls and the upcoming Documentation Sprint. 
This reflects revisions made by @inikolaidis to reference the new issue templates. Comments and feedback are appreciated! @Islandora/documentation
