### ISSUE TITLE
Facets module installed by playbook (^1.6) is out of date (2.0.2 available)

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2121]
**Overview of feature request**

We should update facets and ensure that our out of the box config works for the new 2.x version.
 
**What kind of user is the feature intended for?**

Sys admin and user
 
**What inspired the request?**
Going through seeing what old versions we're installing
 
**What existing behavior do you want changed?**
 not really sure if it'll change behaviour.  
 
**Any brand new behavior do you want to add to Islandora?**
 But apparently we could set up something called a hierarchical date granularity facet. https://www.drupal.org/docs/contributed-modules/facets 
 
**Any related open or closed issues to this feature request?**
no

**Comment by alxp** [comment]
This should be a dependency in islandora_defaults, which has some facet configs in its 'optional' folder.

**Comment by rosiel** [comment]
Due to the config being "optional", it is designed to load those configs if facets is already present. It would break the model that is currently in place to make it a dependency of defaults - that would require us to move those configs to 'install' instead of 'optional'. It makes sense given the way that defaults is set up that we have facets in the playbook.

But there are a number of other modules that are required by the playbook despite being required by islandora or islandora default - I've made a PR to remove them (as well as update some versions).

**Comment by alxp** [comment]
Resolved by https://github.com/Islandora-Devops/islandora-playbook/pull/222
