### ISSUE TITLE
Installation hands on

### ISSUE THREAD

**Issue by Frazer-Nyambe** [Islandora/documentation#2125]
i'm on the step below and the buffer is saying : [ Directory '/opt/karaf/bin' does not exist ]

Creating a setenv.sh Script for Karaf

Similar to Tomcat, our Karaf service is going to rely on a setenv shell script to determine environment variables Karaf needs in place when running. For now, this will simply be the path to JAVA_HOME, but this also accepts many other parameters you can find in the default setenv script.

/opt/karaf/bin/setenv | karaf:karaf/755

#!/bin/sh
export JAVA_HOME="PATH_TO_JAVA_HOME"

    PATH_TO_JAVA_HOME: This will be the same JAVA_HOME we used when installing Tomcat , and can be found using the same method (i.e., still /usr/lib/jvm/java-11-openjdk-amd64 if that's what it was before).

**Comment by flummingbird** [comment]
Frazer-Nyambe, I think this is a similar problem to what you've faced before:

check this path: 
```ls /opt/karaf/```
or 
``` ls /opt/apache-karaf-*```

if there isn't anything there go back to this step: 

```cd /opt
sudo wget -O karaf.tar.gz KARAF_TARBALL_LINK
sudo tar -xzvf karaf.tar.gz
sudo chown -R karaf:karaf KARAF_DIRECTORY
sudo mv KARAF_DIRECTORY/* /opt/karaf
```

The variables in ALL_CAPS are supplied by you, visit https://karaf.apache.org/download.html for the KARAF_TARBALL_LINK probably (https://dlcdn.apache.org/karaf/4.4.0/apache-karaf-4.4.0.tar.gz), 

when you run ```sudo tar -xzvf karaf.tar.gz``` you should use the directory that outputs as the KARAF_DIRECTORY variable.
(if you ```ls /opt/apache-karaf-*``` I think that will help you find the correct directory, which I think is /opt/apache-karaf-4.4.0)

If you have more trouble let me know.

**Comment by Frazer-Nyambe** [comment]
The first code outputs:
frazer@frazer-Islandora:~$ ls /opt/karaf/
ls: cannot access '/opt/karaf/': No such file or directory

Then the second code outputs the following content:
frazer@frazer-Islandora:~$ ls /opt/apache-karaf-*
bin          data    etc       lib      NOTICE     RELEASE-NOTES.md
BUILDING.md  deploy  examples  LICENSE  README.md  system

**Comment by Frazer-Nyambe** [comment]
is there some code i would run to probably uninstall karaf and restart the whole installation process.

**Comment by Frazer-Nyambe** [comment]
So the directory 'opt/karaf' does not exist, where is it created?:

frazer@frazer-Islandora:/opt$ sudo mv /opt/apache-karaf-4.4.0/* opt/karaf
mv: target 'opt/karaf' is not a directory

**Comment by seth-shaw-unlv** [comment]
> So the directory 'opt/karaf' does not exist, where is it created?:

 `opt/karaf` is relative because it lacks the leading '/'. Try `sudo mv /opt/apache-karaf-4.4.0/* /opt/karaf`

Although, with Alpaca 2.0, you no longer need Karaf. The installation instructions should be updated to reflect that.

**Comment by Frazer-Nyambe** [comment]
@seth-shaw-unlv i'm still getting the below output:

frazer@frazer-Islandora:/opt$ sudo mv /opt/apache-karaf-4.4.0/* /opt/karaf
mv: target '/opt/karaf' is not a directory

**Comment by seth-shaw-unlv** [comment]
Well it looks like the step earlier in the instructions, `sudo adduser karaf --ingroup karaf --home /opt/karaf --shell /usr/bin`, wasn't successful in creating the home directory.  I suppose you could try running that again, or simply create the directory manually: `sudo mkdir /opt/karaf`.

Alternatively, you could create a link instead of moving everything over: `sudo ln -s /opt/apache-karaf-4.4.0 /opt/karaf`.

**Comment by Frazer-Nyambe** [comment]
The file path below tells me that...... [ Directory '/opt/karaf/etc' does not exist ] ...... ON the step for Configuring Karaf Logging

frazer@frazer-Islandora:/opt$ sudo nano /opt/karaf/etc/org.pos4j.pax.logging.cfg

**Comment by Frazer-Nyambe** [comment]
or maybe help me with the uninstallation instructions so that i can restart the whole process for karaf

**Comment by flummingbird** [comment]
Sorry you're having so much trouble.

I think we can get what you have fixed.
```ls /opt/apache-karaf-4.4.0/*```

If it outputs ```bin data etc lib NOTICE RELEASE-NOTES.md```
then you still have the files you need. We just need to get them to a directory.

If you can confirm that ```ls /opt/karaf```
is not a directory try running ```sudo mkdir /opt/karaf```
then ```ls /opt``` you should see karaf listed among other directories

Now you have a choice you can simlink as Seth Suggests (thanks seth!)
```sudo ln -s /opt/apache-karaf-4.4.0 /opt/karaf```
or you can move the files from one directory to the other as in 
```sudo mv /opt/apache-karaf-4.4.0/* /opt/karaf```
this should work now that the directory /opt/karaf is properly created.

I do think we should also check that the karaf user is set up correctly too, cat you write:
```groups karaf```
If  you get no user try ```sudo adduser karaf --ingroup karaf```

**Comment by Frazer-Nyambe** [comment]
This worked thank you
