### ISSUE TITLE
[BUG] Batch Upload Children can't upload any files

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#2129]
**What steps does it take to reproduce the issue?**

Tested on ISLE and Virtualbox / Playbook with same errors:

1. Go to a Repository Item, then click on the Children tab.
2. Click the '+ Batch Upload Children' button.
3. Click 'Choose file' and select a file or files to upload.

* When does this issue occur?

Always

* Which page does it occur on?

Batch Upload Children

* What happens?

The error "The file could not be uploaded" is shown on the page.

In Watchdog:
<blockquote>
Referrer	http://localhost:8000/node/125/members/upload
Message	The upload directory for the file field could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.

Location	http://localhost:8000/node/125/members/upload?_wrapper_format=drupal_ajax&ajax_form=1&element_parents=upload
Referrer	http://localhost:8000/node/125/members/upload
Message	Notice: Undefined index: #field_name in file_managed_file_save_upload() (line 1438 of /var/www/html/drupal/web/core/modules/file/file.module)
#0 /var/www/html/drupal/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/html/d...', 1438)
#1 /var/www/html/drupal/web/core/modules/file/file.module(1438): _drupal_error_handler(8, 'Undefined index...', '/var/www/html/d...', 1438, Array)
#2 /var/www/html/drupal/web/core/modules/file/src/Element/ManagedFile.php(76): file_managed_file_save_upload(Array, Object(Drupal\Core\Form\FormState))
#3 [internal function]: Drupal\file\Element\ManagedFile::valueCallback(Array, Array, Object(Drupal\Core\Form\FormState))
#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1258): call_user_func_array(Array, Array)
#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1000): Drupal\Core\Form\FormBuilder->handleInputElement('add_children_fo...', Array, Object(Drupal\Core\Form\FormState))
#6 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1070): Drupal\Core\Form\FormBuilder->doBuildForm('add_children_fo...', Array, Object(Drupal\Core\Form\FormState))
#7 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(574): Drupal\Core\Form\FormBuilder->doBuildForm('add_children_fo...', Array, Object(Drupal\Core\Form\FormState))
#8 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(320): Drupal\Core\Form\FormBuilder->processForm('add_children_fo...', Array, Object(Drupal\Core\Form\FormState))
#9 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\islandora\Form\AddChildrenForm), Object(Drupal\Core\Form\FormState))
#10 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#11 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#12 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#13 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#14 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#15 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#16 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#17 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /var/www/html/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component

</blockquote>

* To whom does it occur (anonymous visitor, editor, administrator)?

Administrator 

**Which version of Islandora are you using?**

2.4.0

**Any related open or closed issues to this bug report?**

No

**Screenshots:**
![image](https://user-images.githubusercontent.com/82412/177383119-ad7f4527-e9d4-45cf-b4f2-b7cb1671ac1a.png)

**Comment by jordandukart** [comment]
We're tracking a similar issue with this internally with the `Batch Upload Children` functionality which runs into the similar issues to which you are seeing. Fixing both these forms is work we are willing to undertake and contribute back but it may make sense to align thoughts / direction on the next tech call to ensure everyone is on board for the proposed changes.

**Comment by rosiel** [comment]
I'm guessing you mean `Batch Upload Media` because I'm finding the same on there, too. I'll put this on the agenda for the tech call following the Conference.

**Comment by marc1aj** [comment]
It's happening with both Batch Upload Children and Media.

**Comment by rosiel** [comment]
Closed with https://github.com/Islandora/islandora/pull/896

**Comment by rosiel** [comment]
Docs PR: https://github.com/Islandora/documentation/pull/2187

**Comment by szanati** [comment]
@rosiel  I just want to make sure that my systems person just needs to update composer to fix the batch children issue? Thanks.

**Comment by rosiel** [comment]
Yes! They can use Composer to update the Islandora module to a [release above 2.5.0](https://github.com/Islandora/islandora/releases).  As long as you're already above Islandora 2.0.0, this should work.

`composer show islandora/islandora` should tell you what version (or commit) of Islandora you're on.
`composer update -W islandora/islandora` should update the islandora module as well as its dependencies.
