### ISSUE TITLE
[BUG] File access is not ensured before attempting to use them in IIIF/OpenSeadragon

### ISSUE THREAD

**Issue by adam-vessey** [Islandora/documentation#2134]
**What steps does it take to reproduce the issue?**

* When does this issue occur?

This was encountered when setting a "file"-level embargo using the [dgi's fork of the `embargoes` module](https://github.com/discoverygarden/embargoes/); however, any other mechanism to constrain access to particular file entities would similarly cause it to happen.

* Which page does it occur on?

Viewing images/paged content which make use of IIIF manifests where the current user does not have access to to the file entities referenced from the media selected for use in the displays.

* What happens?

Broken viewers are shown, with 403 errors emitted to browser consoles (and presumably to Drupal's watchdog logs).

* To whom does it occur (anonymous visitor, editor, administrator)?

Those without access to the referenced files.

* What did you expect to happen?

Viewers would not be visible or not attempt to render elements for entities to which the user does not have access.

**Which version of Islandora are you using?**

2.4.0

**Any related open or closed issues to this bug report?**

Unknown; though, here's a number of PRs addressing things:
* https://github.com/Islandora/islandora/pull/884
    * addressing the inclusion of access-controlled file entities in IIIF manifests generated by `islandora_iiif`
* https://github.com/Islandora/openseadragon/pull/42 
    * addressing the inclusion of access-controlled file entities in the one-off media formatter field (and some caching metadata on the block)
* https://github.com/Islandora/openseadragon/pull/41
    * an optimization to better deal with caching, associated with https://github.com/Islandora/openseadragon/pull/42

**Screenshots:**

**Comment by seth-shaw-asu** [comment]
Anything else, @adam-vessey?

**Comment by adam-vessey** [comment]
Nah, that was it... except... I guess, releases of the two things, `islandora` and `openseadragon`? Drafted... sane (assuming they're visible)?:

- ~~https://github.com/Islandora/islandora/releases/tag/untagged-1e1e9e3fd185b3012538~~ https://github.com/Islandora/islandora/releases/tag/2.4.3
- ~~https://github.com/Islandora/openseadragon/releases/tag/untagged-7d244167655e8480fbe0~~ https://github.com/Islandora/openseadragon/releases/tag/2.0.2
