### ISSUE TITLE
[BUG] Installation of Solr in Playbook is failing

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#2138]
For two consecutive attempts this morning, building the Playbook has failed for me when it attempts to install Solr. Here is the top of the error I am seeing (it goes on for hundreds of lines, mostly reporting the inability to create subcategories):

```
TASK [geerlingguy.solr : Expand Solr.] *****************************************
Thursday 21 July 2022  09:45:29 -0700 (0:01:31.084)       0:49:12.465 ********* 
[WARNING]: Error deleting remote temporary files (rc: 1, stderr: })
fatal: [default]: FAILED! => {"changed": false, "dest": "/root", "extract_results": {"cmd": ["/usr/bin/tar", "--extract", "-C", "/root", "-z", "-f", "/root/solr-8.11.2.tgz"], "err": "/usr/bin/tar: solr-8.11.2: Cannot mkdir: Read-only file system\n/usr/bin/tar: solr-8.11.2/LUCENE_CHANGES.txt: Cannot open: No such file or directory\
```

**What steps does it take to reproduce the issue?**

Try to build an Islandora Playbook. I  am using code at  311aa2126947869ce20d7765e9689de3d219d835. My host is running Ubuntu 20.04.4.

* When does this issue occur?

When I try to build a Playbook.

* Which page does it occur on?
n/a

* What happens?
See error above.

* To whom does it occur (anonymous visitor, editor, administrator)?
n/a

* What did you expect to happen?

No errors.

**Which version of Islandora are you using?**

https://github.com/Islandora-Devops/islandora-playbook at 311aa2126947869ce20d7765e9689de3d219d835.

**Any related open or closed issues to this bug report?**

Not that I know of.

**Comment by alxp** [comment]
Hi @mjordan ,

I was just able to run a full playbook install on to a Vagrant box running Ubuntu 20.04 (recently updated focal64 base box)

Are you deploying to Vagrant or to a remote server?

I did run in to a similar error of tar reporting that it couldn't open a file and I think it ended up being a network error. Perhaps some basic checking of m35 sums of downloaded files would be good practic.

**Comment by mjordan** [comment]
Huh, it's building fine now. Sorry for the false report!

**Comment by mjordan** [comment]
BTW I was building to Vagrant on my laptop.
