### ISSUE TITLE
[DOCS]Links to Audio and Video sections of Behaviours (Models) broken

### ISSUE THREAD

**Issue by BuddyinKC** [Islandora/documentation#2139]
Started with https://islandora.github.io/documentation/concepts/collection/ and noticed there was Paged Content, Audio and Video. But the links for Audio and Video generate 404 errors. Links have a different structure:

Audio - https://islandora.github.io/documentation/models/audio.md

Video - https://islandora.github.io/documentation/models/video.md

* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**

* **Describe your documentation request.**

* **Which version of islandora are you using?**

* **What user roles is this documentation intended for?**

* **What implementations of islandora does this documentation request apply to?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by rosiel** [comment]
Yep - that was a @todo - i'll get on that!
