### ISSUE TITLE
Potential idea for discussion: re-arranging *Using Islandora* section [DOCS]

### ISSUE THREAD

**Issue by mjanowiecki** [Islandora/documentation#2154]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**

I'm not sure how to link to it, but I'm looking at the section of documentation that is nested under https://islandora.github.io/documentation/user-documentation/ 

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**

* **Describe your documentation request.**

As a frequent user of the *Using Islandora* section of the documentation, I think it's a little unclear where to find specific information, especially if you are unsure what specific terms mean (like *Context* or *Flysystem*). For instance, if I'm looking for information on how to adjust how my content/repo items are viewed but I don't know what *IIIF* is or *Context* is, I might not know to click on those pages.

 I was thinking that rearranging this section by function could be helpful to help newbie find what they are looking for. These are main functions I've thought of, but obviously we could pick different terminology or pick more.

- Describe
- View
- Search
- Handling files (idk how else to put this)
- Administer

I've outlined a potential way to rearrange this section based on these functions and would love to talk with documentation folks to see if they think this could be helpful. Here's my preliminary idea -- again, would love a larger discussion on this. :)  

- Introduction
- Describing content*
    - Content models (incorporate Resource Nodes page)
    - Metadata (incorporate Drupal Bundle Configuration page)
    - Linked data (incorporate RDF Generation page)
    - Metadata harvesting (renaming of OAI-PMH page)
- Searching content
    - Search
    - Advanced search
    - Faceting
- Viewing content
    - Context
    - Viewers
    - IIIF
- Handling content files
   - Media
   - Large files
   - Flysystem
- Administering Islandora
    - Access Control
    - Usage Stats
    - Versioning
    -  Islandora Defaults
    - JWT Authentication
- Accessibility in Islandora
- Multilingual Islandora
- Extending Islandora

*Note: For *Describing content*, *Searching content*, *Viewing content*, *Handling content files*, and *Administrating Islandora*, I wasn't envisioning these headers as actual pages necessarily... more as an organizing sections. But we could turn these into pages and add overviews if it would make sense.

* **Which version of islandora are you using?**

Islandora 8

* **What user roles is this documentation intended for?**

I think this documentation is mainly intended for a user or collection manager of Islandora.

* **What implementations of islandora does this documentation request apply to?**

All?

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by mjanowiecki** [comment]
@rosiel I'm just tagging you Rosie because it seems like you have worked a fair amount on these sections and would love to hear what you think :)

**Comment by rosiel** [comment]
I love it! I'd be happy to work with you on this.

**Comment by mjanowiecki** [comment]
awesome! maybe I could do a draft and you could review?

**Comment by mjanowiecki** [comment]
Ok, I did a draft but I somehow pushed it to an old patch of mine? https://github.com/Islandora/documentation/compare/mjanowiecki-patch-1?

**Comment by mjanowiecki** [comment]
How the sidebar looks in patch (approximately): 
![Screen Shot 2022-09-14 at 12 14 42 PM](https://user-images.githubusercontent.com/32551917/190227232-6f1ed48b-aacc-4fa5-9b25-b1f8c8f87f41.png)

**Comment by mjanowiecki** [comment]
This is done now! :)
