### ISSUE TITLE
[TECH DEBT] Break out Mirador into a separate module

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2163]
**Overview of feature request**

Mirador functionality is currently bundled in a submodule of Defaults. But there is no reason the code shouldn't be a standalone viewer module like OpenSeadragon. 

The only thing that would have to be moved are the configs under config/install _that are not setting default values for the options provided for this module itself_ (contexts, entity view displays, etc) which can go in the Starter Site.
 
**What kind of user is the feature intended for?**

Anyone running an islandora site who wants to be able to use Mirador (which can, in theory, do text overlay)
Anyone who wants to be able to run Mirador in Drupal outside of islandora
  
**What existing behavior do you want changed?**

Not behaviour but code task - the location of the mirador module .
 
**Any brand new behavior do you want to add to Islandora?**
 
 in relation to this, it would be cool to provide instructions to upgrade in case you've already installed Mirador.

**Any related open or closed issues to this feature request?**

**Comment by alxp** [comment]
I've added LICENSE and README files to https://github.com/alxp/islandora_mirador. It should be good to move to Islandora organization.

@inikolaidis is there any updated boilerplate I should also add?

**Comment by inikolaidis** [comment]
@alxp Small changes made to the README in this PR: https://github.com/alxp/islandora_mirador/pull/1

**Comment by alxp** [comment]
@inikolaidis Thanks! Merged in to my islandora_mirador instance.

**Comment by rosiel** [comment]
Our LSAP (currently being reworked and I dont know of a public facing document - ping @islandora-community), to be accepted by the Foundation as a module, it should have tests and a Github Workflows integration that runs them (as well as code sniffer and codecov). 

I also would like to strip out the Feature module that contains configuration specific to islandora, and include it in the Islandora Starter Site. The starter site is now 'launched' though has no versions yet.

**Comment by alxp** [comment]
Tests are a good idea but since the code itself is already in the Islandora project, just under islandora_defaults, I don't think the LSAP applies in this case so perhaps it's not necessarily a blocker. I will look in to making a test regardless.

**Comment by rosiel** [comment]
Making this available for everyone to improve sounds like the best plan. The repo has been transferred and is at 
https://github.com/Islandora/islandora_mirador 

Do not close until documentation repo is updated.

**Comment by rosiel** [comment]
Repo needs to be registered with Packagist.
Need to roll a release of Islandora Defaults that doesn't include Mirador.

**Comment by alxp** [comment]
PR for islandora_defaults without Mirador:

https://github.com/Islandora/islandora_defaults/pull/75

**Comment by rosiel** [comment]
The PR has been merged. 🎉

**Comment by rosiel** [comment]
> Do not close until documentation repo is updated.

Oops. 😳
