### ISSUE TITLE
PDF Image Derivatives could be more efficient

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#2165]
When an image derivative is made for a PDF, the _entire_ PDF is used to generate the image.  Every page is taken and then flattened into one image, so it takes a while and the resulting image is oversized.  With a small chunk of code, you can say "just use the first page", which yields the exact same derivative, just smaller and faster.

**What steps does it take to reproduce the issue?**
Upload a 50 MB+ PDF and you'll get slow and oversized derivatives

**Which version of Islandora are you using?**
2+

**Any related open or closed issues to this bug report?**
I've already integrated this with ISLE to an extent.  If this gets merged I can drop a branch i've got over on isle-buildkit.

**Comment by rosiel** [comment]
It'd be nice to have the page number extracted as an option in the System Action (often ETDs etc have boilerplate cover pages). This'll be a separate issue.

**Comment by dannylamb** [comment]
Closing this and staying tuned to https://github.com/Islandora/documentation/issues/2168
