### ISSUE TITLE
[CODE TASK] Playbook takes a very long time.

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2166]
Every time you spin up the Playbook, you have to wait for almost an hour as various things are downloaded, compiled, and installed.

I would like a faster way to "spin up" the environment for testing, especially for testing
* the installation and configuration of the Islandora Starter Site 
* changes to the Islandora Starter Site, such as changes to config and module requirements, that do not impact external services.

I do not know what makes sense given our dev capacity, but
* would it be feasible to cache a partially built state of the machine (maybe as a base box or whatever makes sense
* can we re-evaluate whether Grok is necessary (it takes up the largest amount of time) and I heard a rumour we aren't using it in practice anyway? and maybe other slow services?

**Comment by rosiel** [comment]
Notes from Tech Call today:
* The Playbook is like this, that's why ISLE sounds so good!
* an "everything but the drupal" base box might be nice, as we  used to
* there might be instructions to create and load that base box somewhere.
* automate - every merge to the playbook could automatically build a machine (vagrant cloud?)

**Comment by whikloj** [comment]
Sorry I had a conflicting meeting, but I had a thought that the only issue would be for those that want to use the playbook to provision an actual server. Where they would want Solr/Blazegraph/etc downloaded and Grok compiled as well.

So some alternate playbook for choosing to install those items or assume they are installed would be good.
