### ISSUE TITLE
[DOCS] demo Google Drive links on Installation > Install a Demo are broken

### ISSUE THREAD

**Issue by phette23** [Islandora/documentation#2178]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**

[Docker Demo](https://islandora.github.io/documentation/installation/install-a-demo/)

* **Describe your documentation request.**

The Drive links on this page need to be removed, unfortunately. They lead to a notice saying "We're sorry. You can't access this item because it is in violation of our Terms of Service." I've no idea how this violates their ToS, perhaps it was mistakenly flagged as malware.

* **Which version of islandora are you using?**

n/a

* **What user roles is this documentation intended for?**

All

* **What implementations of islandora does this documentation request apply to?**

Demo

**Any related open or closed issues to this bug report?**

I searched and didn't find any.

**Screenshots:**

<img width="957" alt="Screen Shot 2022-10-06 at 3 41 56 PM" src="https://user-images.githubusercontent.com/1024833/194431728-b62e19e2-efae-46ae-aaed-df086e039386.png">

**Comment by islandora-community** [comment]
Thank you for reporting this issue! It should be fixed now with the re-enabled links taking you to Dropbox for the demo file download.

**Comment by phette23** [comment]
New links seem to work for me!
