### ISSUE TITLE
[BUG] islandora_base_theme Requires install profile

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#2196]
Testing isle-dc with the theme I get the following error is I manually add it and try to install it.
```shell
71   16/Dec 21:21   php             Error      Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by islandora_base_theme have unmet dependencies:                         
                                                 block.block.islandora_base_theme_branding (islandora_install_profile_demo_core), block.block.islandora_base_theme_breadcrumbs                          
                                                 (islandora_install_profile_demo_core, block_class), block.block.islandora_base_theme_disclaimer (fixed_block_content) in                               
                                                 Drupal\Core\Config\UnmetDependenciesException::create() (line 100 of /var/www/drupal/web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php).  
```

**What steps does it take to reproduce the issue?**
Add this to the composer.json file 
```json
        {
            "type": "package",
            "package": {
                "name": "islandora-devops/islandora_base_theme",
                "version": "1.0.0",
                "type": "drupal-theme",
                "source": {
                    "type": "git",
                    "url": "https://github.com/islandora-devops/islandora_base_theme.git",
                    "reference": "main"
                }
            }
        },
```

Then run `composer require islandora-devops/islandora_base_theme`
Related to this https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/main/islandora_install_profile_demo.info.yml#L110

* When does this issue occur?
When installing theme

* Which page does it occur on?
Appearance

* What happens?
Error

* To whom does it occur (anonymous visitor, editor, administrator)?
Developer

* What did you expect to happen?
No error

**Which version of Islandora are you using?**
2.x

**Which method did you use to install your Islandora instance? (manually, ISLE, playbook, etc.)**
Composer

**Any related open or closed issues to this bug report?**
N/A

**Screenshots:**

![Screenshot from 2022-12-16 16-34-03](https://user-images.githubusercontent.com/2738244/208192769-3e015c7f-310a-4347-9697-ccd154998dd4.png)

**Comment by seth-shaw-asu** [comment]
Related PR? https://github.com/Islandora-Devops/islandora_install_profile_demo/pull/33

**Comment by rosiel** [comment]
@joshdentremont and @noahwsmith talked about this on Slack: https://islandora.slack.com/archives/CM5PPAV28/p1671552485864029

**Comment by DonRichards** [comment]
I'm not sure, but this may no longer be relevant.
