### ISSUE TITLE
[BUG] Drupal 9.5 islandora/agent/settings/form-display white screen crash with [mpm_itk:error]child died with signal 11

### ISSUE THREAD

**Issue by darrell-ulm** [Islandora/documentation#2200]
**What steps does it take to reproduce the issue?**
Goto page islandora/agent/settings/form-display after updating to Drupal 9.5.x

* When does this issue occur?
When running Drupal 9.5.x, it does not occur on Drupal 9.3.x

* Which page does it occur on?
islandora/agent/settings/form-display

* What happens?
 white screen crash with [mpm_itk:error]child died with signal 11
Also crashes when trying to change author on repository node

* To whom does it occur (anonymous visitor, editor, administrator)?
administrator / editor

**Which version of Islandora are you using?**
Newest.

**Which method did you use to install your Islandora instance? (manually, ISLE, playbook, etc.)**
Manually with composer.

Browser response

This page isn’t working URL didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by rosiel** [comment]
Can you tell me a little more about what you're trying to do at that page? 

Have you run `drush updb` since updating?

**Comment by darrell-ulm** [comment]
Yes, have run drush updb since updating. 

That page was one I checked when when also editing a repository item, and adding a new author, via add new person (using the entity browser which works on a different field-collections) , the same error occurs.

Basically went to that page looking for anything else that could be broken due to the Drupal 9.5 update.

**Comment by darrell-ulm** [comment]
Looking at this more, believe the error is actually in a custom module. Going to run the upgrade rector to see what changes on that module.

**Comment by rosiel** [comment]
Cool, it sounds like an interesting module! I don't know if it (or your work) is public, but it sound like it'd be a neat demo at an Open meeting or something!

**Comment by darrell-ulm** [comment]
Actually I did not write any of it. I inherited it's maintenance, although I have done Drupal since the 2000's.
The custom module seems to handle adding / editing authors (agents), as it must be something Islandora did not do out of the box, possibly. 
Because it is a segmentation fault error, something in PHP itself, or something new in the /vendor directory is crashing without the back-trace, probably memory overflow due to an infinite loop, I'm assuming. 
Thanks again!
Trying to reproduce the error, happens with Drupal 9.4 and 9.5, not with 9.3 (now unsupported), and can be reproduced in RHEL and Ubuntu.

**Comment by darrell-ulm** [comment]
Believe this can be closed. The segmentation error was from field_group when upgrading to Drupal 9.4 or 9.5.
https://www.drupal.org/project/field_group/issues/3290992
Updating fixed it. 
Others may have the same error if using field_group in certain ways in general, although perhaps not for Islandora core.

Thank you.
