### ISSUE TITLE
[DOCS] Oficial docs (mkdocs) are not building after new commits are pushed

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2210]
* **Describe your documentation request.**

@aOelschlager and I noticed that the oficial docs (mkdocs) are not building after we put in some new commits in the documentation repo.

On slack @misilot reminded us that the docs are built through TravisCI and not Github actions...
https://islandora.slack.com/archives/C01BYA0C2CE/p1676066594133369

Tom had us look at https://github.com/Islandora/documentation/blob/main/.travis.yml

but @aOelschlager and I are still learning about how our community TravisCI is set up, and we are not sure what needs fixing yet.

Any suggestions?

* @Islandora/documentation
* @Islandora/committers

**Comment by adam-vessey** [comment]
With #2212 being merged, has this been addressed?

**Comment by rosiel** [comment]
Yes, i verified the [latest meaningful commit](https://github.com/Islandora/documentation/pull/2208/files) is now reflected in the docs site.
