### ISSUE TITLE
[DOCS]Add Starter Site to Installing a Development Server

### ISSUE THREAD

**Issue by aOelschlager** [Islandora/documentation#2221]
https://islandora.github.io/documentation/installation/docker-local/

* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**

* **Describe your documentation request.**

From a conversation in Slack, TLDR - This person is new to the Islandora stack and wanted to use the Starter Site as a development server which is doable by running make starter but it is not documented on this page.
https://islandora.slack.com/archives/C019U12D44Q/p1680283188130039

* **Which version of islandora are you using?**

* **What user roles is this documentation intended for?**

All users

* **What implementations of islandora does this documentation request apply to?**

ISLE-DC + starter site

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by joshdentremont** [comment]
I just put in a PR for this: https://github.com/Islandora/documentation/pull/2222
