### ISSUE TITLE
[USE CASE] Do we want to expose Media at their own URLs?

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2245]
### Overview of Use Case

There is an option in Drupal's core media settings to have "Standalone Media URL". With it on, all media are visible at /media/[mid] (e.g.) /media/1. 

Right now in the starter site this is off, but should we turn it on?

### Arguments for not having media URLs

* It's cleaner to only expose media through their parent node. You get context and easier site navigation (user won't get lost on leaf pages. Contextual blocks will show up based on the node's configuration). 
* Don't want people to page through media and encounter, for example, FITS files and other things that might be not suitable for public consumption, including media for nodes that aren't published. The incremental nature of media IDs means we are inviting this to happen.
* Workbench defaults assume you don't have this on. There's a workaround configuration option if you do.
* It supports seeing the media as standalone rather than part of a node (assuming you see media as belonging to nodes).

### Arguments for having media URLs
* it supports seeing the media as standalone rather than part of a node (assuming you see media as their own entities subject to management and control, which they are)
* The FITS and Extracted Text media types have data displayed on their "view pages" (e.g. the FITS formatted HTML table) that's not visible otherwise

**Comment by rosiel** [comment]
Some use cases:

(paraphrased from Alexander on the tech call): If you're doing access control, you're making your life much harder by having standalone media URLs.

(paraphrased from Seth on the tech call): It makes administration easier, especially for reading FITS metadata. They were careful to never link to the media URL, and it seems users don't land on it and robots don't index it (which you could enforce with robots.txt)

**Comment by kstapelfeldt** [comment]
+1 for keeping them hidden. If we need to expose the FITS metadata, should we index it and make a view?

**Comment by rosiel** [comment]
I'm closing this ticket under the assumption we have a mild consensus that the answer is "no".
