### ISSUE TITLE
PHP 8.2 Compatibility

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#2262]
PHP 8.1 will be out of active support in Nov 2023; and out of security support a year after. 

PHP 8.1 supports Drupal 9.5, 10.1, and 10.2 but PHP 8.2 only supports Drupal 10.1 and 10.2. 

This will need to be updated:
* in testing matrices for all our components
* in Buildkit to make the containers use the newer PHP

**Comment by adam-vessey** [comment]
(whoops, was just trying to look at the milestone thing)

**Comment by rosiel** [comment]
The code is now 8.2-compliant to the best of my knowledge. Other issues (including updating our devops stuff to actually use 8.2) can be done separately. (e.g. https://github.com/Islandora-Devops/isle-buildkit/issues/293)
