### ISSUE TITLE
[DOCS] 404 arising from inconsistent use of underscore vs hyphen in .md filenames

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#2275]
At https://islandora.github.io/documentation/user-documentation/iiif/#using-iiif-in-islandora the link to "viewer" https://islandora.github.io/documentation/user-documentation/file-viewers 404s.

The actual page is in the docs at https://islandora.github.io/documentation/user-documentation/file_viewers/

* **Describe your documentation request.**
* Fix the 404.
* It is probably best to change the file name to use a hyphen in line with other doc pages with multiple words in title. However I see other doc pages using underscore, e.g. https://github.com/Islandora/documentation/blob/main/docs/user-documentation/content_models.md and https://github.com/Islandora/documentation/blob/main/docs/user-documentation/content_types.md whereas others use hyphen
  * I recommend choosing a single approach (e.g. hyphen) and applying it across all doc files.

**Comment by rosiel** [comment]
I think this has been fixed with the above PR.
