### ISSUE TITLE
Ansible playbook errors in New year

### ISSUE THREAD

**Issue by BrzIGH** [Islandora/documentation#2277]
When running this task in the ansible playbook:

ansible-playbook -kK -i inventory/production playbook.yml -e "islandora_distro=ubuntu/jammy64" -e "islandora_profile=starter" -e "islandora_build_base_box=false"

I get the following error:

TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] *****************************************************************************************
Monday 08 January 2024  14:36:35 -0800 (0:00:04.621)       0:00:33.762 ******** 
failed: [default] (item=drush/drush:^10.1) => {"ansible_loop_var": "item", "changed": false, "item": "drush/drush:^10.1", "msg": "./composer.json has been updated Running composer update drush/drush Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command. - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev]. Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions. Installation failed, reverting ./composer.json and ./composer.lock to their original content.", "stdout": "./composer.json has been updated\nRunning composer update drush/drush\nLoading composer repositories with package information\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.\n    - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.\n    - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev].\n\nUse the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.\n\nInstallation failed, reverting ./composer.json and ./composer.lock to their original content.\n", "stdout_lines": ["./composer.json has been updated", "Running composer update drush/drush", "Loading composer repositories with package information", "Updating dependencies", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - drush/drush[10.1.0, ..., 10.3.1] require chi-teck/drupal-code-generator ^1.30.5 -> found chi-teck/drupal-code-generator[1.30.5, ..., 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.", "    - drush/drush[10.3.2, ..., 10.x-dev] require chi-teck/drupal-code-generator ^1.32.1 -> found chi-teck/drupal-code-generator[1.32.1, 1.33.0, 1.33.1, 1.x-dev] but the package is fixed to 3.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.", "    - Root composer.json requires drush/drush ^10.1 -> satisfiable by drush/drush[10.1.0, ..., 10.x-dev].", "", "Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.", "", "Installation failed, reverting ./composer.json and ./composer.lock to their original content."]}

PLAY RECAP ******************************************************************************************************************************************************************************
default                    : ok=22   changed=5    unreachable=0    failed=1    skipped=122  rescued=0    ignored=0  

I get a similar problem when trying to install the Drupal 10 version of Islandora.

Both of these worked fine back in December but now I am getting consistent playbook errors.

Thanks

**Comment by rosiel** [comment]
There is an open PR that should fix this. Feel free to apply it.

https://github.com/Islandora-Devops/islandora-playbook/pull/271/files

(also, the [playbook defaults to installing drupal 10 now](https://github.com/Islandora-Devops/islandora-playbook/pull/270), that's what changed things over the break.)

**Comment by BrzIGH** [comment]
Thanks. Will just redownload the playbook and redo the installs using the instructions to "Deploy to a remote environment."

**Comment by BrzIGH** [comment]
It keeps failing on me with the same message...

Is it possible to update the scripts at https://github.com/Islandora-Devops/Islandora-playbook so that I do not need to edit anything after downloading and editing only what is in "Deploying to a remote environment" document ?

Thanks

**Comment by rosiel** [comment]
If you go to the pull request page I linked above, and go to the Conversation (first) tab, and scroll down to where it says "View Command line instructions" then you will get a simple 2 steps to "pull" this pull request into your own code. Execute "Step 1" (2 commands) from within the islandora-playbook directory. (Don't execute the merge stuff, which they call Step 2)
<img width="1017" alt="Screenshot 2024-01-11 at 9 49 57 AM" src="https://github.com/Islandora/documentation/assets/1943338/851e91b2-f6f4-49a5-a06b-bff9975c7e3d">

We're also trying to get that PR merged in but sometimes it takes a while.

**Comment by BrzIGH** [comment]
I cannot find the command-line instructions from the "Conversation" tab. But I can execute the code manually. Thanks for the screenshot.

I presume I will do this **after** downloading galaxy requirements and **before** running the first of the two ansible scripts ?

**Comment by rosiel** [comment]
Sorry about that - I forgot that the command-line instructions only show up if you're logged into github and probably a member of this org.

The `git checkout` and `git pull` commands should be done before downloading requirements, but in this case probably won't make much difference if you do it before or after.

**Comment by BrzIGH** [comment]
Running the git pull command gives me access denied..."Please make sure you have access rights"

**Comment by BrzIGH** [comment]
Tried one more time. No joy. Fails at Drupal dependencies stage (same as above).

Will try again next week.

**Comment by ysuarez** [comment]
This issue came up at today's weekly "Tech Call." Are you still having an issue or is this resolved?

**Comment by BrzIGH** [comment]
I eventually ended up by downloading the playbook and following the instructions. Had to make sure the external drupal role pointed to 12 rather than 10 (geerlingguy.drupal). After that Islandora gets installed in a Drupal 10 environment just fine.
