### ISSUE TITLE
[DOCS] Paged Content display out of date with Starter site re available contexts

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#2281]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**
https://islandora.github.io/documentation/user-documentation/iiif/#using-iiif-in-islandora

* **Describe your documentation request.**
"Using IIIF in the Islandora Starter Site" describes using a context "Paged Content - Openseadragon Context" to display paged content. However, in current Starter Site https://sandbox.islandora.ca/admin/structure/context no such context exists, instead the contexts are "Mirador Block - Multipaged items", and "Openseadragon Block - Multipaged items".

**Comment by ysuarez** [comment]
I can create a PR for this and have you verify it.
