### ISSUE TITLE
[DOCS] Evaluate ppa documentation

### ISSUE THREAD

**Issue by eldonquijote** [Islandora/documentation#2285]
* Ask on Slack and in the tech call if documentation about Updating deb package is still needed: https://islandora.github.io/documentation/technical-documentation/ppa-documentation/
* If it's not needed anymore, retire page

**Comment by rosiel** [comment]
I contacted Jonathan Green and confirmed the PPA is still functional in case we have to use it in the future. I propose that we add to the end of the "Background" section,

> If you are running Ubuntu 20.04 or higher, installing a specially-compiled imagemagick is no longer necessary. We are leaving this page available in case in the future we have a need to package our own `deb` and add it to the Lyrasis PPA. 

That sound ok?
