### ISSUE TITLE
[DOCS] Add link to MIG metadata configuration spreadsheet to official docs

### ISSUE THREAD

**Issue by ARCrowe333** [Islandora/documentation#2294]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**
https://islandora.github.io/documentation/user-documentation/metadata/

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**
N/A

* **Describe your documentation request.**
The MIG group created a spreadsheet with the details of the metadata configuration of the “starter site” version of Islandora 2. We think that we should link to this spreadsheet from the official docs.

* **Which version of islandora are you using?**
Islandora 2

* **What user roles is this documentation intended for?**

Collections Manager, Developer, Systems Administrator

* **What implementations of islandora does this documentation request apply to?**
"Starter site"

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by ysuarez** [comment]
Lina and I created this issue, and we are still not sure where exactly in the page https://islandora.github.io/documentation/user-documentation/metadata/ we should add a link to the spreadsheet. Perhaps, we should create a new metadata related page to link for to the spreadsheet.

I can envision adding a section called the same thing as the name of the file: "Islandora Starter Site Metadata Configuration"

Then we could add one or two sentences explaining what the spreadsheet is. For example... 

```
### Islandora Starter Site Metadata Configuration

This spreadsheet contains the details of the various fields, and taxonomy vocabularies, and relators configured for the starter site. 

This spreadsheet was created and maintained by the Islandora [Metadata Interest Group (MIG)](https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group).

```
What do people think?

**Comment by rosiel** [comment]
addressed by https://github.com/Islandora/documentation/pull/2295
