### ISSUE TITLE
[DOCS] Manual Installation: Recommended Changes to Documentation

### ISSUE THREAD

**Issue by slangerx** [Islandora/documentation#2326]
Islandora's [Manual Installation instructions](https://islandora.github.io/documentation/installation/manual/introduction/) include a disclaimer on every page that says, "documentation is in need of attention." The attached document (in both PDF and Word format) is my attempt at providing some of this much-needed attention.

I was finally able to get a manual installation of Islandora for Drupal 10 working, which required quite a lot of trial-and-error and in-depth troubleshooting along the way. I've since made a copy of [Islandora's current online documentation](https://islandora.github.io/documentation/installation/manual/introduction/) (as of **June 21, 2024**) and marked-up each section with my recommended changes. Hopefully, this will help improve the online documentation and make it much easier for others to do a manual installation in the future. 

Let me know if you have any questions or need anything clarified.

-- Stefan

**Comment by slangerx** [comment]
**Manual Installation Documentation: Recommended Changes**
* PDF: [islandora_manual_installation.revisions.2024-06-21.pdf](https://github.com/user-attachments/files/16061246/islandora_manual_installation.revisions.2024-06-21.pdf)
* Word: [islandora_manual_installation.revisions.2024-06-21.docx](https://github.com/user-attachments/files/16061247/islandora_manual_installation.revisions.2024-06-21.docx)

**Comment by ysuarez** [comment]
I don't know enough about how to manually install Islandora, but as a DIG convener I can help with the markdown formatting of these changes, once they are approved.

**Comment by seth-shaw-asu** [comment]
I've begun the process of moving the suggestions into a fork which I'll turn into a PR once I have my first draft completed: https://github.com/seth-shaw-asu/documentation

I've kept most of the suggestions and added a few more additions of my own. E.g. I've upgraded Solr to 9 which simplifies the core creation process.

I've completed through Solr. I'll get to Crayfish and Alpaca next week.

**Comment by seth-shaw-asu** [comment]
The changes were just merged. Thanks for your contribution, @slangerx.

**Comment by slangerx** [comment]
That's great to hear! :-) Thanks, @seth-shaw-asu @ysuarez @rosiel @DonRichards
