### ISSUE TITLE
[DOCS] Link to existing CLA signatories is not accessible to public

### ISSUE THREAD

**Issue by xurizaemon** [Islandora/documentation#2352]
At https://github.com/Islandora/islandora-community/wiki/Contributor-License-Agreements:

> Please see the full list on of Contributor License Agreements on file [at this link](https://docs.google.com/spreadsheets/d/e/2PACX-1vRoZKXrJga17hxhRmoNT34HVkm2W8TRxIyMrM-bS6zxLUuBbu8nrxr-gB9EqPKdZTk4l0LRdWzT-tI3/pubhtml?gid=1490812499&single=true).

That Google Docs link is no longer open to public viewing. Suggest the link might be removed if the information is no longer accessible.

* **Describe your documentation request.**

The link at present is not accessible to the general public. Clicking it leads to a Google Sheet which is restricted to a limited set of users.

If access is not granted, it reads:

> You need permission to access this published document.
> 
> You are signed in as user@example.org, but you don't have permission to access this published document. You may need to [Sign in as a different user](https://docs.google.com/spreadsheets/d/e/2PACX-1vRoZKXrJga17hxhRmoNT34HVkm2W8TRxIyMrM-bS6zxLUuBbu8nrxr-gB9EqPKdZTk4l0LRdWzT-tI3/logout)

* **Which version of islandora are you using?**

n/a

* **What user roles is this documentation intended for?**

Contributors and potential contributors, organisation owners.

* **What implementations of islandora does this documentation request apply to?**

List of contributors is not discoverable.

**Any related open or closed issues to this bug report?**

Not found.

**Screenshots:**

Well, okie dokie then!

![a silly screenshot](https://github.com/user-attachments/assets/f8971a40-25f5-4912-94ec-65e471161891)

**Comment by super2014001** [comment]
您好！您的邮件我已收到！谢谢！

**Comment by ysuarez** [comment]
I have gotten access to the new version of the CLA spreadsheet from Noah. I need to find time to make a less verbose of the data to share on a public page. While keeping all the raw data from the spreadsheet private to be accessible to some community members.

**Comment by super2014001** [comment]
您好！您的邮件我已收到！谢谢！

**Comment by xurizaemon** [comment]
Thanks @ysuarez ! No rush here, though it may be an obstacle to folks considering whether they can submit a PR or issue (which was my situation when I noticed this).

Btw, Super's email auto-reply which I expect below translates to

> Hello! I have received your email! Thank you!

**Comment by DonRichards** [comment]
It's public now.
