### ISSUE TITLE
Use Case: Ability to have sets for OAI-PMH Harvests

### ISSUE THREAD

**Issue by uconnjeustis** [Islandora/documentation#502]
| Title (Goal)        |  Option to create sets for OAI-PMH Harvest         | 
| ------------- |:-------------:| 
| Primary Actor      | Repository Administrator |
| Scope     | configuration | 
| Level | TBD      |
| Story | As a repository administrator, I would like to have the ability to create sets for the harvest. For example, in a repository that is shared among institutions, we often get requests from an institution that only wants their data set. Another example, is to harvest only collections.     |

**Comment by kspurgin** [comment]
It was explained in today's Islandora Metadata Interest Group meeting that you can manually create sets for OAI-PMH harvests by creating new views. 

I wanted to clarify that this use case should still remain open/relevant. Manually setting up a view for a special use case/request is doable, but a common need is to emit each collection as its own set in OAI-PMH. Folks should not have to manually create a view for every collection in order to accomplish this.

**Comment by kspurgin** [comment]
AND, if there is the aforementioned ability to flip an "automagically create an OAI-PMH set for each collection" setting, there also needs to be a config where individual collection IDs (or whatever) can be entered to prevent them from being emitted into OAI-PMH.

Addendum inspired by client request that came in to us today: we want to temporarily prevent items in Collection X from being emitted to OAI-PMH. 

Preventing creation of a Set for said collection could/would fulfill part of this. Presumably there might also need to be something that prevents records for items in said collection being listed in ListRecords, too, depending on the actual use case. That would not fit into this particular use case (I will try to locate the use case where the functionality should actually be expressed), but **from a design/UX perspective**, if I'm adding a collection to an OAI-PMH handling exception list, it makes sense I should be able to check "Do not create set for this collection" and "Do not emit records for items in this collection" in one place.

**Comment by nigelgbanks** [comment]
I've recently encountered this, and found that by creating a view with a contextual filter on `field_member_of` and using that instead emits collections as sets from the rest endpoint.

One could add additional filters on the view, say a field `Exclude from OAI-PMH` or on the parent collection to prevent it from being returned in the response, in the same way that `Content: Publish (= Yes)` is used to exclude non-published items below. 

![2022-02-08_20-40](https://user-images.githubusercontent.com/487373/153072122-21ec0a25-a16a-407a-a926-340d7a14341e.png)

![2022-02-08_20-44](https://user-images.githubusercontent.com/487373/153072415-a0229613-cb0b-4f79-b330-25d14a6a298f.png)

[
](http://nbanks-vagrant-glbt-vm.local/oai/request?verb=ListRecords&metadataPrefix=oai_dc)

```xml
<?xml version="1.0" ?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd" name="OAI-PMH">
    <responseDate>2022-02-08T20:45:13Z</responseDate>
    <request verb="ListRecords" metadataPrefix="oai_dc">http://nbanks-vagrant-glbt-vm.local/oai/request</request>
    <ListRecords>
        <resumptionToken/>
        <record>
            <header>
                <identifier>oai:nbanks-vagrant-glbt-vm.local:node-3</identifier>
                <datestamp>2022-02-08T15:51:18Z</datestamp>
                <setSpec>node:4</setSpec>
            </header>
            <metadata>
                <oai_dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                    <dc:title>Test Image #1</dc:title>
                    <dc:format>1 item</dc:format>
                    <dc:type>Still Image</dc:type>
                    <dc:rights>All rights reserved</dc:rights>
                </oai_dc>
            </metadata>
        </record>
        <record>
            <header>
                <identifier>oai:nbanks-vagrant-glbt-vm.local:node-6</identifier>
                <datestamp>2022-02-08T16:03:49Z</datestamp>
                <setSpec>node:5</setSpec>
            </header>
            <metadata>
                <oai_dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                    <dc:title>Test Image #2</dc:title>
                    <dc:format>1 item</dc:format>
                    <dc:type>Image</dc:type>
                    <dc:rights>All rights reserved</dc:rights>
                </oai_dc>
            </metadata>
        </record>
        <record>
            <header>
                <identifier>oai:nbanks-vagrant-glbt-vm.local:node-8</identifier>
                <datestamp>2022-02-08T16:32:59Z</datestamp>
                <setSpec>node:5</setSpec>
                <setSpec>node:7</setSpec>
            </header>
            <metadata>
                <oai_dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                    <dc:title>Test Image #3</dc:title>
                    <dc:format>1 item</dc:format>
                    <dc:type>Still Image</dc:type>
                    <dc:rights>All rights reserved</dc:rights>
                </oai_dc>
            </metadata>
        </record>
        <record>
            <header>
                <identifier>oai:nbanks-vagrant-glbt-vm.local:node-9</identifier>
                <datestamp>2022-02-08T16:39:43Z</datestamp>
                <setSpec>node:4</setSpec>
            </header>
            <metadata>
                <oai_dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                    <dc:title>Test Image #4</dc:title>
                    <dc:format>1 item</dc:format>
                    <dc:type>Image</dc:type>
                    <dc:rights>None</dc:rights>
                </oai_dc>
            </metadata>
        </record>
    </ListRecords>
</OAI-PMH>

```

**Comment by kspurgin** [comment]
You are awesome, @nigelgbanks and I truly miss working closely with you on a regular basis. 
That said... documentation/recipe PR? 😸

**Comment by nigelgbanks** [comment]
It's part of the site configuration from the feature [here](https://github.com/Islandora/islandora_defaults/blob/ec2cf3cbf883b178c6032173d836dfd30f23431f/modules/islandora_oaipmh/config/install/views.view.oai_pmh.yml), I'll do a pull request to later today. I need to set up an environment to test. Since the module is a feature to get the change you'll need to go into the Features UI (or use `drush`) to get the newest change to the configuration after it has been merged. I'll link the pull request on this ticket when it's ready.

**Comment by nigelgbanks** [comment]
Looks like it'll have to wait for tomorrow somethings come up in testing about how the OAI-PMH results are cached something seems buggy.

**Comment by nigelgbanks** [comment]
Turns out using the above method if the object does not belong to a collection it will not appear in OAI-PMH results, so another view is needed. I think I'll get to making the pull request today.

**Comment by nigelgbanks** [comment]
I've raised a pull request that should sort this out: https://github.com/Islandora/islandora_defaults/pull/65

After it has been merged and integrated into your environment you'll need to import the changes from the feature and export your site configuration.

Go to: `admin/config/development/features` and look for `Islandora OAI-PMH Endpoint` import the changes.

You can then use `drush` to export your site configuration so you can persist it under source control.

```bash
drush config:export
```

**Comment by nigelgbanks** [comment]
Pull request was merged.
