### ISSUE TITLE
Add some cool show-off sandbox content and features

### ISSUE THREAD

**Issue by rosiel** [Islandora/documentation#645]
Along the lines of "selling" CLAW, the sandbox should contain some pre-built content to show off the features of CLAW:
- a good amount of RDF content, including (possibly) a js graph browser? 
- a slick Drupal view or "exhibit" of Drupal content.

**Comment by kimpham54** [comment]
Possibly also play around with Islandora content with some other Drupal 8 modules:

taxonomy
rules
views
block tabs
quick edit
mail system
easy social
chosen
linkit
image effects
mirador
components
twig
paragraphs
address
file entity

**Comment by aulorbe** [comment]
@kimpham54 being able to play around w/Mirador in the sandbox would be awesome

**Comment by DiegoPino** [comment]
Small idea:
@rosiel : about js graph browser -> have [this one](https://github.com/scienceai/jsonld-vis) integrated into "esmero" and it took like 5 minutes to do so. Seems like pretty simple to do on drupal 8 also. Not sure if full blown for our needs but its a good start. Just hook this JS to the JSON-LD output we are already providing in CLAW into a template and you got that. Also: it is used as the standard byJSON-LD playground 👀  https://json-ld.org/playground/#/gist/689ebc48f594957d4910815953ed659c

**Comment by dannylamb** [comment]
@aulorbe Some IIIF viewer is on the docket for MVP, with Mirador being the likely candidate.  So hopefully that will be a reality soon.

@kimpham54 :+1: to paragraphs.  I'd like to add Workflow to the list.  It's part of core but still marked as 'Experimental', but I think it would be useful to a ton of our users.

Also, some of those may depend on https://github.com/Islandora-CLAW/CLAW/issues/643 landing beforehand, as there's potentially lots of hidden assumptions that you're using nodes in there.

**Comment by aulorbe** [comment]
@dannylamb fantastic!

**Comment by flummingbird** [comment]
I've written a script to download and enable mirador... had some strange permission issue, so the script doesn't quite get you to `drush pm-enable mirador -y` so you have to `vagrant ssh`, and enable the module yourself...
