### ISSUE TITLE
Add Drupal dev version to CI environment

### ISSUE THREAD

**Issue by jonathangreen** [Islandora/documentation#655]
Try running our code against Drupal minor version release candidates to see if things will break when a new version of Drupal is coming out.

**Comment by jonathangreen** [comment]
So I took a crack at this, but right now its pretty much impossible due to Drush being borked because Drupal updated major versions of symfony. See details in this issue:
https://github.com/drush-ops/drush/pull/2787

**Comment by jonathangreen** [comment]
Just to leave my work here in case we want to revisit it at some point: 

Updated `travis.yml`:
https://github.com/jonathangreen/islandora-claw/compare/8.x-1.x...jonathangreen:issue-665

Updated `travis_setup_drupal.sh`:
https://github.com/jonathangreen/CLAW/compare/issue-665

**Comment by jonathangreen** [comment]
Here is the travis fail during site install due to drush:
https://travis-ci.org/jonathangreen/islandora-claw/jobs/242069028

**Comment by kstapelfeldt** [comment]
It remains an issue that we need a strategy for looking ahead to testing code on alpha (emerging) versions of Drupal. We do have some portions of this set up. We need to document Github Actions approach.
