### ISSUE TITLE
Technical Documentation For claw-playbook

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#701]
Add some technical documentation markdown format to https://github.com/Islandora-Devops/claw-playbook.

We should have a basic TL;DR section in bullet points for how to get up and running, as well as more in-depth analysis of the architecture for those who are curious.

**Comment by g7morris** [comment]
Okay I've given this a start. https://github.com/Islandora-Devops/claw-playbook/pull/11

**Comment by rosiel** [comment]
I think this particular ticket can be closed, despite docs being an ongoing project; "CLAW" technical documentation is now part of https://islandora.github.io/documentation/ ?
