### ISSUE TITLE
Testing our roles

### ISSUE THREAD

**Issue by jonathangreen** [Islandora/documentation#794]
As per @whikloj's comment [here](https://github.com/Islandora-Devops/claw-playbook/pull/51), we really should be doing some testing of our roles. Especially now that we are working on multiple OS support. 

I've always liked how the [geerlingguy](https://github.com/geerlingguy) roles are tested, so I thought it would be worth trying it out in our repos.

- [x] grok
- [x] karaf
- [x] crayfish
- [x] tomcat8
- [x] blazegraph
- [ ] drupal-openseadragon
- [ ] fcrepo-syn
- [ ] fcrepo
- [ ] cantaloupe
- [ ] keymaster
- [ ] fits
- [ ] apix
- [ ] alpaca
- [ ] activemq

**Comment by jonathangreen** [comment]
Going to make a PR against one of our roles as an example, and we can see if it makes sense to test them all.

**Comment by dannylamb** [comment]
The crayfish role will need CENTOS testing added after https://github.com/Islandora-Devops/ansible-role-crayfish/issues/2 is merged.

**Comment by dannylamb** [comment]
Same with tomcat and https://github.com/Islandora-Devops/ansible-role-tomcat8/pull/3

**Comment by DigitLib** [comment]
The crayfish role installed on CentOS after https://github.com/Islandora-Devops/ansible-role-crayfish/pull/3, but fail in Travis
