### ISSUE TITLE
JP2 Support

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#922]
Right now, everything works great with TIFFs, but JP2s feel like a whole other beast.  We need to figure out how to get Cantaloupe to play nice with OpenJpeg so we can zoom in on JP2s using OpenSeadragon.  We will also want to confirm that Houdini can generate JP2s on a stock claw-playbook instance.

**Comment by dannylamb** [comment]
@rangel35 Thanks for reporting this in this week's CLAW call.

**Comment by noahwsmith** [comment]
This was what we ended up doing in i7, if it's helpful: https://github.com/Islandora/islandora_solution_pack_large_image/pull/192

**Comment by ajstanley** [comment]
We can do all this without any trouble.  Change the extension in our service file action from .jpg to .jp2 and we're done, as long as cantaloupe.properties specifies ManualSelectionStrategy
