### ISSUE TITLE
OpenAIRE support

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#949]
Part of https://github.com/Islandora-CLAW/CLAW/issues/498

When implementing an OAI-PMH endpoint, it would be great if things were kept configurable enough so that we can support OpenAIRE.  Essentially, we would need to provide a way for a repository admin to expose certain metadata fields via the OAI-PMH endpoint.  See https://guidelines.openaire.eu/en/latest/ for a detailed list of fields that would need to be included.

We may want to consider allowing the user to supply their own twig templates for rendering metadata in whatever format they wish, as that would meet the OAI-PMH use case as well as many others.

**Comment by bryjbrown** [comment]
This was discussed at the IRIG meeting today, and keeping the option for OpenAIRE as a format for OAI-PMH would be a nice feature to have that might draw in European users.

**Comment by mjordan** [comment]
And Canadian. SFU will very likely be needing this and we can share what we do.

**Comment by dmoses** [comment]
@mjordan did SFU create an OAI-PMH transform by any chance?

**Comment by mjordan** [comment]
No, but we want one (https://www.drupal.org/project/rest_oai_pmh/issues/3159441) and are happy to sponsor its development as part of our migration to Islandora 8.

**Comment by kstapelfeldt** [comment]
We think the Rest OAI-PMH module does this. You can add your own metadata profile. We don't think that there is an OpenAIRE profile, but there is a path to this now. You can follow Mark's comment in the link above if this remains of interest.

We also acknowledge that the use case could be more general as metadata serialization is appealing in a number of contexts. It may be good to author a new use about configurable metadata serialization in multiple formats.

**Comment by mjordan** [comment]
https://www.drupal.org/project/rest_oai_pmh does not provide non-DC mappings out of the box, it only provides a mechanism for hooking in custom modules to create non-DC serializations ("and a metadata mapping module of your choice").
