### ISSUE TITLE
.ova created from claw-playbook won't launch if it can't write to a local log file

### ISSUE THREAD

**Issue by manez** [Islandora/documentation#975]
We discovered this the hard way as a dozen people at Islandora Camp all tried to launch a CLAW VM that wanted to write to "ubuntu-xenial-16.04-cloudimg-console.log" on the local file system that the VM was built on.

We got things working by editing this field in VirtualBox settings to point to a writable path on each user's local machine (see screenshot), but can we do away with the need to have this file written out locally at all? Or is it something I messed up when creating the VM? 

![image](https://user-images.githubusercontent.com/2371345/48293399-407bac00-e455-11e8-98f9-5187c0efec2f.png)

**Comment by dannylamb** [comment]
I think if set a shell variable before running vagrant up you should be able to prevent it from trying to create a log file.

`$ export VBOX_LOG_DEST=nofile`

We'll need to test that to confirm it, and then document it in claw-playbook's readme.  I gleaned this from https://www.virtualbox.org/wiki/VBoxLogging

But yeah... finally get the shared folder thing sorted out and this old ghost rises to replace it. :ghost: :ghost: :ghost:

**Comment by manez** [comment]
I think this is fixed in most environments in the .ova we shipped with 1.0.0 because it points to tmp now, but there were some issues for a few people at iCamp Switzerland (I want to say... Windows users?). @mjordan or @MarcusBarnes can you confirm? And what the fix was for those cases?

**Comment by mjordan** [comment]
Yes, the problem was that the path to that log file was `/tmp/ubuntu-xenial-16.04-cloudimg-console.log` and since Windows doesn't have a `/tmp` directory (unlike OSX and Linux), loading the VM would fail. Simply changing `/tmp` to `c:/users/myname` and saving worked in all cases I helped with.

**Comment by dannylamb** [comment]
Chances are, users who would want to use the .ova have a windows machine.  Is it more appropriate to make the defaults a C:/ something or other?

**Comment by manez** [comment]
Going off impressions from the last couple of camps, windows users were in the minority. I think as long as we document the fix for different scenarios, the current configuration is probably fine for more users.

**Comment by mjordan** [comment]
I agree with @manez. Also, AFAIK Windows puts it temp directory under the user's home directory, so c:/temp won't work, each machine will have a different path to temp.

Is it possible to create an .ova that doesn't have a serial port, thereby avoiding the need for that file entirely?

**Comment by jonathangreen** [comment]
Maybe we could throw this in our vagrant file: 
```
vb.customize [ 'modifyvm', :id, '--uartmode1', 'disconnected']
```
Some info including this suggestion here: https://github.com/hashicorp/vagrant/issues/9425
